import { D } from "./entry";

/* ── Pack B2 · abstracción, sociedad, argumentación (MCER B2) ── */

export const PACK_B2: import("../types").VocabWord[] = [
  /* ══ conceptos abstractos (léxico académico B2) ══ */
  D("d4-concetto", "concetto", "concepto", "konˈtʃɛtto", "sostantivo", "astratto", "B2", 3, { it: "Il concetto di bellezza cambia col tempo.", es: "El concepto de belleza cambia con el tiempo." }, { gender: "m", plural: "concetti" }),
  D("d4-aspetto", "aspetto", "aspecto / pinta", "asˈpɛtto", "sostantivo", "astratto", "B2", 2, { it: "Analizziamo l'aspetto economico del problema.", es: "Analizamos el aspecto económico del problema." }, { gender: "m", note: "aspetto = aspecto (faceta) Y apariencia (avere un bell'aspetto)." }),
  D("d4-fattore", "fattore", "factor", "ˈfattoːre", "sostantivo", "astratto", "B2", 3, { it: "Il fattore tempo è decisivo.", es: "El factor tiempo es decisivo." }, { gender: "m", plural: "fattori" }),
  D("d4-contesto", "contesto", "contexto", "konˈtɛsto", "sostantivo", "astratto", "B2", 3, { it: "Nel contesto attuale, è una scelta sensata.", es: "En el contexto actual, es una elección sensata." }, { gender: "m" }),
  D("d4-ambito", "ambito", "ámbito / campo", "ˈambito", "sostantivo", "astratto", "B2", 3, { it: "Lavoro nell'ambito della ricerca.", es: "Trabajo en el ámbito de la investigación." }, { gender: "m", collocations: ["nell'ambito di"] }),
  D("d4-settore", "settore", "sector", "ˈsettore", "sostantivo", "lavoro", "B2", 3, { it: "Il settore terziario cresce in Italia.", es: "El sector terciario crece en Italia." }, { gender: "m" }),
  D("d4-fenomeno", "fenomeno", "fenómeno", "feˈnɔːmeno", "sostantivo", "astratto", "B2", 3, { it: "L'inflazione è un fenomeno complesso.", es: "La inflación es un fenómeno complejo." }, { gender: "m", plural: "fenomeni" }),
  D("d4-sviluppo", "sviluppo", "desarrollo", "zviˈluppo", "sostantivo", "astratto", "B2", 3, { it: "Lo sviluppo sostenibile è una priorità.", es: "El desarrollo sostenible es una prioridad." }, { gender: "m", collocations: ["sviluppo sostenibile", "paese in via di sviluppo"] }),
  D("d4-vantaggio", "vantaggio", "ventaja", "vanˈtaddʒo", "sostantivo", "astratto", "B2", 2, { it: "Parlare spagnolo è un vantaggio per l'italiano.", es: "Hablar español es una ventaja para el italiano." }, { gender: "m", ant: ["svantaggio"] }),
  D("d4-svantaggio", "svantaggio", "desventaja", "zvanˈtaddʒo", "sostantivo", "astratto", "B2", 3, { it: "Lo svantaggio di vivere in centro è il rumore.", es: "La desventaja de vivir en el centro es el ruido." }, { gender: "m", ant: ["vantaggio"] }),
  D("d4-conseguenza", "conseguenza", "consecuencia", "konseˈɡwenntsa", "sostantivo", "astratto", "B2", 2, { it: "Di conseguenza, i prezzi sono saliti.", es: "En consecuencia, los precios subieron." }, { gender: "f", collocations: ["di conseguenza", "come conseguenza di"] }),
  D("d4-causa", "causa", "causa", "ˈkauːza", "sostantivo", "astratto", "B2", 2, { it: "La causa del ritardo è il maltempo.", es: "La causa del retraso es el mal tiempo." }, { gender: "f", collocations: ["a causa di"] }),
  D("d4-effetto", "effetto", "efecto", "efˈfetto", "sostantivo", "astratto", "B2", 2, { it: "L'effetto serra aumenta.", es: "El efecto invernadero aumenta." }, { gender: "m", plural: "effetti", collocations: ["effetto serra", "in effetti"] }),
  D("d4-scopo", "scopo", "propósito / finalidad", "ˈskopo", "sostantivo", "astratto", "B2", 3, { it: "Lo scopo del corso è la fluidità.", es: "El propósito del curso es la fluidez." }, { gender: "m", syn: ["obiettivo", "finale"], collocations: ["a scopo di", "con lo scopo di"] }),
  D("d4-obiettivo", "obiettivo", "objetivo / meta", "objetˈtiːvo", "sostantivo", "astratto", "B2", 2, { it: "Il mio obiettivo è il C1 entro dicembre.", es: "Mi objetivo es el C1 antes de diciembre." }, { gender: "m" }),
  D("d4-risorsa", "risorsa", "recurso", "riˈsorsa", "sostantivo", "astratto", "B2", 3, { it: "Le risorse naturali non sono infinite.", es: "Los recursos naturales no son infinitos." }, { gender: "f", plural: "risorse" }),
  D("d4-criterio", "criterio", "criterio", "kriˈteːrjo", "sostantivo", "astratto", "B2", 4, { it: "Quali criteri usiamo per valutare?", es: "¿Qué criterios usamos para evaluar?" }, { gender: "m", plural: "criteri" }),
  D("d4-parametro", "parametro", "parámetro", "paraˈmeːtro", "sostantivo", "astratto", "B2", 4, { it: "I parametri di valutazione sono chiari.", es: "Los parámetros de evaluación son claros." }, { gender: "m" }),
  D("d4-ipotesi", "ipotesi", "hipótesis", "ipoˈteːzi", "sostantivo", "astratto", "B2", 3, { it: "L'ipotesi è stata confermata dai dati.", es: "La hipótesis fue confirmada por los datos." }, { gender: "f", plural: "ipotesi" }),
  D("d4-teoria", "teoria", "teoría", "teoˈriːa", "sostantivo", "astratto", "B2", 3, { it: "In teoria sì, in pratica no.", es: "En teoría sí, en la práctica no." }, { gender: "f", collocations: ["in teoria"] }),
  D("d4-argomento", "argomento", "argumento / tema", "arɡoˈmento", "sostantivo", "astratto", "B2", 2, { it: "Un argomento convincente a favore dell'italiano.", es: "Un argumento convincente a favor del italiano." }, { gender: "m", note: "argomento = argumento (razonamiento) Y tema (di una conversazione)." }),
  D("d4-prova", "prova", "prueba / evidencia", "ˈprɔːva", "sostantivo", "astratto", "B2", 2, { it: "Le prove dimostrano la sua innocenza.", es: "Las pruebas demuestran su inocencia." }, { gender: "f", plural: "prove", collocations: ["prove scientifiche", "mettere alla prova"] }),
  D("d4-mezzo", "mezzo", "medio / medio de", "ˈmɛddzo", "sostantivo", "astratto", "B2", 2, { it: "Il treno è il mezzo più ecologico.", es: "El tren es el medio más ecológico." }, { gender: "m", plural: "mezzi", collocations: ["mezzo di trasporto", "mezzi di comunicazione"] }),
  D("d4-sfida", "sfida", "desafío / reto", "ˈsfiːda", "sostantivo", "astratto", "B2", 3, { it: "La transizione ecologica è una sfida globale.", es: "La transición ecológica es un desafío global." }, { gender: "f" }),
  D("d4-tendenza", "tendenza", "tendencia", "tenˈdɛntsa", "sostantivo", "astratto", "B2", 3, { it: "La tendenza dei giovani a emigrare.", es: "La tendencia de los jóvenes a emigrar." }, { gender: "f", plural: "tendenze" }),

  /* ══ verbos de argumentación B2 ══ */
  D("d4-ribattere", "ribattere", "replicar / refutar", "ribˈbatteːre", "verbo", "connettivi", "B2", 4, { it: "Ribatto che i dati dicono altro.", es: "Replico que los datos dicen otra cosa." }),
  D("d4-obiettare", "obiettare", "objetar / oponer", "obietˈtaːre", "verbo", "connettivi", "B2", 4, { it: "Obietto: mancano le fonti.", es: "Objeto: faltan las fuentes." }),
  D("d4-contestare", "contestare", "impugnar / rebatir / protestar", "kontesˈtaːre", "verbo", "connettivi", "B2", 3, { it: "Gli studenti contestano la decisione.", es: "Los estudiantes protestan la decisión." }),
  D("d4-smentire", "smentire", "desmentir", "zmenˈtiːre", "verbo", "comunicazione", "B2", 4, { it: "Il ministero smentisce la notizia.", es: "El ministero desmiente la noticia." }, { ant: ["confermare"] }),
  D("d4-ipotizzare", "ipotizzare", "plantear hipótesis / hipotetizar", "ipotitˈtsaːre", "verbo", "astratto", "B2", 4, { it: "Ipotizziamo tre scenari possibili.", es: "Planteamos tres escenarios posibles." }),
  D("d4-dedurre", "dedurre", "deducir / inferir", "deˈdurre", "verbo", "astratto", "B2", 5, { it: "Deduciamo che l'ipotesi è valida.", es: "Deducimos que la hipótesis es válida." }),
  D("d4-evidenziare", "evidenziare", "resaltar / poner de relieve", "evidenˈtsjaːre", "verbo", "connettivi", "B2", 3, { it: "Il report evidenzia due problemi.", es: "El informe resalta dos problemas." }),
  D("d4-rilevare", "rilevare", "señalar / detectar", "rileˈvaːre", "verbo", "connettivi", "B2", 4, { it: "Lo studio rileva un calo delle vendite.", es: "El estudio señala una caída de las ventas." }),
  D("d4-constatare", "constatare", "constatar / verificar", "konstaˈtaːre", "verbo", "connettivi", "B2", 4, { it: "Constato che il livello è migliorato.", es: "Constato que el nivel ha mejorado." }),
  D("d4-sottovalutare", "sottovalutare", "subestimar", "sottovaluˈtaːre", "verbo", "astratto", "B2", 3, { it: "Non sottovalutare la potenza del congiuntivo!", es: "¡No subestimes el poder del subjuntivo!" }, { ant: ["sopravvalutare"] }),
  D("d4-sopravvalutare", "sopravvalutare", "sobreestimar", "sopravvaluˈtaːre", "verbo", "astratto", "B2", 3, { it: "Sopravvaluti le mie capacità di cuoco.", es: "Sobreestimas mis capacidades de cocinero." }, { ant: ["sottovalutare"] }),
  D("d4-far fronte", "far fronte a", "hacer frente a", "far ˈfronte a", "espressione", "astratto", "B2", 3, { it: "Le famiglie fanno fatica a far fronte alle bollette.", es: "Las familias tienen dificultad para hacer frente a las recibos." }),
  D("d4-prendereposizione", "prendere posizione", "tomar posición", "ˈprɛndere positˈtsjoːne", "espressione", "connettivi", "B2", 3, { it: "Il governo prende posizione sul dibattito.", es: "El gobierno toma posición en el debate." }),

  /* ══ economía B2 ══ */
  D("d4-crescita", "crescita", "crecimiento", "kreˈʃiːta", "sostantivo", "finanze", "B2", 3, { it: "La crescita del PIL è dell'1%.", es: "El crecimiento del PIB es del 1%." }, { gender: "f", ant: ["recessione", "calo"] }),
  D("d4-recessione", "recessione", "recesión", "retʃesˈsjoːne", "sostantivo", "finanze", "B2", 4, { it: "L'Italia entra in recessione tecnica.", es: "Italia entra en recesión técnica." }, { gender: "f", ant: ["crescita"] }),
  D("d4-inflazione", "inflazione", "inflación", "inflaˈtsjoːne", "sostantivo", "finanze", "B2", 3, { it: "L'inflazione erode i salari.", es: "La inflación erosiona los salarios." }, { gender: "f" }),
  D("d4-concorrenza", "concorrenza", "competencia (mercado)", "konkorˈrentsa", "sostantivo", "finanze", "B2", 4, { it: "La concorrenza abbassa i prezzi.", es: "La competencia baja los precios." }, { gender: "f" }),
  D("d4-impresa", "impresa", "empresa / hazaña", "imˈpreːza", "sostantivo", "lavoro", "B2", 3, { it: "Un'impresa familiare con cinquant'anni di storia.", es: "Una empresa familiar con cincuenta años de historia." }, { gender: "f", syn: ["azienda"], note: "impresa = empresa Y hazaña (che impresa! = ¡qué hazaña!)." }),
  D("d4-fallimento", "fallimento", "quiebra / fracaso", "falliˈmento", "sostantivo", "finanze", "B2", 4, { it: "Il fallimento dell'azienda ha sorpreso tutti.", es: "La quiebra de la empresa sorprendió a todos." }, { gender: "m" }),
  D("d4-bilancio", "bilancio", "presupuesto / balance", "biˈlantʃo", "sostantivo", "finanze", "B2", 3, { it: "Il bilancio dello Stato passa in Parlamento.", es: "El presupuesto del Estado pasa en el Parlamento." }, { gender: "m", collocations: ["bilancio dello stato"] }),
  D("d4-salario", "salario / retribuzione", "salario / sueldo", "saˈlaːrjo", "sostantivo", "lavoro", "B2", 3, { it: "Un salario minimo garantito per legge.", es: "Un salario mínimo garantizado por ley." }, { gender: "m" }),

  /* ══ política e instituciones B2 ══ */
  D("d4-governo", "governo", "gobierno", "ˈɡoverno", "sostantivo", "istituzioni", "B2", 2, { it: "Il governo approva il decreto.", es: "El gobierno aprueba el decreto." }, { gender: "m" }),
  D("d4-parlamento", "parlamento", "parlamento", "parlaˈmento", "sostantivo", "istituzioni", "B2", 3, { it: "Il Parlamento italiano è bicamerale.", es: "El Parlamento italiano es bicameral." }, { gender: "m", note: "En Italia: Camera (diputados) + Senato (senadores) = Parlamento." }),
  D("d4-ministro", "ministro", "ministro", "miˈniːstro", "sostantivo", "istituzioni", "B2", 3, { it: "Il ministro dell'Istruzione presenta la riforma.", es: "El ministro de Educación presenta la reforma." }, { gender: "m", plural: "ministri" }),
  D("d4-elezioni", "elezioni", "elecciones", "eletˈtsjoːni", "sostantivo", "istituzioni", "B2", 3, { it: "Alle elezioni vota il 70% degli elettori.", es: "En las elecciones vota el 70% de los electores." }, { gender: "f", plural: "elezioni", collocations: ["andare a votare", "seggi"] }),
  D("d4-partito", "partito", "partido", "parˈtiːto", "sostantivo", "istituzioni", "B2", 3, { it: "Il partito di maggioranza guida il governo.", es: "El partido de mayoría guía el gobierno." }, { gender: "m" }),
  D("d4-opposizione", "opposizione", "oposición", "oppositˈtsjoːne", "sostantivo", "istituzioni", "B2", 3, { it: "L'opposizione critica la manovra economica.", es: "La oposición critica la maniobra económica." }, { gender: "f" }),
  D("d4-costituzione", "costituzione", "constitución", "kostitutˈtsjoːne", "sostantivo", "istituzioni", "B2", 3, { it: "La Costituzione italiana è del 1948.", es: "La Constitución italiana es de 1948." }, { gender: "f" }),
  D("d4-riforma", "riforma", "reforma", "riˈfɔrma", "sostantivo", "istituzioni", "B2", 3, { it: "La riforma della giustizia è in discussione.", es: "La reforma de la justicia está en discusión." }, { gender: "f" }),
  D("d4-referendum", "referendum", "referéndum", "referɛnˈdum", "sostantivo", "istituzioni", "B2", 4, { it: "Il referendum abrogativo del 2011.", es: "El referéndum abrogativo de 2011." }, { gender: "m" }),
  D("d4-decreto", "decreto legge", "decreto ley", "deˈkreːto", "sostantivo", "istituzioni", "B2", 4, { it: "Il decreto legge entra in vigore domani.", es: "El decreto ley entra en vigor mañana." }, { gender: "m" }),

  /* ══ cuestiones sociales B2 ══ */
  D("d4-immigrazione", "immigrazione", "inmigración", "imiɡratˈtsjoːne", "sostantivo", "istituzioni", "B2", 3, { it: "L'immigrazione è un tema divisivo.", es: "La inmigración es un tema divisorio." }, { gender: "f", ant: ["emigrazione"] }),
  D("d4-integrazione", "integrazione", "integración", "integraˈtsjoːne", "sostantivo", "istituzioni", "B2", 3, { it: "L'integrazione passa dalla scuola.", es: "La integración pasa por la escuela." }, { gender: "f" }),
  D("d4-discriminazione", "discriminazione", "discriminación", "diskriminaˈtsjoːne", "sostantivo", "istituzioni", "B2", 4, { it: "Discriminazione di genere sul lavoro.", es: "Discriminación de género en el trabajo." }, { gender: "f" }),
  D("d4-parita", "parità di genere", "igualdad de género", "paˈriːta", "sostantivo", "istituzioni", "B2", 4, { it: "La parità salariale non è ancora una realtà.", es: "La igualdad salarial aún no es una realidad." }, { gender: "f" }),
  D("d4-poverta", "povertà", "pobreza", "poverˈta", "sostantivo", "istituzioni", "B2", 3, { it: "La povertà educativa colpisce i minori.", es: "La pobreza educativa golpea a los menores." }, { gender: "f", ant: ["ricchezza"] }),
  D("d4-disuguaglianza", "disuguaglianza", "desigualdad", "disuɡuaʎʎanˈntsa", "sostantivo", "istituzioni", "B2", 4, { it: "La disuguaglianza cresce tra Nord e Sud.", es: "La desigualdad crece entre el Norte y el Sur." }, { gender: "f", ant: ["uguaglianza"] }),
  D("d4-dipendenza", "dipendenza", "dependencia / adicción", "dipenˈdɛntsa", "sostantivo", "salud", "B2", 3, { it: "La dipendenza dallo smartphone è reale.", es: "La dependencia del teléfono es real." }, { gender: "f" }),
  D("d4-bullismo", "bullismo", "acoso escolar", "ˈbullizmo", "sostantivo", "studi", "B2", 3, { it: "Il bullismo non è uno scherzo.", es: "El acoso escolar no es una broma." }, { gender: "m" }),
  D("d4-violenza", "violenza", "violencia", "vioˈlɛntsa", "sostantivo", "istituzioni", "B2", 3, { it: "Zero tolleranza alla violenza sulle donne.", es: "Cero tolerancia a la violencia contra las mujeres." }, { gender: "f" }),
  D("d4-emarginazione", "emarginazione", "marginación / exclusión", "emardʒinaˈtsjoːne", "sostantivo", "istituzioni", "B2", 5, { it: "L'emarginazione sociale genera malessere.", es: "La marginación social genera malestar." }, { gender: "f", syn: ["esclusione sociale"] }),

  /* ══ conectores B2 ══ */
  D("d4-tuttavia", "tuttavia", "sin embargo / no obstante", "tutˈtaːvia", "congiunzione", "connettivi", "B2", 3, { it: "Il piano è buono, tuttavia costoso.", es: "El plan es bueno, sin embargo costoso." }, { syn: ["tuttavvia", "nondimeno"], register: "formale" }),
  D("d4-nonostante", "nonostante", "a pesar de / pese a", "nonoˈstante", "preposizione", "connettivi", "B2", 3, { it: "Esce nonostante la pioggia.", es: "Sale a pesar de la lluvia." }, { note: "nonostante + sustantivo o congiuntivo: nonostante piova. Como 'a pesar de que'." }),
  D("d4-sebbene", "sebbene", "aunque / si bien", "sebˈbeːne", "congiunzione", "connettivi", "B2", 4, { it: "Sebbene sia stanco, continua a studiare.", es: "Aunque esté cansado, continúa estudiando." }, { note: "sebbene + congiuntivo — concesión formal B2/C1." }),
  D("d4-affinche", "affinché", "para que / a fin de que", "affinˈke", "congiunzione", "connettivi", "B2", 4, { it: "Spiego lentamente affinché tutti capiscano.", es: "Explico lentamente para que todos entiendan." }, { note: "affinché + congiuntivo — finalidad formal." }),
  D("d4-purché", "purché", "con tal de que / siempre que", "purˈke", "congiunzione", "connettivi", "B2", 4, { it: "Vengo purché tu paghi il cinema!", es: "¡Voy con tal de que tú pagues el cine!" }, { note: "purché + congiuntivo — condición restrictiva." }),
  D("d4-nel-caso", "nel caso in cui", "en caso de que", "nel ˈkaːzo in ˈui", "congiunzione", "connettivi", "B2", 4, { it: "Nel caso in cui piova, rinunciamo.", es: "En caso de que llueva, desistimos." }),
  D("d4-per-quanto-ne-so", "per quanto ne so", "por lo que sé / que yo sepa", "per ˈkwanto ne so", "espressione", "connettivi", "B2", 3, { it: "Per quanto ne so, l'esame è a giugno.", es: "Por lo que sé, el examen es en junio." }),
  D("d4-quanto-a", "quanto a", "en cuanto a / respecto a", "ˈkwanto a", "preposizione", "connettivi", "B2", 3, { it: "Quanto al prezzo, ne parliamo dopo.", es: "En cuanto al precio, hablamos después." }, { syn: ["per quanto riguarda"] }),

  /* ══ adjetivos B2 ══ */
  D("d4-puntuale", "puntuale", "puntual", "punˈtwale", "aggettivo", "lavoro", "B2", 3, { it: "Il treno Italo è sempre puntuale.", es: "El tren Italo es siempre puntual." }),
  D("d4-credibile", "credibile", "creíble", "ˈkrɛːdibile", "aggettivo", "astratto", "B2", 4, { it: "Una fonte credibile e verificabile.", es: "Una fuente creíble y verificable." }, { ant: ["incredibile"] }),
  D("d4-rilevante", "rilevante", "relevante / pertinente", "rileˈvante", "aggettivo", "astratto", "B2", 4, { it: "Un dettaglio rilevante per l'indagine.", es: "Un detalle relevante para la investigación." }, { syn: ["pertinente"] }),
  D("d4-appropriato", "appropriato", "apropiado / adecuado", "approˈprjaːto", "aggettivo", "astratto", "B2", 4, { it: "Usa un registro appropriato all'occasione.", es: "Usa un registro apropiado a la ocasión." }),
  D("d4-graduale", "graduale", "gradual", "graˈdwale", "aggettivo", "astratto", "B2", 4, { it: "Un miglioramento graduale e costante.", es: "Una mejora gradual y constante." }),
  D("d4-rigido", "rigido", "rígido / inflexible", "ˈriːdʒido", "aggettivo", "astratto", "B2", 3, { it: "Orari rigidi in fabbrica.", es: "Horarios rígidos en la fábrica." }, { ant: ["flessibile"] }),
  D("d4-flessibile", "flessibile", "flexible", "flesˈsiːbile", "aggettivo", "lavoro", "B2", 3, { it: "Il lavoro agile offre orari flessibili.", es: "El trabajo ágil ofrece horarios flexibles." }, { ant: ["rigido"] }),
  D("d4-essenziale", "essenziale", "esencial", "essenˈtsjaːle", "aggettivo", "astratto", "B2", 3, { it: "È essenziale praticare ogni giorno.", es: "Es esencial practicar cada día." }, { syn: ["fondamentale", "cruciale"] }),
  D("d4-trascurabile", "trascurabile", "despreciable / insignificante", "traskuˈraːbile", "aggettivo", "astratto", "B2", 5, { it: "Un errore trascurabile nel conteggio.", es: "Un error despreciable en el conteo." }),
  D("d4-evidente", "evidente", "evidente / obvio", "eviˈdɛnte", "aggettivo", "astratto", "B2", 3, { it: "È evidente che serve più pratica.", es: "Es evidente que hace falta más práctica." }),
  D("d4-corretto", "corretto", "correcto", "korˈrɛtto", "aggettivo", "astratto", "B2", 3, { it: "Il suo italiano è ormai corretto.", es: "Su italiano ya es correcto." }, { ant: ["sbagliato"] }),
  D("d4-esaustivo", "esaustivo", "exhaustivo / completo", "esauˈstiːvo", "aggettivo", "astratto", "B2", 4, { it: "Una spiegazione esaustiva e chiara.", es: "Una explicación exhaustiva y clara." }),

  /* ══ locuciones idiomáticas B2 ══ */
  D("d4-andare-in-fumo", "andare in fumo", "irse humo / fracasar", "ˈandare in ˈfjuːmo", "espressione", "astratto", "B2", 4, { it: "I miei piani di vacanza sono andati in fumo.", es: "Mis planes de vacaciones se fueron en humo." }, { register: "colloquiale" }),
  D("d4-prendere-decisione", "prendere una decisione", "tomar una decisión", "ˈprɛndere una detʃiˈzjoːne", "espressione", "astratto", "B2", 2, { it: "È ora di prendere una decisione importante.", es: "Es hora de tomar una decisión importante." }),
  D("d4-dare-priorita", "dare priorità", "dar prioridad", "daːre prioriˈta", "espressione", "astratto", "B2", 3, { it: "Do priorità allo studio dell'italiano.", es: "Doy prioridad al estudio del italiano." }),
  D("d4-prendere-sul-serio", "prendere sul serio", "tomar en serio", "ˈprɛndere sul ˈseːrjo", "espressione", "relazioni", "B2", 3, { it: "Finalmente prendono sul serio il mio progetto.", es: "Finalmente toman en serio mi proyecto." }),
  D("d4-alla-lunga", "alla lunga", "a la larga", "alla ˈluŋɡa", "espressione", "astratto", "B2", 4, { it: "Alla lunga, la costanza paga sempre.", es: "A la larga, la constancia siempre paga." }),
  D("d4-in-conclusione", "in conclusione", "en conclusión", "in konkluˈzjoːne", "espressione", "connettivi", "B2", 3, { it: "In conclusione, il congiuntivo si impara praticando.", es: "En conclusión, el subjuntivo se aprende practicando." }),
  D("d4-per-esempio", "a titolo di esempio", "a título de ejemplo", "a ˈtiːtolo di esˈsempjo", "espressione", "connettivi", "B2", 4, { it: "A titolo di esempio, cito Dante.", es: "A título de ejemplo, cito a Dante." }, { register: "formale" }),
];
