import { D } from "./entry";

/* ── Pack B1 · sociedad, trabajo, medios, opinión (MCER B1) ── */

export const PACK_B1: import("../types").VocabWord[] = [
  /* ══ verbos de opinión y discurso B1 ══ */
  D("d3-sostenere", "sostenere", "sostener / defender (una tesis)", "sosteˈnɛːre", "verbo", "connettivi", "B1", 2, { it: "Sostengo che l'italiano si impari leggendo.", es: "Sostengo que el italiano se aprende leyendo." }, { note: "sostenere che + congiuntivo — verbo clave para ensayos y debates B1/B2." }),
  D("d3-affermare", "affermare", "afirmar", "afferˈmaːre", "verbo", "connettivi", "B1", 3, { it: "L'articolo afferma che l'economia cresce.", es: "El artículo afirma que la economía crece." }),
  D("d3-dimostrare", "dimostrare", "demostrar", "dimostˈraːre", "verbo", "connettivi", "B1", 3, { it: "I dati dimostrano il contrario.", es: "Los datos demuestran lo contrario." }),
  D("d3-ammettere", "ammettere", "admitir", "amˈmɛttere", "verbo", "connettivi", "B1", 3, { it: "Ammetto di aver sbagliato.", es: "Admito haberme equivocado." }, { note: "ammettere DI + infinitivo = admitir haber hecho." }),
  D("d3-negare", "negare", "negar", "ˈneːɡare", "verbo", "connettivi", "B1", 3, { it: "Nega di conoscere il sospettato.", es: "Niega conocer al sospechoso." }, { ant: ["confermare"] }),
  D("d3-confermare", "confermare", "confirmar", "konferˈmaːre", "verbo", "connettivi", "B1", 2, { it: "Ti confermo l'appuntamento di domani.", es: "Te confirmo la cita de mañana." }, { ant: ["smentire"] }),
  D("d3-approfondire", "approfondire", "profundizar", "approfonˈdiːre", "verbo", "studi", "B1", 4, { it: "Voglio approfondire la storia italiana.", es: "Quiero profundizar en la historia italiana." }),
  D("d3-riassumere", "riassumere", "resumir", "riasˈsuːmere", "verbo", "studi", "B1", 3, { it: "Riassumo il capitolo in cinque righe.", es: "Resumo el capítulo en cinco líneas." }, { related: ["riassunto"] }),
  D("d3-tradurre", "tradurre", "traducir", "traˈdurre", "verbo", "studi", "B1", 2, { it: "Traduco dallo spagnolo all'italiano.", es: "Traduzco del español al italiano." }),
  D("d3-correggere", "correggere", "corregir", "korˈreddʒere", "verbo", "studi", "B1", 2, { it: "Il prof corregge i miei errori.", es: "El profesor corrige mis errores." }),
  D("d3-partecipare", "partecipare", "participar", "partetʃiˈpaːre", "verbo", "relazioni", "B1", 2, { it: "Partecipo a un corso di cucina.", es: "Participo en un curso de cocina." }, { note: "partecipare A algo (con a, como español 'en'). partecipare di = compartir una cualidad." }),
  D("d3-occuparsi", "occuparsi di", "encargarse de / ocuparse de", "okkuˈparsi", "verbo", "lavoro", "B1", 2, { it: "Mi occupo io delle pratiche burocratiche.", es: "Yo me encargo de los trámites burocráticos." }),
  D("d3-fidarsi", "fidarsi", "confiar (en alguien)", "fiˈdarsi", "verbo", "relazioni", "B1", 2, { it: "Mi fido di te al cento per cento.", es: "Confío en ti al cien por cien." }, { collocations: ["fidarsi di"] }),
  D("d3-sfidare", "sfidare", "desafiar / retar", "sfiˈdaːre", "verbo", "relazioni", "B1", 3, { it: "Sfido la sorte e parto senza ombrello.", es: "Desafío a la suerte y salgo sin paraguas." }),
  D("d3-approfittare", "approfittare", "aprovechar", "approfitˈtaːre", "verbo", "astratto", "B1", 3, { it: "Approfitto dell'offerta e compro due biglietti.", es: "Aprovecho la oferta y compro dos billetes." }),
  D("d3-sprecare", "sprecare", "desperdiciar / malgastar", "ˈsprekare", "verbo", "astratto", "B1", 3, { it: "Non sprecare l'acqua, chiudi il rubinetto!", es: "¡No desperdicies el agua, cierra el grifo!" }, { ant: ["risparmiare"] }),
  D("d3-inquinare", "inquinare", "contaminar", "inkwiˈnaːre", "verbo", "attualita", "B1", 3, { it: "Le fabbriche inquinano il fiume.", es: "Las fábricas contaminan el río." }),
  D("d3-condividere", "condividere", "compartir", "kondiˈviːdere", "verbo", "relazioni", "B1", 2, { it: "Condivido l'appartamento con un collega.", es: "Comparto el apartamento con un colega." }),
  D("d3-superare", "superare", "superar / aprobar (examen)", "suˈpeːrare", "verbo", "studi", "B1", 2, { it: "Ho superato l'esame B1 al primo tentativo!", es: "¡Superé el examen B1 al primer intento!" }, { syn: ["passare (l'esame)"], note: "'Aprobar un examen' = superare/passare un esame, ¡no 'approvare' (que es del profesor)!" }),
  D("d3-bocciare", "bocciare", "reprobar (a alguien)", "botˈtʃaːre", "verbo", "studi", "B1", 3, { it: "Il prof l'ha bocciato all'orale.", es: "El profesor lo reprobó en el oral." }, { note: "essere bocciato = reprobar (el alumno); approvare = aprobar (el profesor/examinador)." }),
  D("d3-presentarsi", "presentarsi", "presentarse", "presenˈtarsi", "verbo", "lavoro", "B1", 2, { it: "Mi presento: sono Ana, candidato per il posto.", es: "Me presento: soy Ana, candidata al puesto." }),
  D("d3-assumere", "assumere", "contratar / asumir", "asˈsuːmere", "verbo", "lavoro", "B1", 3, { it: "L'azienda assume personale qualificato.", es: "La empresa contrata personal cualificado." }, { note: "assumere = contratar (empresa) Y asumir (una responsabilidad). 'Ser contratado' = essere assunto." }),
  D("d3-licenziare", "licenziare", "despedir", "litʃenˈtsjaːre", "verbo", "lavoro", "B1", 3, { it: "L'hanno licenziato dopo dieci anni.", es: "Lo despidieron después de diez años." }, { ant: ["assumere"] }),
  D("d3-dimettersi", "dimettersi", "renunciar (al empleo)", "dimetˈtersi", "verbo", "lavoro", "B1", 3, { it: "Si è dimesso per aprire un'attività propria.", es: "Renunció para abrir un negocio propio." }, { note: "'Renunciar al trabajo' = dimettersi / dare le dimissioni, ¡no 'rinunciare' (a algo/una cosa)!" }),
  D("d3-promuovere", "promuovere", "promover / ascender", "promoˈvwɔːvere", "verbo", "lavoro", "B1", 3, { it: "L'hanno promossa a direttrice.", es: "La ascendieron a directora." }),
  D("d3-sbarcare", "sbarcare il lunario", "ir tirando / sobrevivir", "zbarˈkaːre il luˈnaːrjo", "espressione", "lavoro", "B1", 5, { it: "Con due lavori sbarco il lunario.", es: "Con dos trabajos voy tirando." }, { register: "colloquiale" }),

  /* ══ conectores B1 ══ */
  D("d3-invece", "invece", "en cambio / en lugar de", "inˈvɛtse", "congiunzione", "connettivi", "B1", 1, { it: "Io bevo tè, invece lui vuole un caffè.", es: "Yo bebo té, en cambio él quiere un café." }, { collocations: ["invece di"], note: "invece di + infinitivo = en lugar de hacer." }),
  D("d3-bensi", "bensì", "sino que / sino", "benˈsi", "congiunzione", "connettivi", "B1", 4, { it: "Non è pigro, bensì stanco.", es: "No es perezoso, sino que está cansado." }, { register: "formale", note: "no…bensì = no…sino que. Conectivo formal para contrastar negaciones." }),
  D("d3-pertanto", "pertanto", "por consiguiente / por lo tanto", "perˈtanto", "congiunzione", "connettivi", "B1", 3, { it: "È tardi, pertanto rimango a casa.", es: "Es tarde, por consiguiente me quedo en casa." }, { syn: ["dunque", "quindi"], register: "formale" }),
  D("d3-dunque", "dunque", "así que / entonces / por tanto", "ˈdunkwe", "congiunzione", "connettivi", "B1", 2, { it: "Dunque, vediamo: che facciamo oggi?", es: "Entonces, veamos: ¿qué hacemos hoy?" }),
  D("d3-peraltro", "peraltro", "por lo demás / además", "perˈaltro", "congiunzione", "connettivi", "B1", 4, { it: "È un buon lavoro, peraltro mal pagato.", es: "Es un buen trabajo, por lo demás mal pagado." }, { register: "formale" }),
  D("d3-cioe", "cioè", "es decir / o sea", "tʃoˈɛ", "congiunzione", "connettivi", "B1", 1, { it: "Vado dal medico, cioè... dal dentista!", es: "Voy al médico, es decir... ¡al dentista!" }),
  D("d3-ossia", "ossia", "o sea / es decir", "osˈsia", "congiunzione", "connettivi", "B1", 4, { it: "Il Verde, ossia il partito ecologista.", es: "El Verde, o sea, el partido ecologista." }, { syn: ["ovvero"], register: "formale" }),
  D("d3-ovvero", "ovvero", "o sea / o bien", "ovˈvɛːro", "congiunzione", "connettivi", "B1", 3, { it: "Rispondi sì o no, ovvero taci.", es: "Responde sí o no, o bien calla." }),
  D("d3-inoltre", "inoltre", "además", "inˈoltre", "congiunzione", "connettivi", "B1", 2, { it: "È economica e inoltre è centrale.", es: "Es económica y además está céntrica." }, { syn: ["peraltro", "in aggiunta"] }),
  D("d3-perquanto", "per quanto", "por más que / si bien", "per ˈkwanto", "congiunzione", "connettivi", "B1", 4, { it: "Per quanto provi, non riesco a capirlo.", es: "Por más que intente, no consigo entenderlo." }, { note: "per quanto + congiuntivo — concesión formal." }),
  D("d3-anzi", "anzi", "al contrario / más bien", "ˈantsi", "congiunzione", "connettivi", "B1", 3, { it: "Non è un problema, anzi, un vantaggio!", es: "No es un problema, ¡al contrario, una ventaja!" }),

  /* ══ trabajo B1 ══ */
  D("d3-disoccupazione", "disoccupazione", "desempleo / paro", "diskkupaˈtsjoːne", "sostantivo", "lavoro", "B1", 3, { it: "La disoccupazione giovanile è un problema serio.", es: "El desempleo juvenil es un problema serio." }, { gender: "f", collocations: ["sussidio di disoccupazione"] }),
  D("d3-pensione", "pensione", "pensión / pensión (hotel)", "penˈsjoːne", "sostantivo", "lavoro", "B1", 3, { it: "Mio padre è andato in pensione a sessantacinque anni.", es: "Mi padre se jubiló a los sesenta y cinco años." }, { gender: "f", collocations: ["andare in pensione"], note: "andare in pensione = jubilarse. En hotel: pensione completa = pensión completa." }),
  D("d3-congedo", "congedo (parentale)", "permiso (parental)", "konˈdʒeːdo", "sostantivo", "lavoro", "B1", 4, { it: "È in congedo parentale per tre mesi.", es: "Está de permiso parental por tres meses." }, { gender: "m" }),
  D("d3-sindacato", "sindacato", "sindicato", "sindaˈkaːto", "sostantivo", "lavoro", "B1", 3, { it: "Il sindacato ha proclamato lo sciopero.", es: "El sindicato ha convocado la huelga." }, { gender: "m", plural: "sindacati" }),
  D("d3-sciopero", "sciopero", "huelga", "ˈʃɔːpero", "sostantivo", "lavoro", "B1", 3, { it: "Sciopero generale dei trasporti venerdì.", es: "Huelga general de transportes el viernes." }, { gender: "m", collocations: ["fare sciopero"] }),
  D("d3-carriera", "carriera", "carrera (profesional)", "karˈriːera", "sostantivo", "lavoro", "B1", 3, { it: "Ha fatto carriera in pochi anni.", es: "Hizo carrera en pocos años." }, { gender: "f", collocations: ["fare carriera"] }),
  D("d3-tirocinio", "tirocinio", "prácticas (laborales)", "tiritʃiˈnio", "sostantivo", "lavoro", "B1", 4, { it: "Faccio un tirocinio in una casa editrice.", es: "Hago unas prácticas en una editorial." }, { gender: "m", note: "'Prácticas' = tirocinio/stage. Il 'praticantato' è per avvocati e medici." }),
  D("d3-competenza", "competenza", "competencia / habilidad", "kompeˈtɛntsa", "sostantivo", "lavoro", "B1", 3, { it: "Le sue competenze linguistiche sono ottime.", es: "Sus competencias lingüísticas son óptimas." }, { gender: "f", plural: "competenze" }),
  D("d3-curriculum-vitae", "curriculum vitae", "currículum vitae", "kuˈrikulum ˈviːtae", "sostantivo", "lavoro", "B1", 3, { it: "Allego il mio curriculum vitae alla candidatura.", es: "Adjunto mi currículum vitae a la candidatura." }, { gender: "m", plural: "curricula" }),
  D("d3-bustapaga", "busta paga", "nómina (salario)", "ˈbusta ˈpaːɡa", "sostantivo", "lavoro", "B1", 4, { it: "Controllo la busta paga ogni mese.", es: "Reviso la nómina cada mes." }, { gender: "f" }),
  D("d3-fisco", "fisco", "hacienda (impuestos)", "ˈfisko", "sostantivo", "finanze", "B1", 4, { it: "Il fisco italiano trattiene il 27%.", es: "La hacienda italiana retiene el 27%." }, { gender: "m", note: "'Hacienda' = fisco/agenzia delle entrate. Tasse = impuestos." }),
  D("d3-tassa", "tassa / imposta", "impuesto / tasa", "ˈtassa", "sostantivo", "finanze", "B1", 3, { it: "Le tasse universitarie sono alte.", es: "Las tasas universitarias son altas." }, { gender: "f", plural: "tasse", collocations: ["tasse universitarie", "evasione fiscale"] }),

  /* ══ estudios B1 ══ */
  D("d3-iscrizione", "iscrizione", "inscripción / matrícula", "iskritˈtsjoːne", "sostantivo", "studi", "B1", 3, { it: "L'iscrizione all'università scade a settembre.", es: "La inscripción a la universidad vence en septiembre." }, { gender: "f", collocations: ["fare l'iscrizione"] }),
  D("d3-facolta", "facoltà", "facultad / carrera", "fakolˈta", "sostantivo", "studi", "B1", 3, { it: "Mi sono iscritto alla facoltà di lettere.", es: "Me matriculé en la facultad de letras." }, { gender: "f" }),
  D("d3-borsastudio", "borsa di studio", "beca", "ˈborsa di ˈstuːdjo", "espressione", "studi", "B1", 3, { it: "Ho vinto una borsa di studio Erasmus.", es: "Gané una beca Erasmus." }),
  D("d3-tesi", "tesi", "tesis", "ˈteːzi", "sostantivo", "studi", "B1", 3, { it: "Discuto la tesi a marzo.", es: "Defiendo la tesis en marzo." }, { gender: "f", plural: "tesi", collocations: ["tesi di laurea", "discutere la tesi"] }),
  D("d3-relatore", "relatore", "director (de tesis) / ponente", "relaˈtoːre", "sostantivo", "studi", "B1", 4, { it: "Il mio relatore mi ha dato ottimi consigli.", es: "Mi director de tesis me dio óptimos consejos." }, { gender: "m" }),
  D("d3-appello", "appello", "convocatoria (de examen)", "apˈpɛllo", "sostantivo", "studi", "B1", 4, { it: "Sono andato al secondo appello.", es: "Fui a la segunda convocatoria." }, { gender: "m", note: "Sistema universitario italiano: gli 'appelli' son las convocatorias de examen (febbraio, giugno, luglio, settembre)." }),
  D("d3-credito", "credito formativo", "crédito (académico)", "ˈkrɛːdito", "sostantivo", "studi", "B1", 4, { it: "Questo esame vale 12 crediti formativi.", es: "Este examen vale 12 créditos académicos." }, { gender: "m" }),

  /* ══ medios de comunicación B1 ══ */
  D("d3-telegiornale", "telegiornale", "telediario", "teledʒorˈnaːle", "sostantivo", "comunicazione", "B1", 3, { it: "Il telegiornale delle otto.", es: "El telediario de las ocho." }, { gender: "m", syn: ["TG"] }),
  D("d3-intervista", "intervista", "entrevista", "interˈvista", "sostantivo", "comunicazione", "B1", 2, { it: "Il giornalista fa un'intervista alla ministra.", es: "El periodista hace una entrevista a la ministra." }, { gender: "f", plural: "interviste" }),
  D("d3-articolo-giornale", "articolo", "artículo", "arˈtiːkolo", "sostantivo", "comunicazione", "B1", 2, { it: "Ho letto un articolo interessante sul turismo.", es: "Leí un artículo interesante sobre el turismo." }, { gender: "m", plural: "articoli" }),
  D("d3-titolo", "titolo", "título / titular", "ˈtiːtolo", "sostantivo", "comunicazione", "B1", 2, { it: "Il titolo del giornale è scandalistico.", es: "El titular del periódico es sensacionalista." }, { gender: "m", plural: "titoli", note: "'Titular' (portada) = titolo/diocane... titolo di testa. titolo = título en general." }),
  D("d3-pubblicita", "pubblicità", "publicidad", "pubblikiˈta", "sostantivo", "comunicazione", "B1", 2, { it: "La pubblicità interrompe sempre il film.", es: "La publicidad interrumpe siempre la película." }, { gender: "f" }),
  D("d3-rubrica", "rubrica", "sección / rúbrica", "ˈruːbrika", "sostantivo", "comunicazione", "B1", 4, { it: "Scrivo per la rubrica di cultura.", es: "Escribo para la sección de cultura." }, { gender: "f" }),
  D("d3-edizione", "edizione", "edición / emisión", "editˈtsjoːne", "sostantivo", "comunicazione", "B1", 3, { it: "L'edizione delle 13 è la più vista.", es: "La edición de las 13 es la más vista." }, { gender: "f" }),
  D("d3-quotidiano", "quotidiano", "diario / periódico", "kuotiˈdjaːno", "sostantivo", "comunicazione", "B1", 3, { it: "Il Corriere della Sera è un quotidiano storico.", es: "El Corriere della Sera es un diario histórico." }, { gender: "m", syn: ["giornale"] }),
  D("d3-periodico", "periodico", "revista / periódico", "perioˈdiko", "sostantivo", "comunicazione", "B1", 3, { it: "Un periodico settimanale di politica.", es: "Una revista semanal de política." }, { gender: "m" }),

  /* ══ sociedad e instituciones B1 ══ */
  D("d3-legge", "legge", "ley", "ˈlɛddʒe", "sostantivo", "istituzioni", "B1", 2, { it: "Una nuova legge sul lavoro.", es: "Una nueva ley sobre el trabajo." }, { gender: "f", plural: "leggi", collocations: ["rispettare la legge", "approvare una legge"] }),
  D("d3-tribunale", "tribunale", "tribunal", "tribuˈnaːle", "sostantivo", "istituzioni", "B1", 3, { it: "Il processo si tiene al tribunale di Milano.", es: "El proceso se celebra en el tribunal de Milán." }, { gender: "m" }),
  D("d3-processo", "processo", "proceso / juicio", "proˈtʃɛsso", "sostantivo", "istituzioni", "B1", 3, { it: "Il processo per corruzione dura da anni.", es: "El proceso por corrupción dura años." }, { gender: "m" }),
  D("d3-giudice", "giudice", "juez", "ˈdʒuːditʃe", "sostantivo", "istituzioni", "B1", 3, { it: "Il giudice ha deciso: colpevole.", es: "El juez decidió: culpable." }, { gender: "m" }),
  D("d3-multa", "multa", "multa", "ˈmulta", "sostantivo", "istituzioni", "B1", 2, { it: "Ho preso una multa per divieto di sosta.", es: "Me pusieron una multa por prohibido estacionar." }, { gender: "f", plural: "multe", collocations: ["prendere una multa"] }),
  D("d3-denuncia", "denuncia", "denuncia / querella", "deˈnuntʃa", "sostantivo", "istituzioni", "B1", 3, { it: "Ha sporto denuncia contro il vicino.", es: "Presentó denuncia contra el vecino." }, { gender: "f", collocations: ["sporgere denuncia"] }),
  D("d3-vigile", "vigile (urbano)", "guardia urbano / policía municipal", "ˈviːdʒile", "sostantivo", "istituzioni", "B1", 3, { it: "Il vigile mi ha fatto la multa.", es: "El guardia me puso la multa." }, { gender: "m" }),
  D("d3-carabinieri", "carabinieri", "carabineros (policía)", "karabiˈnjɛːri", "sostantivo", "istituzioni", "B1", 3, { it: "Chiamo i carabinieri: c'è un ladro!", es: "Llamo a los carabineros: ¡hay un ladrón!" }, { gender: "m", plural: "carabinieri", note: "Cuerpo policial militar italiano. Siempre plural. Emergencias: 112." }),
  D("d3-furto", "furto", "robo / hurto", "ˈfurto", "sostantivo", "istituzioni", "B1", 3, { it: "C'è stato un furto in gioielleria.", es: "Hubo un robo en la joyería." }, { gender: "m", plural: "furti", related: ["ladro", "rubare"] }),
  D("d3-truffa", "truffa", "estafa", "ˈtruffa", "sostantivo", "istituzioni", "B1", 3, { it: "Una truffa online da centomila euro.", es: "Una estafa en línea de cien mil euros." }, { gender: "f" }),
  D("d3-carcere", "carcere", "cárcel", "ˈkartʃere", "sostantivo", "istituzioni", "B1", 3, { it: "L'hanno condannato a due anni di carcere.", es: "Lo condenaron a dos años de cárcel." }, { gender: "m" }),
  D("d3-condanna", "condanna", "condena", "konˈdanna", "sostantivo", "istituzioni", "B1", 3, { it: "La condanna a dieci anni.", es: "La condena a diez años." }, { gender: "f" }),
  D("d3-cittadinanza", "cittadinanza", "ciudadanía", "tʃittadiˈnanna", "sostantivo", "istituzioni", "B1", 3, { it: "Ha ottenuto la cittadinanza italiana.", es: "Obtuvo la ciudadanía italiana." }, { gender: "f" }),

  /* ══ medio ambiente B1 ══ */
  D("d3-rifiuti", "rifiuti", "residuos / basuras", "riˈfjuːti", "sostantivo", "attualita", "B1", 3, { it: "La raccolta differenziata dei rifiuti è obbligatoria.", es: "La recogida selectiva de residuos es obligatoria." }, { gender: "m", plural: "rifiuti", collocations: ["raccolta differenziata", "buttare i rifiuti"] }),
  D("d3-riciclaggio", "riciclaggio", "reciclaje", "ritʃiˈladdʒo", "sostantivo", "attualita", "B1", 3, { it: "Il riciclaggio della plastica salva il mare.", es: "El reciclaje del plástico salva el mar." }, { gender: "m", syn: ["riciclo"] }),
  D("d3-spreco", "spreco", "desperdicio", "ˈspreːko", "sostantivo", "attualita", "B1", 3, { it: "Lo spreco alimentare è uno scandalo.", es: "El desperdicio alimentario es un escándalo." }, { gender: "m" }),
  D("d3-rinnovabile", "rinnovabile", "renovable", "rinnoˈvaːbile", "aggettivo", "attualita", "B1", 4, { it: "Le energie rinnovabili sono il futuro.", es: "Las energías renovables son el futuro." }, { collocations: ["energia rinnovabile"] }),
  D("d3-emissioni", "emissioni", "emisiones", "emiˈssjoːni", "sostantivo", "attualita", "B1", 4, { it: "L'Italia deve ridurre le emissioni di CO2.", es: "Italia debe reducir las emisiones de CO2." }, { gender: "f" }),
  D("d3-siccita", "siccità", "sequía", "sitˈtʃiːta", "sostantivo", "attualita", "B1", 4, { it: "La siccità colpisce il Sud Italia.", es: "La sequía golpea al sur de Italia." }, { gender: "f", ant: ["alluvione"] }),
  D("d3-alluvione", "alluvione", "inundación", "alluˈvjoːne", "sostantivo", "attualita", "B1", 4, { it: "L'alluvione di Genova del 2011.", es: "La inundación de Génova de 2011." }, { gender: "f" }),
  D("d3-riscaldamento", "riscaldamento globale", "calentamiento global", "riskaldaˈmento ˈɡlobale", "espressione", "attualita", "B1", 4, { it: "Il riscaldamento globale è una sfida urgente.", es: "El calentamiento global es un reto urgente." }),
  D("d3-tutela", "tutela", "protección / tutela", "tuˈteːla", "sostantivo", "attualita", "B1", 4, { it: "La tutela del patrimonio artistico.", es: "La protección del patrimonio artístico." }, { gender: "f", collocations: ["tutela dell'ambiente"] }),

  /* ══ tecnología B1 ══ */
  D("d3-account", "account", "cuenta (usuario)", "akˈkaunt", "sostantivo", "tecnologia", "B1", 2, { it: "Creo un account per il corso online.", es: "Creo una cuenta para el curso en línea." }, { gender: "m" }),
  D("d3-privacy", "privacy", "privacidad", "ˈpraivisi", "sostantivo", "tecnologia", "B1", 3, { it: "Il GDPR tutela la privacy dei dati.", es: "El GDPR protege la privacidad de los datos." }, { gender: "f", register: "tecnico" }),
  D("d3-virus", "virus", "virus (informático)", "ˈviːrus", "sostantivo", "tecnologia", "B1", 3, { it: "Il computer ha preso un virus.", es: "La computadora contrajo un virus." }, { gender: "m" }),
  D("d3-aggiornamento", "aggiornamento", "actualización", "addʒornaˈmento", "sostantivo", "tecnologia", "B1", 3, { it: "Installo l'aggiornamento del sistema.", es: "Instalo la actualización del sistema." }, { gender: "m", collocations: ["aggiornamento software"] }),
  D("d3-truffa-online", "truffa online", "estafa en línea", "ˈtruffa ˈonline", "espressione", "tecnologia", "B1", 3, { it: "Attenzione alle truffe online sui voli.", es: "Cuidado con las estafas en línea de vuelos." }),

  /* ══ dinero B1 ══ */
  D("d3-bolletta", "bolletta", "recibo (servicios)", "bolˈletta", "sostantivo", "finanze", "B1", 3, { it: "Devo pagare la bolletta della luce.", es: "Debo pagar el recibo de la luz." }, { gender: "f", collocations: ["bolletta della luce", "bolletta del gas"] }),
  D("d3-mutuo", "mutuo", "hipoteca / préstamo", "ˈmuːtuo", "sostantivo", "finanze", "B1", 3, { it: "Abbiamo acceso un mutuo per la casa.", es: "Contrajimos una hipoteca para la casa." }, { gender: "m", collocations: ["mutuo casa", "accendere un mutuo"] }),
  D("d3-prestito", "prestito", "préstamo", "preˈstiːto", "sostantivo", "finanze", "B1", 3, { it: "Un prestito personale a tasso zero.", es: "Un préstamo personal a tasa cero." }, { gender: "m" }),
  D("d3-interessi", "interessi", "interés (financiero)", "inteˈrɛssi", "sostantivo", "finanze", "B1", 3, { it: "Gli interessi del mutuo sono alti.", es: "Los intereses de la hipoteca son altos." }, { gender: "m", plural: "interessi" }),
  D("d3-fattura", "fattura", "factura", "fatˈtuːra", "sostantivo", "finanze", "B1", 3, { it: "Mi fa la fattura, per favore?", es: "¿Me hace la factura, por favor?" }, { gender: "f" }),
  D("d3-investimento", "investimento", "inversión", "investiˈmento", "sostantivo", "finanze", "B1", 3, { it: "Un investimento sicuro nel mattone.", es: "Una inversión segura en el ladrillo." }, { gender: "m" }),

  /* ══ emociones / carácter B1 ══ */
  D("d3-affidabile", "affidabile", "fiable / confiable", "affidaˈbiːle", "aggettivo", "emozioni", "B1", 4, { it: "È una persona affidabile e puntuale.", es: "Es una persona fiable y puntual." }),
  D("d3-responsabile", "responsabile", "responsable", "responˈsaːbile", "aggettivo", "emozioni", "B1", 3, { it: "È responsabile del reparto marketing.", es: "Es responsable del departamento de marketing." }, { collocations: ["essere responsabile di"] }),
  D("d3-entusiasta", "entusiasta", "entusiasta", "entuziˈasta", "aggettivo", "emozioni", "B1", 3, { it: "Sono entusiasta del nuovo corso!", es: "¡Estoy entusiasmado con el nuevo curso!" }, { collocations: ["entusiasta di"] }),
  D("d3-motivato", "motivato", "motivado", "motiˈvaːto", "aggettivo", "emozioni", "B1", 3, { it: "Uno studente motivato impara in fretta.", es: "Un estudiante motivado aprende rápido." }),
  D("d3-determinato", "determinato", "decidido / determinado", "determiˈnaːto", "aggettivo", "emozioni", "B1", 3, { it: "È determinato a finire la maratona.", es: "Está decidido a terminar el maratón." }),
  D("d3-scoraggiato", "scoraggiato", "desanimado", "skorandˈdʒaːto", "aggettivo", "emozioni", "B1", 4, { it: "Non ti scoraggiare al primo errore!", es: "¡No te desanimes con el primer error!" }),
  D("d3-testardo", "testardo", "testarudo / terco", "teˈstardo", "aggettivo", "emozioni", "B1", 3, { it: "Sei testardo come un mulo!", es: "¡Eres testarudo como un mulo!" }, { syn: ["ostinato"] }),
  D("d3-impaziente", "impaziente", "impaciente", "impattsjɛnte", "aggettivo", "emozioni", "B1", 3, { it: "Sono impaziente di partire.", es: "Estoy impaciente por partir." }, { ant: ["paziente"] }),
  D("d3-paziente", "paziente", "paciente", "pattsjɛnte", "aggettivo", "emozioni", "B1", 2, { it: "L'insegnante è paziente con i principianti.", es: "El profesor es paciente con los principiantes." }, { ant: ["impaziente"] }),
  D("d3-razionale", "razionale", "racional", "rattsjoˈnaːle", "aggettivo", "astratto", "B1", 4, { it: "Una scelta razionale, non emotiva.", es: "Una elección racional, no emotiva." }, { ant: ["istintivo", "emotivo"] }),

  /* ══ locuciones y expresiones B1 ══ */
  D("d3-dare-ragione", "dare ragione", "dar la razón", "daːre raˈdʒoːne", "espressione", "comunicazione", "B1", 2, { it: "Ti do ragione: hai capito tutto.", es: "Te doy la razón: entendiste todo." }, { ant: ["dare torto"] }),
  D("d3-dare-torto", "dare torto", "quitar la razón", "daːre ˈtorto", "espressione", "comunicazione", "B1", 3, { it: "Il capo gli ha dato torto davanti a tutti.", es: "El jefe le quitó la razón delante de todos." }, { ant: ["dare ragione"] }),
  D("d3-avere-bisogno", "avere bisogno di", "necesitar / tener necesidad de", "ˈavere biˈzoɲɲo", "espressione", "astratto", "B1", 1, { it: "Ho bisogno di un consiglio.", es: "Necesito un consejo." }, { note: "avere bisogno DI = necesitar. ¡Siempre con di! ho bisogno di te." }),
  D("d3-avere-voglia", "avere voglia di", "tener ganas de", "ˈavere ˈvoʎʎa", "espressione", "emozioni", "B1", 1, { it: "Ho voglia di un gelato al cioccolato.", es: "Tengo ganas de un helado de chocolate." }),
  D("d3-cavarsela", "cavarsela", "apañárselas / arreglárselas", "kaˈvarˈsela", "espressione", "astratto", "B1", 3, { it: "Me la cavo bene con l'italiano!", es: "¡Me apaño bien con el italiano!" }, { register: "colloquiale" }),
  D("d3-andare-male", "andare male", "ir mal / salir mal", "ˈandare ˈmale", "espressione", "astratto", "B1", 2, { it: "L'esame è andato male, riprovo a settembre.", es: "El examen salió mal, reintento en septiembre." }, { ant: ["andare bene"] }),
  D("d3-fare-finta", "fare finta di", "fingir / hacer como si", "faːre ˈfinta", "espressione", "comunicazione", "B1", 3, { it: "Faccio finta di non vedere il disordine.", es: "Hago como si no viera el desorden." }),
  D("d3-roba", "roba", "cosa(s) / bártulos / asunto", "ˈroːba", "sostantivo", "astratto", "B1", 2, { it: "Imballa tutta la roba nelle scatole.", es: "Empaqueta todas las cosas en las cajas." }, { gender: "f", ff: true, register: "colloquiale", note: "⚠️ FALSO AMIGO: roba = COSAS/bártulos, no 'ropa' (= vestiti, abiti). ¡Confusión clásica!" }),
  D("d3-colla", "colla", "pegamento / cola", "ˈkɔlla", "sostantivo", "casa", "B1", 3, { it: "Attacco il poster con la colla.", es: "Pego el póster con pegamento." }, { gender: "f", ff: true, note: "⚠️ FALSO AMIGO: colla = PEGAMENTO, no 'cola' (bebida = coca; para pegar = adhesivo)." }),
  D("d3-subire", "subire", "sufrir / padecer (sin culpa)", "suˈbiːre", "verbo", "astratto", "B1", 2, { it: "La città ha subito danni pesanti.", es: "La ciudad sufrió daños graves." }, { ff: true, note: "⚠️ FALSO AMIGO: subire = SUFRIR/PADOCER, no 'subir' (= salire). El partido subió = la squadra è salita." }),
  D("d3-pena", "pena", "pena / lástima / condena", "ˈpeːna", "sostantivo", "istituzioni", "B1", 3, { it: "Che pena! La pena di morte è abolita in Italia.", es: "¡Qué pena! La pena de muerte está abolida en Italia." }, { gender: "f", collocations: ["pena di morte", "che pena!"] }),
  D("d3-magari", "magari", "ojalá / quizá / cómo no", "ˈmaɡari", "avverbio", "connettivi", "B1", 2, { it: "Magari venissi anch'io in Italia!", es: "¡Ojalá viniera yo también a Italia!" }, { register: "colloquiale", note: "magari = ojalá (deseo), quizá (posibilidad) o 'claro que sí' (respuesta entusiasta)." }),
];
