import { D } from "./entry";

/* ── Pack A1 · inventario fundamental MCER (parte 1: función, números, verbos) ── */

export const PACK_A1: import("../types").VocabWord[] = [
  /* ══ articolo ══ */
  D("d1-art-il", "il", "el (artículo determinado)", "il", "articolo", "astratto", "A1", 1, { it: "Il libro è sul tavolo.", es: "El libro está sobre la mesa." }, { alt: ["lo", "la", "i", "gli", "le"], note: "Il→lo ante s+consonante, z, ps, gn, y (lo studente, lo zaino). Singular→plural: il→i, lo→gli, la→le." }),
  D("d1-art-un", "un", "un / una (artículo indeterminado)", "un", "articolo", "astratto", "A1", 1, { it: "Vorrei un caffè e una brioche.", es: "Querría un café y un bollo." }, { alt: ["uno", "una", "un'", "uno"], note: "un→uno ante s+cons., z, ps, gn (uno zaino, uno studente). Fem.: una / un' ante vocal (un'amica)." }),

  /* ══ pronomi ══ */
  D("d1-io", "io", "yo", "ˈiːo", "pronome", "astratto", "A1", 1, { it: "Io abito a Roma.", es: "Yo vivo en Roma." }, { note: "El sujeto suele omitirse: la terminación verbal lo identifica (Abito a Roma)." }),
  D("d1-tu", "tu", "tú", "tu", "pronome", "astratto", "A1", 1, { it: "Tu come ti chiami?", es: "¿Tú cómo te llamas?" }),
  D("d1-lui", "lui", "él", "ˈluːi", "pronome", "astratto", "A1", 1, { it: "Lui è mio fratello.", es: "Él es mi hermano." }),
  D("d1-lei", "lei", "ella / usted (formal)", "lɛi", "pronome", "astratto", "A1", 1, { it: "Lei parla spagnolo?", es: "¿Usted habla español?" }, { note: "Lei con 3ª persona = usted formal (courtesy form), como 'usted' en español." }),
  D("d1-noi", "noi", "nosotros", "nɔi", "pronome", "astratto", "A1", 1, { it: "Noi siamo pronti.", es: "Nosotros estamos listos." }),
  D("d1-voi", "voi", "vosotros / ustedes", "vɔi", "pronome", "astratto", "A1", 1, { it: "Voi da dove venite?", es: "¿Vosotros de dónde venís?" }),
  D("d1-loro", "loro", "ellos / ellas", "ˈlɔːro", "pronome", "astratto", "A1", 1, { it: "Loro sono spagnoli.", es: "Ellos son españoles." }),
  D("d1-questo", "questo", "este / esto", "ˈkwesto", "pronome", "astratto", "A1", 1, { it: "Questo è il mio quaderno.", es: "Este es mi cuaderno." }, { ant: ["quello"] }),
  D("d1-quello", "quello", "ese / aquel", "ˈkwɛllo", "pronome", "astratto", "A1", 1, { it: "Quello è il tuo zaino?", es: "¿Ese es tu mochila?" }, { ant: ["questo"] }),
  D("d1-tutto", "tutto", "todo", "ˈtutto", "pronome", "astratto", "A1", 1, { it: "Ho mangiato tutto.", es: "He comido todo." }, { note: "Concordancia total: tutto/tutta/tutti/tutte (tutte le ragazze). En español 'todo' no concuerda tan ricamente." }),
  D("d1-niente", "niente", "nada", "ˈnjɛnte", "pronome", "astratto", "A1", 2, { it: "Non ho niente da dire.", es: "No tengo nada que decir." }, { note: "Doble negación permitida: non…niente = 'no…nada'. Igual que en español." }),
  D("d1-qualcosa", "qualcosa", "algo / alguna cosa", "ˈkwalʃɔlɔa", "pronome", "astratto", "A1", 2, { it: "Vuoi qualcosa da bere?", es: "¿Quieres algo de beber?" }),

  /* ══ interrogativi ══ */
  D("d1-chi", "chi", "quién", "ki", "pronome", "astratto", "A1", 1, { it: "Chi è quella signora?", es: "¿Quién es esa señora?" }),
  D("d1-cosa", "cosa", "qué (che cosa)", "ˈkɔsa", "pronome", "astratto", "A1", 1, { it: "Cosa fai stasera?", es: "¿Qué haces esta noche?" }, { alt: ["che cosa"], note: "cosa / che cosa / che — tres formas del mismo interrogativo; 'cosa' es la más coloquial." }),
  D("d1-dove", "dove", "dónde", "ˈdɔːve", "avverbio", "astratto", "A1", 1, { it: "Dove abiti?", es: "¿Dónde vives?" }),
  D("d1-quando", "quando", "cuándo", "ˈkwndo", "avverbio", "astratto", "A1", 1, { it: "Quando arriva il treno?", es: "¿Cuándo llega el tren?" }),
  D("d1-perche", "perché", "por qué / porque", "perˈke", "congiunzione", "connettivi", "A1", 1, { it: "Perché ridi? — Rido perché sono felice.", es: "¿Por qué ríes? — Río porque estoy feliz." }, { note: "Misma forma para pregunta y respuesta, como en español. También 'perché' + congiuntivo = 'para que'." }),
  D("d1-come", "come", "cómo", "ˈkɔːme", "avverbio", "astratto", "A1", 1, { it: "Come stai? — Bene, grazie!", es: "¿Cómo estás? — ¡Bien, gracias!" }),
  D("d1-quanto", "quanto", "cuánto", "ˈkwsnto", "pronome", "astratto", "A1", 1, { it: "Quanto costa il biglietto?", es: "¿Cuánto cuesta el billete?" }),
  D("d1-quale", "quale", "cuál", "ˈkwale", "pronome", "astratto", "A1", 2, { it: "Quale preferisci, il tè o il caffè?", es: "¿Cuál prefieres, el té o el café?" }, { alt: ["quali"] }),

  /* ══ preposizioni ══ */
  D("d1-di", "di", "de", "di", "preposizione", "astratto", "A1", 1, { it: "Il libro di Luca è nuovo.", es: "El libro de Luca es nuevo." }, { note: "di + artículo → del, dello, della, dei, degli, delle (como 'del' español)." }),
  D("d1-a", "a", "a / en", "a", "preposizione", "astratto", "A1", 1, { it: "Vado a Roma a piedi.", es: "Voy a Roma a pie." }, { note: "a + artículo → al, alla, ai, alle. Ciudad sin artículo: vado a Roma (vs. vado in Italia)." }),
  D("d1-da", "da", "de / desde / en casa de", "da", "preposizione", "astratto", "A1", 1, { it: "Vengo da Madrid. Sono dal medico.", es: "Vengo de Madrid. Estoy en el médico." }, { note: "da expresa procedencia y también 'en casa de': dal medico, da Maria (como 'de/en' francés)." }),
  D("d1-in", "in", "en", "in", "preposizione", "astratto", "A1", 1, { it: "Abito in Italia, in via Roma.", es: "Vivo en Italia, en la calle Roma." }, { note: "in + país, ciudad con artículo (in Italia, a Roma), medio de transporte (in treno, in macchina)." }),
  D("d1-con", "con", "con", "kon", "preposizione", "astratto", "A1", 1, { it: "Ceno con gli amici.", es: "Ceno con los amigos." }),
  D("d1-su", "su", "sobre", "su", "preposizione", "astratto", "A1", 1, { it: "Il gatto è sul divano.", es: "El gato está sobre el sofá." }, { note: "su + il → sul (sobre el). 'Sopra' = encima de." }),
  D("d1-per", "per", "para / por", "per", "preposizione", "astratto", "A1", 1, { it: "Questo regalo è per te.", es: "Este regalo es para ti." }),
  D("d1-tra", "tra / fra", "entre / dentro de (tiempo)", "tra", "preposizione", "astratto", "A1", 1, { it: "Tra dieci minuti arriva.", es: "En diez minutos llega." }, { note: "tra y fra son intercambiables. Para tiempo futuro = 'en': tra un anno = en un año." }),
  D("d1-senza", "senza", "sin", "ˈsɛnttso", "preposizione", "astratto", "A1", 1, { it: "Caffè senza zucchero, per favore.", es: "Café sin azúcar, por favor." }),

  /* ══ congiunzioni ══ */
  D("d1-e", "e", "y", "e", "congiunzione", "connettivi", "A1", 1, { it: "Pane e vino, per favore.", es: "Pan y vino, por favor." }, { note: "Ante vocal: ed (ed io). Igual que 'y/e' en español." }),
  D("d1-o", "o", "o", "o", "congiunzione", "connettivi", "A1", 1, { it: "Tè o caffè?", es: "¿Té o café?" }, { note: "Ante vocal: od (od io)." }),
  D("d1-ma", "ma", "pero", "ma", "congiunzione", "connettivi", "A1", 1, { it: "Vorrei venire, ma non posso.", es: "Querría venir, pero no puedo." }),
  D("d1-se", "se", "si (condicional)", "se", "congiunzione", "connettivi", "A1", 1, { it: "Se piove, resto a casa.", es: "Si llueve, me quedo en casa." }),
  D("d1-che", "che", "que", "ke", "congiunzione", "connettivi", "A1", 1, { it: "Credo che abbia ragione.", es: "Creo que tiene razón." }, { note: "che jamás se omite (a diferencia del 'that' inglés). Tras verbos de opinión + congiuntivo." }),
  D("d1-anche", "anche", "también", "ˈanke", "avverbio", "connettivi", "A1", 1, { it: "Anche io amo l'Italia.", es: "Yo también amo Italia." }, { note: "'Yo también' = anche io / anch'io (ante vocal). No confundir con 'todavía' = ancora." }),
  D("d1-non", "non", "no", "non", "avverbio", "astratto", "A1", 1, { it: "Non capisco questa parola.", es: "No entiendo esta palabra." }),

  /* ══ numerali ══ */
  D("d1-uno", "uno", "uno", "ˈuːno", "numerale", "tempo", "A1", 1, { it: "Ho uno zaino blu.", es: "Tengo una mochila azul." }, { alt: ["una", "un"] }),
  D("d1-due", "due", "dos", "ˈduːe", "numerale", "tempo", "A1", 1, { it: "Vorrei due biglietti.", es: "Querría dos billetes." }),
  D("d1-tre", "tre", "tres", "tre", "numerale", "tempo", "A1", 1, { it: "Siamo in tre.", es: "Somos tres." }),
  D("d1-quattro", "quattro", "cuatro", "ˈkwattro", "numerale", "tempo", "A1", 1, { it: "La lezione dura quattro ore.", es: "La clase dura cuatro horas." }),
  D("d1-cinque", "cinque", "cinco", "ˈtʃinkwe", "numerale", "tempo", "A1", 1, { it: "Ci vediamo alle cinque.", es: "Nos vemos a las cinco." }),
  D("d1-dieci", "dieci", "diez", "ˈdjɛːtʃi", "numerale", "tempo", "A1", 1, { it: "Un caffè costa dieci euro.", es: "Un café cuesta diez euros." }),
  D("d1-venti", "venti", "veinte", "ˈvɛnti", "numerale", "tempo", "A1", 1, { it: "Ho venti anni.", es: "Tengo veinte años." }, { note: "Años con 'avere' (ho vent'anni), no con 'ser/tener' como en español: tengo 20 años." }),
  D("d1-cento", "cento", "cien / cien(to)", "ˈtʃɛnto", "numerale", "tempo", "A1", 1, { it: "Costa cento euro.", es: "Cuesta cien euros." }, { note: "cento es invariable: duecento, trecento… (vs. español doscientos/-as)." }),
  D("d1-mille", "mille", "mil", "ˈmille", "numerale", "tempo", "A1", 1, { it: "Mille grazie!", es: "¡Mil gracias!" }, { note: "Plural irónico: mille → mila (duemila). Como 'mil/miles'." }),
  D("d1-primo", "primo", "primero", "ˈprimo", "aggettivo", "tempo", "A1", 1, { it: "Abito al primo piano.", es: "Vivo en el primer piso." }, { note: "Ordinales: primo, secondo, terzo, quarto… décimo = decimo. Concuerdan: la prima volta." }),
  D("d1-secondo", "secondo", "segundo / según", "seˈkondo", "aggettivo", "tempo", "A1", 1, { it: "Secondo me, hai ragione.", es: "Según mí, tienes razón." }, { note: "'Según yo' = secondo me — expresión clave para opinar (B1 opinion)." }),
  D("d1-mezzo", "mezzo", "medio / media", "ˈmɛddzo", "aggettivo", "tempo", "A1", 2, { it: "Un chilo e mezzo, per favore. Sono le tre e mezza.", es: "Un kilo y medio, por favor. Son las tres y media." }, { note: "mezzo/mezza concuerda; en la hora: le tre e mezza = las tres y media." }),

  /* ══ verbi nucleari ══ */
  D("d1-essere", "essere", "ser / estar", "ˈɛssere", "verbo", "astratto", "A1", 1, { it: "Sono stanco, ma sono felice.", es: "Estoy cansado, pero soy feliz." }, { note: "Como en español, distingue 'ser' (identidad) y 'stare' (estado). Sono + adjetivo invariable en género, concuerda en número." }),
  D("d1-avere", "avere", "tener / haber", "aˈvɛvere", "verbo", "astratto", "A1", 1, { it: "Ho vent'anni e ho fame.", es: "Tengo veinte años y tengo hambre." }, { note: "Avoir-sensaciones: ho fame/sete/freddo/caldo/sonno/paura = tengo hambre/sed/frío/calor/sueño/miedo." }),
  D("d1-fare", "fare", "hacer", "ˈfaːre", "verbo", "astratto", "A1", 1, { it: "Che fai? Faccio colazione alle otto.", es: "¿Qué haces? Desayuno a las ocho." }, { collocations: ["fare colazione", "fare la spesa", "fare una domanda", "fare una passeggiata", "fare festa"], note: "Fare + sustantivo forma innumerables locuciones (fare una domanda = hacer una pregunta)." }),
  D("d1-andare", "andare", "ir", "ˈandare", "verbo", "astratto", "A1", 1, { it: "Vado a scuola in bicicletta.", es: "Voy a la escuela en bicicleta." }, { note: "Verbo irregular con sentido de movimiento. andare a + infinitivo = ir a hacer (vado a dormire)." }),
  D("d1-venire", "venire", "venir", "veˈniːre", "verbo", "astratto", "A1", 1, { it: "Vieni anche tu alla festa?", es: "¿Vienes tú también a la fiesta?" }),
  D("d1-dire", "dire", "decir", "ˈdiːre", "verbo", "astratto", "A1", 1, { it: "Come si dice 'libro' in spagnolo?", es: "¿Cómo se dice 'libro' en español?" }, { note: "come si dice…? = ¿cómo se dice…? Fórmula clave para el aula." }),
  D("d1-parlare", "parlare", "hablar", "parˈlaːre", "verbo", "astratto", "A1", 1, { it: "Parlo italiano e un po' di spagnolo.", es: "Hablo italiano y un poco de español." }),
  D("d1-mangiare", "mangiare", "comer", "manˈdʒaːre", "verbo", "alimentazione", "A1", 1, { it: "Mangiamo una pizza margherita.", es: "Comemos una pizza margarita." }),
  D("d1-bere", "bere", "beber", "ˈbɛːre", "verbo", "alimentazione", "A1", 1, { it: "Bevo un bicchiere d'acqua.", es: "Bebo un vaso de agua." }, { alt: ["bevo", "bevi"], note: "bevo, bevi, beve… forma irregular breve en presente." }),
  D("d1-dormire", "dormire", "dormir", "dorˈmiːre", "verbo", "casa", "A1", 1, { it: "Dormo otto ore ogni notte.", es: "Duermo ocho horas cada noche." }),
  D("d1-vivere", "vivere", "vivir", "ˈviːvere", "verbo", "astratto", "A1", 1, { it: "Vivo a Firenze da due anni.", es: "Vivo en Florencia desde hace dos años." }, { note: "vivere a + ciudad (no 'in'). Presente: vivo, vivi, vive, viviamo, vivete, vivono." }),
  D("d1-dare", "dare", "dar", "ˈdaːre", "verbo", "astratto", "A1", 1, { it: "Mi dai una mano, per favore?", es: "¿Me das una mano, por favor?" }, { collocations: ["dare una mano", "dare un bacio", "dare la mano"] }),
  D("d1-prendere", "prendere", "tomar / coger / agarrar", "ˈprɛndere", "verbo", "astratto", "A1", 1, { it: "Prendo il treno delle nove.", es: "Tomo el tren de las nueve." }, { note: "prendere = tomar/coger. 'Cogere' en italiano: prendere también sirve (prendo l'autobus)." }),
  D("d1-mettere", "mettere", "poner", "ˈmɛttere", "verbo", "astratto", "A1", 1, { it: "Metto il libro nello zaino.", es: "Pongo el libro en la mochila." }),
  D("d1-potere", "potere", "poder", "pɔˈtɛːre", "verbo", "astratto", "A1", 1, { it: "Puoi aiutarmi, per favore?", es: "¿Puedes ayudarme, por favor?" }, { note: "Modal + infinitivo sin preposición: posso venire (puedo venir). No 'di/pa' como el 'de/a' español." }),
  D("d1-volere", "volere", "querer", "vɔˈlɛːre", "verbo", "astratto", "A1", 1, { it: "Voglio imparare l'italiano.", es: "Quiero aprender italiano." }),
  D("d1-dovere", "dovere", "deber / tener que", "dɔˈvɛːre", "verbo", "astratto", "A1", 1, { it: "Devo studiare per l'esame.", es: "Tengo que estudiar para el examen." }),
  D("d1-sapere", "sapere", "saber", "saˈpɛːre", "verbo", "astratto", "A1", 1, { it: "So nuotare e so parlare inglese.", es: "Sé nadar y sé hablar inglés." }, { note: "Non si dice 'no can swim' — savoir = saber hacer algo aprendido: so nuotare." }),
  D("d1-conoscere", "conoscere", "conocer", "konoʃˈʃɛːre", "verbo", "astratto", "A1", 1, { it: "Conosci Roma? Sì, conosco bene Roma.", es: "¿Conoces Roma? Sí, conozco bien Roma." }, { note: "conoscere (conocer personas/lugares) ≠ sapere (saber información): distinción igual que español." }),
  D("d1-stare", "stare", "estar / quedarse", "ˈstaːre", "verbo", "astratto", "A1", 1, { it: "Come stai? Sto bene, grazie.", es: "¿Cómo estás? Estoy bien, gracias." }, { collocations: ["stare bene", "stare male", "stare a casa"], note: "stare bene/male = estar bien/mal. stare + gerundio = estar -ando: sto mangiando." }),
  D("d1-uscire", "uscire", "salir", "uˈʃiːre", "verbo", "astratto", "A1", 1, { it: "Esco con gli amici stasera.", es: "Salgo con los amigos esta noche." }, { ant: ["entrare", "rientrare"] }),
  D("d1-tornare", "tornare", "volver / regresar", "torˈnaːre", "verbo", "astratto", "A1", 1, { it: "Torno a casa alle sei.", es: "Vuelvo a casa a las seis." }, { note: "tornare a + infinitivo = volver a hacer: torno a provare." }),
  D("d1-chiamarsi", "chiamarsi", "llamarse", "kjaˈmarsːi", "verbo", "astratto", "A1", 1, { it: "Come ti chiami? Mi chiamo Ana.", es: "¿Cómo te llamas? Me llamo Ana." }),
  D("d1-lavorare", "lavorare", "trabajar", "lavoˈraːre", "verbo", "lavoro", "A1", 1, { it: "Lavoro in un ufficio al centro.", es: "Trabajo en una oficina en el centro." }),
  D("d1-studiare", "studiare", "estudiar", "stuˈdjaːre", "verbo", "studi", "A1", 1, { it: "Studio italiano da sei mesi.", es: "Estudio italiano desde hace seis meses." }),
  D("d1-scrivere", "scrivere", "escribir", "ˈskriːvere", "verbo", "studi", "A1", 1, { it: "Scrivo una lettera a mia nonna.", es: "Escribo una carta a mi abuela." }),
  D("d1-leggere", "leggere", "leer", "ˈlɛddʒere", "verbo", "studi", "A1", 1, { it: "Leggo un libro di Gramsci.", es: "Leo un libro de Gramsci." }),
  D("d1-aprire", "aprire", "abrir", "aˈpriːre", "verbo", "casa", "A1", 1, { it: "Puoi aprire la finestra?", es: "¿Puedes abrir la ventana?" }, { ant: ["chiudere"] }),
  D("d1-chiudere", "chiudere", "cerrar", "ˈkjuːdere", "verbo", "casa", "A1", 1, { it: "Chiudo la porta a chiave.", es: "Cierro la puerta con llave." }, { ant: ["aprire"] }),
  D("d1-aiutare", "aiutare", "ayudar", "aiuˈtaːre", "verbo", "astratto", "A1", 1, { it: "Ti aiuto volentieri!", es: "¡Te ayudo con gusto!" }),
  D("d1-aspettare", "aspettare", "esperar / esperar a alguien", "aspetˈtaːre", "verbo", "astratto", "A1", 1, { it: "Ti aspetto alla stazione.", es: "Te espero en la estación." }),
  D("d1-cercare", "cercare", "buscar", "tʃerˈkaːre", "verbo", "astratto", "A1", 1, { it: "Cerco un albergo economico.", es: "Busco un hotel económico." }, { note: "cercare = buscar (cosa). 'Buscar a alguien' para personas: cerco Maria." }),
  D("d1-trovare", "trovare", "encontrar", "troˈvaːre", "verbo", "astratto", "A1", 1, { it: "Non trovo le mie chiavi!", es: "¡No encuentro mis llaves!" }, { ant: ["perdere"] }),
  D("d1-chiedere", "chiedere", "pedir / preguntar", "ˈkjɛːdere", "verbo", "astratto", "A1", 1, { it: "Chiedo un'informazione, scusi.", es: "Pido una información, disculpe." }, { note: "chiedere = pedir algo a alguien (chiedo un caffè) / preguntar (chiedo come si chiama). 'Preguntar' también = domandare." }),
  D("d1-rispondere", "rispondere", "responder", "riˈspɔndere", "verbo", "astratto", "A1", 1, { it: "Rispondo all'email subito.", es: "Respondo al correo de inmediato." }, { ant: ["chiedere", "domandare"] }),
  D("d1-capire", "capire", "entender / comprender", "kaˈpiːre", "verbo", "astratto", "A1", 1, { it: "Non capisco, può ripetere?", es: "No entiendo, ¿puede repetir?" }, { note: "Verbo -isc-: capisco, capisci, capisce… Fórmula clave: Non capisco, può ripetere per favore?" }),
  D("d1-finire", "finire", "terminar / acabar", "fiˈniːre", "verbo", "astratto", "A1", 1, { it: "La lezione finisce alle tredici.", es: "La clase termina a la una." }, { ant: ["cominciare", "iniziare"] }),
  D("d1-cominciare", "cominciare", "empezar / comenzar", "kombinˈtʃaːre", "verbo", "astratto", "A1", 1, { it: "Comincio a studiare italiano.", es: "Empiezo a estudiar italiano." }, { note: "cominciare a + infinitivo = empezar a hacer. También iniziare (más formal)." }),
  D("d1-ricordare", "ricordare", "recordar", "riˈkɔrdare", "verbo", "astratto", "A1", 1, { it: "Ricordo il tuo compleanno!", es: "¡Recuerdo tu cumpleaños!" }, { note: "ricordare qualcosa ≠ ricordarsi di qualcosa — ambas significan recordar." }),
  D("d1-dimenticare", "dimenticare", "olvidar", "dimentiˈkaːre", "verbo", "astratto", "A1", 2, { it: "Ho dimenticato il portafoglio!", es: "¡He olvidado la cartera!" }, { ant: ["ricordare"], note: "'Se me olvidó' = mi sono dimenticato (o ho dimenticato)." }),
  D("d1-perdere", "perdere", "perder", "ˈpɛrdere", "verbo", "astratto", "A1", 1, { it: "Ho perso il treno delle otto!", es: "¡He perdido el tren de las ocho!" }, { ant: ["trovare", "vincere"], collocations: ["perdere il treno", "perdere tempo", "perdersi"] }),
  D("d1-portare", "portare", "llevar / traer", "porˈtaːre", "verbo", "astratto", "A1", 1, { it: "Porto il vino alla festa.", es: "Llevo el vino a la fiesta." }),
  D("d1-arrivare", "arrivare", "llegar", "arriˈvaːre", "verbo", "astratto", "A1", 1, { it: "Arrivo in cinque minuti.", es: "Llego en cinco minutos." }, { ant: ["partire"] }),
  D("d1-partire", "partire", "salir (viajar) / partir", "parˈtiːre", "verbo", "astratto", "A1", 1, { it: "Il treno parte alle nove.", es: "El tren sale a las nueve." }, { ant: ["arrivare"], note: "'El tren sale' = il treno parte. Salida (indicación) = partenza." }),
  D("d1-restare", "restare", "quedarse", "reˈstaːre", "verbo", "astratto", "A1", 2, { it: "Resto a casa oggi.", es: "Me quedo en casa hoy." }, { syn: ["rimanere"] }),
  D("d1-piacere", "piacere", "gustar / agradar", "pjaˈtʃeːre", "verbo", "astratto", "A1", 1, { it: "Mi piace la pizza. Mi piacciono i film italiani.", es: "Me gusta la pizza. Me gustan las películas italianas." }, { note: "Construcción invertida como 'gustar': MI PIACE la cosa (sing.), MI PIACCIONO las cosas (pl.). Mi piace mangiare = me gusta comer." }),
  D("d1-servire", "servire", "servir / hacer falta", "serˈviːre", "verbo", "astratto", "A1", 2, { it: "Mi serve un aiuto. Ti serve il passaporto?", es: "Necesito (me sirve) una ayuda. ¿Necesitas el pasaporte?" }, { note: "a me serve… = 'yo necesito' (como 'gustar'): mi serve una penna = necesito un bolígrafo." }),
  D("d1-seguire", "seguire", "seguir", "seˈɡuːire", "verbo", "astratto", "A1", 2, { it: "Seguo un corso d'italiano online.", es: "Sigo un curso de italiano en línea." }),

  /* ══ aggettivi A1 ══ */
  D("d1-buono", "buono", "bueno", "ˈbwɔːno", "aggettivo", "alimentazione", "A1", 1, { it: "Questo dolce è buono!", es: "¡Este postre está bueno!" }, { ant: ["cattivo"], note: "Posición especial: buono → buon ante consonante (un buon amico). 'Essere buono' = ser bueno; 'essere buono!' para comida." }),
  D("d1-cattivo", "cattivo", "malo", "katˈtiːvo", "aggettivo", "alimentazione", "A1", 2, { it: "Il caffè della macchinetta è cattivo.", es: "El café de la máquina es malo." }, { ant: ["buono"] }),
  D("d1-grande", "grande", "grande / grande (edad)", "ˈɡrande", "aggettivo", "astratto", "A1", 1, { it: "Una grande città come Milano.", es: "Una gran ciudad como Milán." }, { ant: ["piccolo"], note: "Ante sustantivo → gran (un gran amico). 'Essere grande' = ser mayor: mia sorella è grande." }),
  D("d1-piccolo", "piccolo", "pequeño", "ˈpikkolo", "aggettivo", "astratto", "A1", 1, { it: "Un caffè piccolo, per favore.", es: "Un café pequeño, por favor." }, { ant: ["grande"] }),
  D("d1-nuovo", "nuovo", "nuevo", "ˈnwɔːvo", "aggettivo", "astratto", "A1", 1, { it: "Ho un telefono nuovo.", es: "Tengo un teléfono nuevo." }, { ant: ["vecchio"] }),
  D("d1-vecchio", "vecchio", "viejo", "ˈvɛkkjo", "aggettivo", "astratto", "A1", 1, { it: "Il centro storico è vecchio di mille anni.", es: "El centro histórico tiene mil años de antigüedad." }, { ant: ["nuovo"], note: "'Tener X años (antigüedad)' = essere vecchio di X anni." }),
  D("d1-alto", "alto", "alto", "ˈalto", "aggettivo", "corpo", "A1", 1, { it: "Mio fratello è alto un metro e novanta.", es: "Mi hermano mide un metro noventa." }, { ant: ["basso"], note: "'Mide 1,90' = è alto 1,90. También 'alto' = ruidoso: la musica è alta." }),
  D("d1-basso", "basso", "bajo", "ˈbasso", "aggettivo", "corpo", "A1", 1, { it: "Parla a voce bassa.", es: "Habla en voz baja." }, { ant: ["alto"] }),
  D("d1-lungo", "lungo", "largo / largo (tiempo)", "ˈluŋɡo", "aggettivo", "astratto", "A1", 1, { it: "Un film lungo tre ore.", es: "Una película de tres horas de duración." }, { ant: ["corto"], note: "'Largo' espacial y temporal = lungo: un lungo viaggio. 'Corto' = corto." }),
  D("d1-corto", "corto", "corto", "ˈkorto", "aggettivo", "astratto", "A1", 1, { it: "Un vestito corto ed elegante.", es: "Un vestido corto y elegante." }, { ant: ["lungo"] }),
  D("d1-facile", "facile", "fácil", "ˈfaːtʃile", "aggettivo", "studi", "A1", 1, { it: "L'italiano è facile per gli spagnoli.", es: "El italiano es fácil para los españoles." }, { ant: ["difficile"], note: "facile a capirsi = fácil de entender: facil + a + infinitivo." }),
  D("d1-difficile", "difficile", "difícil", "diffiˈtʃile", "aggettivo", "studi", "A1", 1, { it: "Il congiuntivo è difficile.", es: "El subjuntivo es difícil." }, { ant: ["facile"] }),
  D("d1-bello", "bello", "bonito / hermoso", "ˈbɛllo", "aggettivo", "astratto", "A1", 1, { it: "Che bello! Roma è bellissima!", es: "¡Qué bonito! ¡Roma es bellísima!" }, { note: "Formas especiales: bel→bell→bello→bei→begli→belle (bella giornata, begli occhi). ¡Che bello! = ¡Qué bonito!" }),
  D("d1-brutto", "brutto", "feo", "ˈbrutto", "aggettivo", "astratto", "A1", 1, { it: "Che brutto tempo oggi!", es: "¡Qué feo tiempo hoy!" }, { ant: ["bello"], note: "brutto tempo = mal tiempo. 'Hace mal tiempo' = che brutto tempo / il tempo è brutto." }),
  D("d1-felice", "felice", "feliz", "feˈliːtʃe", "aggettivo", "emozioni", "A1", 1, { it: "Sono felice di vederti!", es: "¡Soy feliz de verte!" }, { ant: ["triste", "infelice"], note: "felice di + infinitivo = feliz de hacer algo." }),
  D("d1-triste", "triste", "triste", "ˈtriste", "aggettivo", "emozioni", "A1", 1, { it: "Questo film mi rende triste.", es: "Esta película me pone triste." }, { ant: ["felice", "allegro"] }),
  D("d1-stanco", "stanco", "cansado", "ˈstanko", "aggettivo", "emozioni", "A1", 1, { it: "Sono stanco morto dopo il lavoro.", es: "Estoy muerto de cansancio después del trabajo." }),
  D("d1-occupato", "occupato", "ocupado", "okkuˈpaːto", "aggettivo", "lavoro", "A1", 1, { it: "Scusa, sono occupato fino alle sei.", es: "Disculpa, estoy ocupado hasta las seis." }, { ant: ["libero"] }),
  D("d1-libero", "libero", "libre / desocupado", "ˈliːbero", "aggettivo", "astratto", "A1", 1, { it: "Sabato sei libero per un caffè?", es: "¿El sábado estás libre para un café?" }, { ant: ["occupato"] }),
  D("d1-pieno", "pieno", "lleno", "ˈpjɛːno", "aggettivo", "astratto", "A1", 1, { it: "Il ristorante è pieno zeppo.", es: "El restaurante está llenísimo." }, { ant: ["vuoto"], collocations: ["pieno zeppo", "un piatto pieno"] }),
  D("d1-vuoto", "vuoto", "vacío", "ˈvwɔːto", "aggettivo", "astratto", "A1", 1, { it: "Il frigorifero è vuoto!", es: "¡El refrigerador está vacío!" }, { ant: ["pieno"] }),
  D("d1-forte", "forte", "fuerte", "ˈfɔrte", "aggettivo", "astratto", "A1", 1, { it: "Un caffè forte, per favore!", es: "¡Un café fuerte, por favor!" }, { ant: ["debole"] }),
  D("d1-debole", "debole", "débil", "ˈdɛːbole", "aggettivo", "astratto", "A1", 2, { it: "Mi italiano è ancora debole.", es: "Mi italiano es todavía débil." }, { ant: ["forte"] }),
  D("d1-veloce", "veloce", "rápido", "veˈlɔːtʃe", "aggettivo", "astratto", "A1", 1, { it: "Il treno veloce arriva in un'ora.", es: "El tren rápido llega en una hora." }, { ant: ["lento"], syn: ["rapido"] }),
  D("d1-lento", "lento", "lento", "ˈlento", "aggettivo", "astratto", "A1", 1, { it: "Parla lentamente, per favore.", es: "Hable lentamente, por favor." }, { ant: ["veloce"] }),
  D("d1-pronto", "pronto", "listo / listo (teléfono)", "ˈpronto", "aggettivo", "astratto", "A1", 1, { it: "Pronto? Chi parla? Sono pronto!", es: "¿Aló? ¿Quién habla? ¡Estoy listo!" }, { note: "¡Pronto! al contestar el teléfono = ¿Aló? / ¿Sí? 'Estar listo' = essere pronto." }),
  D("d1-caro", "caro", "caro / querido", "ˈkaːro", "aggettivo", "compras", "A1", 1, { it: "Che caro! Ma cara Anna, come stai?", es: "¡Qué caro! Pero querida Ana, ¿cómo estás?" }, { ant: ["economico"], note: "caro = caro (precio) y querido (carta: cara Anna). ant. 'a buon mercato' o 'economico'." }),
  D("d1-economico", "economico", "económico / barato", "ekoˈnɔːmiko", "aggettivo", "compras", "A1", 1, { it: "Cerco un albergo economico.", es: "Busco un hotel barato." }, { ant: ["caro"], syn: ["a buon mercato"] }),
  D("d1-pulito", "pulito", "limpio", "puˈliːto", "aggettivo", "casa", "A1", 1, { it: "La camera è pulita e ordinata.", es: "La habitación está limpia y ordenada." }, { ant: ["sporco"] }),
  D("d1-sporco", "sporco", "sucio", "ˈsporko", "aggettivo", "casa", "A1", 1, { it: "Non toccare, hai le mani sporche!", es: "¡No toques, tienes las manos sucias!" }, { ant: ["pulito"] }),
  D("d1-giusto", "giusto", "correcto / justo", "ˈdʒusto", "aggettivo", "astratto", "A1", 1, { it: "Hai giusto! Il conto è giusto.", es: "¡Tienes razón! La cuenta es correcta." }, { ant: ["sbagliato"] }),
  D("d1-sbagliato", "sbagliato", "equivocado / errado", "zbaˈʎʎato", "aggettivo", "astratto", "A1", 1, { it: "Numero sbagliato, mi scusi!", es: "Número equivocado, ¡disculpe!" }, { ant: ["giusto"] }),
  D("d1-importante", "importante", "importante", "importˈtante", "aggettivo", "astratto", "A1", 1, { it: "È importante praticare ogni giorno.", es: "Es importante practicar cada día." }, { ant: ["senza importanza"] }),
  D("d1-vero", "vero", "verdadero / cierto", "ˈveːro", "aggettivo", "astratto", "A1", 1, { it: "È vero che vai in Italia?", es: "¿Es verdad que vas a Italia?" }, { ant: ["falso"], note: "¡Davvero! = ¡de verdad! / ¡en serio!" }),
  D("d1-falso", "falso", "falso", "ˈfalso", "aggettivo", "astratto", "A1", 2, { it: "Questa notizia è falsa.", es: "Esta noticia es falsa." }, { ant: ["vero"] }),
  D("d1-stesso", "stesso", "mismo", "ˈstɛsso", "aggettivo", "astratto", "A1", 1, { it: "Abitiamo nello stesso palazzo.", es: "Vivimos en el mismo edificio." }, { note: "'El mismo' = lo stesso / il medesimo (formal). nello stesso = en el mismo." }),
  D("d1-altro", "altro", "otro", "ˈaltro", "aggettivo", "astratto", "A1", 1, { it: "Vuoi dell'altro caffè? Un altro giorno, magari.", es: "¿Quieres más café? Otro día, quizá." }),

  /* ══ tiempo ══ */
  D("d1-minuto", "minuto", "minuto", "miˈnuːto", "sostantivo", "tempo", "A1", 1, { it: "Arrivo tra cinque minuti!", es: "¡Llego en cinco minutos!" }, { gender: "m", plural: "minuti" }),
  D("d1-ora", "ora", "hora / ahora", "ˈoːra", "sostantivo", "tempo", "A1", 1, { it: "Che ora è? Sono le tre. A che ora arrivi?", es: "¿Qué hora es? Son las tres. ¿A qué hora llegas?" }, { gender: "f", plural: "ore", note: "Che ora è? / A che ora…? — preguntas de hora esenciales A1. 'ora' también = ahora (ora vado)." }),
  D("d1-giorno", "giorno", "día", "ˈdʒorno", "sostantivo", "tempo", "A1", 1, { it: "Buona giornata! Il giorno più bello della mia vita.", es: "¡Buen día! El día más bonito de mi vida." }, { gender: "m", plural: "giorni", collocations: ["buongiorno", "buona giornata", "tutti i giorni"] }),
  D("d1-settimana", "settimana", "semana", "settiˈmaːna", "sostantivo", "tempo", "A1", 1, { it: "Ci vediamo la prossima settimana.", es: "Nos vemos la próxima semana." }, { gender: "f", plural: "settimane" }),
  D("d1-mese", "mese", "mes", "ˈmeːze", "sostantivo", "tempo", "A1", 1, { it: "Il mese prossimo vado in vacanza.", es: "El mes que viene voy de vacaciones." }, { gender: "m", plural: "mesi" }),
  D("d1-anno", "anno", "año", "ˈanno", "sostantivo", "tempo", "A1", 1, { it: "Felice anno nuovo! Ho trent'anni.", es: "¡Feliz año nuevo! Tengo treinta años." }, { gender: "m", plural: "anni", collocations: ["anno nuovo", "capodanno", "anni anni"] }),
  D("d1-mattina", "mattina", "mañana (parte del día)", "matˈtiːna", "sostantivo", "tempo", "A1", 1, { it: "La mattina bevo il caffè.", es: "Por la mañana bebo el café." }, { gender: "f", plural: "mattine", note: "'Mañana' día siguiente = domani; 'mañana' parte del día = mattina. di mattina = por la mañana." }),
  D("d1-pomeriggio", "pomeriggio", "tarde (mediodía)", "pomeriˈddʒo", "sostantivo", "tempo", "A1", 1, { it: "Ci vediamo nel pomeriggio.", es: "Nos vemos por la tarde." }, { gender: "m", plural: "pomeriggi", note: "pomeriggio = tarde hasta ~18h; sera = tarde-noche. 'Buenas tardes' = buonasera (¡no 'buon pomeriggio'!)." }),
  D("d1-notte", "notte", "noche", "ˈnɔtte", "sostantivo", "tempo", "A1", 1, { it: "Buonanotte, dormi bene!", es: "Buenas noches, ¡duerme bien!" }, { gender: "f", plural: "notti", ant: ["giorno"] }),
  D("d1-volta", "volta", "vez / vuelta", "ˈvolta", "sostantivo", "tempo", "A1", 1, { it: "Una volta a settimana vado in palestra.", es: "Una vez a la semana voy al gimnasio." }, { gender: "f", plural: "volte", collocations: ["una volta", "due volte", "a volte", "ogni tanto"], note: "a volte = a veces; un'altra volta = otra vez; ogni volta = cada vez." }),

  /* ══ meses ══ */
  D("d1-gennaio", "gennaio", "enero", "dʒenˈnaːjo", "sostantivo", "tempo", "A1", 2, { it: "A gennaio comincio il corso.", es: "En enero empiezo el curso." }, { gender: "m" }),
  D("d1-febbraio", "febbraio", "febrero", "febˈbraːjo", "sostantivo", "tempo", "A1", 2, { it: "A febbraio si festeggia il Carnevale.", es: "En febrero se celebra el Carnaval." }, { gender: "m" }),
  D("d1-marzo", "marzo", "marzo", "ˈmartso", "sostantivo", "tempo", "A1", 2, { it: "In marzo fioriscono i mandorli.", es: "En marzo florecen los almendros." }, { gender: "m" }),
  D("d1-aprile", "aprile", "abril", "aˈpriːle", "sostantivo", "tempo", "A1", 2, { it: "Ad aprile piove spesso.", es: "En abril llueve a menudo." }, { gender: "m", note: "Aprile dolce dormire — proverbio italiano." }),
  D("d1-maggio", "maggio", "mayo", "ˈmaddʒo", "sostantivo", "tempo", "A1", 2, { it: "Il primo maggio è festa in Italia.", es: "El primero de mayo es fiesta en Italia." }, { gender: "m" }),
  D("d1-giugno", "giugno", "junio", "ˈdʒuɲɲo", "sostantivo", "tempo", "A1", 2, { it: "A giugno finisce la scuola.", es: "En junio termina la escuela." }, { gender: "m" }),
  D("d1-luglio", "luglio", "julio", "ˈluʎʎo", "sostantivo", "tempo", "A1", 2, { it: "In luglio va tutta Italia al mare.", es: "En julio toda Italia va al mar." }, { gender: "m" }),
  D("d1-agosto", "agosto", "agosto", "aˈɡosto", "sostantivo", "tempo", "A1", 2, { it: "Ad agosto le città si svuotano.", es: "En agosto las ciudades se vacían." }, { gender: "m" }),
  D("d1-settembre", "settembre", "septiembre", "setˈtɛmbre", "sostantivo", "tempo", "A1", 2, { it: "Settembre, si torna a scuola.", es: "Septiembre, se vuelve a la escuela." }, { gender: "m" }),
  D("d1-ottobre", "ottobre", "octubre", "ˈɔttobre", "sostantivo", "tempo", "A1", 2, { it: "In ottobre vendemmiano l'uva.", es: "En octubre vendimian la uva." }, { gender: "m" }),
  D("d1-novembre", "novembre", "noviembre", "noˈvɛmbre", "sostantivo", "tempo", "A1", 2, { it: "A novembre arrivano i primi freddi.", es: "En noviembre llegan los primeros fríos." }, { gender: "m" }),
  D("d1-dicembre", "dicembre", "diciembre", "diˈtʃɛmbre", "sostantivo", "tempo", "A1", 2, { it: "Dicembre è il mese del panettone.", es: "Diciembre es el mes del panetone." }, { gender: "m" }),

  /* ══ personas ══ */
  D("d1-uomo", "uomo", "hombre", "ˈwɔːmo", "sostantivo", "famiglia", "A1", 1, { it: "Un uomo alto con un cappello nero.", es: "Un hombre alto con un sombrero negro." }, { gender: "m", plural: "uomini", ant: ["donna"] }),
  D("d1-donna", "donna", "mujer", "ˈdonna", "sostantivo", "famiglia", "A1", 1, { it: "Quella donna è mia zia.", es: "Esa mujer es mi tía." }, { gender: "f", plural: "donne", ant: ["uomo"] }),
  D("d1-bambino", "bambino", "niño", "bamˈbiːno", "sostantivo", "famiglia", "A1", 1, { it: "Il bambino gioca nel parco.", es: "El niño juega en el parque." }, { gender: "m", plural: "bambini" }),
  D("d1-ragazzo", "ragazzo", "chico / muchacho", "raˈɡattso", "sostantivo", "relazioni", "A1", 1, { it: "Quel ragazzo è molto simpatico.", es: "Ese chico es muy simpático." }, { gender: "m", plural: "ragazzi", note: "ragazzi también = chicos y chicas juntos ('i ragazzi' = los chicos, grupo mixto)." }),
  D("d1-persona", "persona", "persona", "perˈsoːna", "sostantivo", "relazioni", "A1", 1, { it: "È una persona molto gentile.", es: "Es una persona muy amable." }, { gender: "f", plural: "persone", note: "persona es femenina pero sirve para ambos sexos (como español)." }),
  D("d1-gente", "gente", "gente", "ˈdʒɛnte", "sostantivo", "relazioni", "A1", 1, { it: "C'è tanta gente in piazza.", es: "Hay mucha gente en la plaza." }, { gender: "f", note: "gente es singular en italiano (la gente è…) — ¡cuidado, como en español!" }),
  D("d1-nome", "nome", "nombre", "ˈnɔːme", "sostantivo", "astratto", "A1", 1, { it: "Il mio nome è Marco, e il tuo?", es: "Mi nombre es Marco, ¿y el tuyo?" }, { gender: "m", plural: "nomi" }),
  D("d1-zio", "zio", "tío", "ˈtsiːo", "sostantivo", "famiglia", "A1", 1, { it: "Mio zio vive a Torino.", es: "Mi tío vive en Turín." }, { gender: "m", plural: "zii", related: ["zia"] }),
  D("d1-zia", "zia", "tía", "ˈtsiːa", "sostantivo", "famiglia", "A1", 1, { it: "Mia zia fa la pasta fresca.", es: "Mi tía hace pasta fresca." }, { gender: "f", plural: "zie" }),
  D("d1-cugino", "cugino", "primo (familiar)", "kuˈdʒiːno", "sostantivo", "famiglia", "A1", 1, { it: "Mio cugino ha la mia età.", es: "Mi primo tiene mi edad." }, { gender: "m", plural: "cugini", note: "'Primo' en italiano = primero (adj.). ¡El familiar es cugino!" }),
  D("d1-nipote", "nipote", "sobrino / nieto", "niˈpɔːte", "sostantivo", "famiglia", "A1", 1, { it: "I miei nipoti mi chiamano nonna.", es: "Mis nietos me llaman abuela." }, { note: "nipote = sobrino/a Y nieto/a — el contexto decide (como 'nieto/sobrino', doble sentido)." }),

  /* ══ comida A1 ══ */
  D("d1-latte", "latte", "leche", "ˈlatte", "sostantivo", "alimentazione", "A1", 1, { it: "Un cappuccino con latte, per favore.", es: "Un capuchino con leche, por favor." }, { gender: "m", plural: "latti" }),
  D("d1-uovo", "uovo", "huevo", "ˈwɔːvo", "sostantivo", "alimentazione", "A1", 1, { it: "Due uova al tegamino, per favore.", es: "Dos huevos fritos, por favor." }, { gender: "m", plural: "uova", note: "¡Plural irregularísimo!: m. uovo → f. uova (le uova). Singular masc., plural fem." }),
  D("d1-zucchero", "zucchero", "azúcar", "ˈtsukkero", "sostantivo", "alimentazione", "A1", 1, { it: "Un caffè con poco zucchero.", es: "Un café con poco azúcar." }, { gender: "m" }),
  D("d1-sale", "sale", "sal", "ˈsaːle", "sostantivo", "alimentazione", "A1", 1, { it: "Passami il sale, per favore.", es: "Pásame la sal, por favor." }, { gender: "m" }),
  D("d1-olio", "olio", "aceite (de oliva)", "ˈɔːljo", "sostantivo", "alimentazione", "A1", 1, { it: "L'olio extravergine d'oliva toscano.", es: "El aceite de oliva extravirgen toscano." }, { gender: "m", plural: "oli", collocations: ["olio d'oliva", "olio extravergine"] }),
  D("d1-pomodoro", "pomodoro", "tomate", "pomoˈdɔːro", "sostantivo", "alimentazione", "A1", 1, { it: "Gli spaghetti al pomodoro sono un classico.", es: "Los espaguetis al tomate son un clásico." }, { gender: "m", plural: "pomodori" }),
  D("d1-insalata", "insalata", "ensalada", "insaˈlaːta", "sostantivo", "alimentazione", "A1", 1, { it: "Un'insalata mista come contorno.", es: "Una ensalada mixta de guarnición." }, { gender: "f", plural: "insalate" }),
  D("d1-pasta", "pasta", "pasta / masa", "ˈpasta", "sostantivo", "alimentazione", "A1", 1, { it: "La pasta fresca fatta in casa.", es: "La pasta fresca hecha en casa." }, { gender: "f", plural: "paste", collocations: ["pasta al pomodoro", "pasta alla carbonara"] }),
  D("d1-riso", "riso", "arroz", "ˈriːzo", "sostantivo", "alimentazione", "A1", 1, { it: "Il risotto alla milanese è dorato.", es: "El risotto a la milanesa es dorado." }, { gender: "m", plural: "risi", collocations: ["risotto"] }),
  D("d1-mela", "mela", "manzana", "ˈmɛːla", "sostantivo", "alimentazione", "A1", 1, { it: "Una mela al giorno toglie il medico di torno.", es: "Una manzana al día aleja al médico." }, { gender: "f", plural: "mele" }),
  D("d1-arancia", "arancia", "naranja", "aˈrantʃa", "sostantivo", "alimentazione", "A1", 1, { it: "Un succo d'arancia fresco.", es: "Un jugo de naranja fresco." }, { gender: "f", plural: "arance", note: "Plural irrugular: l'arancia → le arance (sin -i-)." }),
  D("d1-verdura", "verdura", "verdura", "verˈduːra", "sostantivo", "alimentazione", "A1", 1, { it: "Mangio verdura ogni giorno.", es: "Como verdura cada día." }, { gender: "f" }),
  D("d1-patata", "patata", "patata", "paˈtaːta", "sostantivo", "alimentazione", "A1", 1, { it: "Le patatine fritte, un vizio.", es: "Las papas fritas, un vicio." }, { gender: "f", plural: "patate" }),
  D("d1-birra", "birra", "cerveza", "ˈbirra", "sostantivo", "alimentazione", "A1", 1, { it: "Una birra fresca, per favore!", es: "¡Una cerveza fría, por favor!" }, { gender: "f", plural: "birre", collocations: ["birra alla spina"] }),
  D("d1-te", "tè", "té", "tɛ", "sostantivo", "alimentazione", "A1", 1, { it: "Un tè verde con limone.", es: "Un té verde con limón." }, { gender: "m" }),
  D("d1-succo", "succo", "jugo", "ˈsukkə", "sostantivo", "alimentazione", "A1", 1, { it: "Un succo di frutta per i bambini.", es: "Un jugo de fruta para los niños." }, { gender: "m", plural: "succhi", related: ["sugo"] }),
  D("d1-burro", "burro", "mantequilla", "ˈburro", "sostantivo", "alimentazione", "A1", 2, { it: "Pane, burro e marmellata: colazione perfetta.", es: "Pan, mantequilla y mermelada: desayuno perfecto." }, { gender: "m", ff: true, note: "⚠️ FALSO AMIGO: burro = MANTEQUILLA, no 'burro' (asno). El animal se dice asino." }),
  D("d1-gelato", "gelato", "helado", "dʒeˈlaːto", "sostantivo", "alimentazione", "A1", 1, { it: "Un gelato al pistacchio, per favore!", es: "¡Un helado de pistacho, por favor!" }, { gender: "m", plural: "gelati", collocations: ["gelato artigianale", "gelateria"] }),
  D("d1-colazione-prima", "fare colazione", "desayunar", "fare kolatˈtsjoːne", "espressione", "alimentazione", "A1", 1, { it: "Faccio colazione alle sette e mezza.", es: "Desayuno a las siete y media." }, { note: "'Desayunar' no es un verbo simple: fare colazione (hacer desayuno). También 'pranzare' = almorzar y 'cenare' = cenar." }),
  D("d1-pranzo", "pranzo", "almuerzo / comida", "ˈprantso", "sostantivo", "alimentazione", "A1", 1, { it: "A pranzo mangio un panino.", es: "Al mediodía como un sándwich." }, { gender: "m", plural: "pranzi", collocations: ["a pranzo", "pranzo della domenica"] }),
  D("d1-cena", "cena", "cena", "ˈtʃeːna", "sostantivo", "alimentazione", "A1", 1, { it: "Stasera cena alle nove.", es: "Esta noche cena a las nueve." }, { gender: "f", plural: "cene" }),

  /* ══ objetos y casa ══ */
  D("d1-sedia", "sedia", "silla", "ˈseːdja", "sostantivo", "casa", "A1", 1, { it: "Questa sedia è scomoda.", es: "Esta silla es incómoda." }, { gender: "f", plural: "sedie" }),
  D("d1-finestra", "finestra", "ventana", "fiˈnɛstra", "sostantivo", "casa", "A1", 1, { it: "Apri la finestra, che caldo!", es: "Abre la ventana, ¡qué calor!" }, { gender: "f", plural: "finestre", ant: ["porta"] }),
  D("d1-divano", "divano", "sofá", "diˈvaːno", "sostantivo", "casa", "A1", 2, { it: "Il gatto dorme sul divano.", es: "El gato duerme en el sofá." }, { gender: "m", plural: "divani" }),
  D("d1-armadio", "armadio", "armario", "arˈmaːdjo", "sostantivo", "casa", "A1", 1, { it: "Metto i vestiti nell'armadio.", es: "Pongo la ropa en el armario." }, { gender: "m", plural: "armadi" }),
  D("d1-ombrello", "ombrello", "paraguas", "omˈbrɛllo", "sostantivo", "casa", "A1", 1, { it: "Ho dimenticato l'ombrello a casa!", es: "¡He olvidado el paraguas en casa!" }, { gender: "m", plural: "ombrelli" }),
  D("d1-occhiali", "occhiali", "gafas / lentes", "okˈkjaːli", "sostantivo", "corpo", "A1", 1, { it: "Non trovo i miei occhiali da sole.", es: "No encuentro mis gafas de sol." }, { gender: "m", plural: "occhiali", note: "Solo plural en italiano (gli occhiali) — como 'gafas/lentes'. un paio di occhiali." }),
  D("d1-orologio", "orologio", "reloj", "oroˈlɔːdʒo", "sostantivo", "tempo", "A1", 1, { it: "L'orologio della stazione è perfetto.", es: "El reloj de la estación es perfecto." }, { gender: "m", plural: "orologi" }),
  D("d1-bicicletta", "bicicletta", "bicicleta", "bitʃiˈkletta", "sostantivo", "transporte", "A1", 1, { it: "Vado al lavoro in bicicletta.", es: "Voy al trabajo en bicicleta." }, { gender: "f", plural: "biciclette", note: "in bicicletta = en bicicleta (preposición in)." }),
  D("d1-mano", "mano", "mano", "ˈmaːno", "sostantivo", "corpo", "A1", 1, { it: "Dammi la mano, per favore.", es: "Dame la mano, por favor." }, { gender: "f", plural: "mani", note: "Femenino irregular con plural en -i: la mano → le mani." }),
  D("d1-piede", "piede", "pie", "ˈpjeːde", "sostantivo", "corpo", "A1", 1, { it: "Mi fa male un piede.", es: "Me duele un pie." }, { gender: "m", plural: "piedi" }),

  /* ══ ciudad y comunicación ══ */
  D("d1-posto", "posto", "lugar / sitio / puesto", "ˈposto", "sostantivo", "citta", "A1", 1, { it: "Cerco un posto dove mangiare.", es: "Busco un lugar donde comer." }, { gender: "m", plural: "posti", collocations: ["posto a sedere", "posteggiare", "posto di lavoro"] }),
  D("d1-paese", "paese", "país / pueblo", "paˈeːze", "sostantivo", "citta", "A1", 1, { it: "L'Italia è un paese bellissimo. Un piccolo paese di montagna.", es: "Italia es un país bellísimo. Un pequeño pueblo de montaña." }, { gender: "m", plural: "paesi", note: "Doble sentido: país (Estado) y pueblo (aldea). El contexto distingue." }),
  D("d1-via", "via", "calle / camino", "ˈviːa", "sostantivo", "citta", "A1", 1, { it: "Abito in via Garibaldi, al numero cinque.", es: "Vivo en la calle Garibaldi, en el número cinco." }, { gender: "f", plural: "vie", note: "via = calle y 'vía'. 'Por la calle X' = in via X. '¡Vamos!' = Andiamo! / Via!" }),
  D("d1-ospedale", "ospedale", "hospital", "ospeˈdaːle", "sostantivo", "salud", "A1", 1, { it: "Mi portano all'ospedale.", es: "Me llevan al hospital." }, { gender: "m", plural: "ospedali" }),
  D("d1-posta", "posta", "correo (oficina)", "ˈpɔsta", "sostantivo", "citta", "A1", 1, { it: "Devo andare alla posta a spedire un pacco.", es: "Tengo que ir al correo a enviar un paquete." }, { gender: "f", note: "alla posta = al correo (oficina postal). email = posta elettronica." }),
  D("d1-parola", "parola", "palabra", "paˈroːla", "sostantivo", "comunicazione", "A1", 1, { it: "Come si scrive questa parola?", es: "¿Cómo se escribe esta palabra?" }, { gender: "f", plural: "parole", collocations: ["una parola alla volta", "in altre parole"] }),
  D("d1-frase", "frase", "frase / oración", "ˈfraːze", "sostantivo", "comunicazione", "A1", 1, { it: "Ripeto la frase un'altra volta.", es: "Repito la frase otra vez." }, { gender: "f", plural: "frasi" }),
  D("d1-domanda", "domanda", "pregunta", "doˈmanda", "sostantivo", "comunicazione", "A1", 1, { it: "Ho una domanda per lei.", es: "Tengo una pregunta para usted." }, { gender: "f", plural: "domande", ant: ["risposta"], note: "'Pregunta' = domanda; 'pedir' = chiedere. No confundir domanda (pregunta) con domandare (preguntar)." }),
  D("d1-risposta", "risposta", "respuesta", "riˈspɔsta", "sostantivo", "comunicazione", "A1", 1, { it: "La sua risposta mi sorprende.", es: "Su respuesta me sorprende." }, { gender: "f", plural: "risposte" }),
  D("d1-problema", "problema", "problema", "proˈblɛːma", "sostantivo", "astratto", "A1", 1, { it: "Nessun problema, ci penso io!", es: "Ningún problema, ¡yo me encargo!" }, { gender: "m", plural: "problemi", note: "Como en español: problema es masculino aunque termina en -a (il problema → i problemi)." }),
  D("d1-vita", "vita", "vida / cintura", "ˈviːta", "sostantivo", "astratto", "A1", 1, { it: "La vita è bella quando hai amici.", es: "La vida es bella cuando tienes amigos." }, { gender: "f", plural: "vite", collocations: ["la bella vita", "vita da romani"] }),
  D("d1-mondo", "mondo", "mundo", "ˈmondo", "sostantivo", "astratto", "A1", 1, { it: "Il mio sogno è girare il mondo.", es: "Mi sueño es dar la vuelta al mundo." }, { gender: "m", plural: "mondi" }),

  /* ══ avverbi temporales y de modo A1 ══ */
  D("d1-adesso", "adesso", "ahora (momento exacto)", "aˈdɛsso", "avverbio", "tempo", "A1", 1, { it: "Adesso capisco tutto!", es: "¡Ahora entiendo todo!" }, { syn: ["ora"] }),
  D("d1-poi", "poi", "después / luego", "pɔi", "avverbio", "tempo", "A1", 1, { it: "Prima studio, poi esco.", es: "Primero estudio, luego salgo." }),
  D("d1-prima-avv", "prima", "antes / primero", "ˈpriːma", "avverbio", "tempo", "A1", 1, { it: "Prima di uscire, chiudi la porta.", es: "Antes de salir, cierra la puerta." }, { ant: ["poi", "dopo"], note: "prima di + infinitivo = antes de hacer. prima…poi = primero…después." }),
  D("d1-dopo-avv", "dopo", "después", "ˈdopo", "avverbio", "tempo", "A1", 1, { it: "Ci vediamo dopo la lezione.", es: "Nos vemos después de la clase." }, { ant: ["prima"], note: "dopo + infinitivo = después de hacer (dopo mangiato, coloquial: después de comer)." }),
  D("d1-molto", "molto", "mucho / muy", "ˈmɔlto", "avverbio", "astratto", "A1", 1, { it: "Mi piace molto. Ho molto tempo.", es: "Me gusta mucho. Tengo mucho tiempo." }, { ant: ["poco"], note: "Concuerda como adjetivo: molta acqua, molti amici, molte volte." }),
  D("d1-poco", "poco", "poco", "ˈpɔːko", "avverbio", "astratto", "A1", 1, { it: "Parlo poco italiano, ma capisco molto.", es: "Hablo poco italiano, pero entiendo mucho." }, { ant: ["molto"], note: "un poco di = un poco de (un po' di pane — con apócope po')." }),
  D("d1-tanto", "tanto", "tanto / mucho", "ˈtanto", "avverbio", "astratto", "A1", 1, { it: "Ti voglio tanto bene!", es: "¡Te quiero tanto!" }, { syn: ["molto"] }),
  D("d1-sempre-avv", "sempre", "siempre", "ˈsɛmpre", "avverbio", "tempo", "A1", 1, { it: "Prendo sempre il caffè alle otto.", es: "Siempre tomo el café a las ocho." }, { ant: ["mai"] }),
  D("d1-mai-avv", "mai", "nunca / jamás", "mai", "avverbio", "tempo", "A1", 1, { it: "Non sono mai stata a Venezia.", es: "Nunca he estado en Venecia." }, { ant: ["sempre"], note: "non…mai = nunca (doble negación, como español)." }),
  D("d1-gia", "già", "ya", "dʒa", "avverbio", "tempo", "A1", 1, { it: "Ho già fatto i compiti.", es: "Ya he hecho los deberes." }),
  D("d1-ancora", "ancora", "todavía / aún / otra vez", "anˈkora", "avverbio", "tempo", "A1", 1, { it: "Sei ancora qui? Non capisco ancora bene.", es: "¿Todavía estás aquí? Todavía no entiendo bien." }, { note: "ancora = todavía (no…ancora = todavía no) y también 'otra vez' (ancora una volta)." }),
  D("d1-subito", "subito", "inmediatamente / enseguida", "ˈsubito", "avverbio", "tempo", "A1", 1, { it: "Arrivo subito!", es: "¡Llego enseguida!" }),
  D("d1-presto", "presto", "temprano / pronto", "ˈprɛsto", "avverbio", "tempo", "A1", 1, { it: "Domani mi alzo presto.", es: "Mañana me levanto temprano." }, { ant: ["tardi"] }),
  D("d1-tardi", "tardi", "tarde", "ˈtardi", "avverbio", "tempo", "A1", 1, { it: "Scusa il ritardo, ho fatto tardi al lavoro.", es: "Disculpa el retraso, hice tarde en el trabajo." }, { ant: ["presto"] }),
  D("d1-quasi", "quasi", "casi", "ˈkwaːzi", "avverbio", "astratto", "A1", 1, { it: "Sono quasi pronto!", es: "¡Estoy casi listo!" }),
  D("d1-forse", "forse", "quizá / tal vez", "ˈfɔrse", "avverbio", "astratto", "A1", 1, { it: "Forse domani piove.", es: "Quizá mañana llueva." }, { syn: ["magari"], note: "magari = ojalá/quizá (más expresivo y coloquial)." }),
  D("d1-bene", "bene", "bien", "ˈbɛːne", "avverbio", "astratto", "A1", 1, { it: "Parli bene l'italiano!", es: "¡Hablas bien el italiano!" }, { ant: ["male"], note: "stare bene = estar bien. mollo bene… Va bene! = ¡está bien! / ¡de acuerdo!" }),
  D("d1-male", "male", "mal", "ˈmaːle", "avverbio", "astratto", "A1", 1, { it: "Mi sento male oggi.", es: "Me siento mal hoy." }, { ant: ["bene"] }),
  D("d1-insieme", "insieme", "juntos / junto", "inˈsjɛːme", "avverbio", "relazioni", "A1", 1, { it: "Andiamo insieme al cinema?", es: "¿Vamos juntos al cine?" }, { collocations: ["insieme a"] }),
  D("d1-qui", "qui", "aquí", "kwi", "avverbio", "astratto", "A1", 1, { it: "Vieni qui, per favore!", es: "¡Ven aquí, por favor!" }, { ant: ["lì", "là"], syn: ["qua"] }),
  D("d1-li", "lì / là", "allí / ahí / allí", "li", "avverbio", "astratto", "A1", 1, { it: "Il libro è lì, sul tavolo.", es: "El libro está ahí, sobre la mesa." }, { ant: ["qui"], syn: ["qua"], note: "lì (ahí, cerca del oyente), là (allí, lejos). qui/qua = aquí." }),
];
