import type { Exercise } from "./types";

/* ── Banca de ejercicios · motor de práctica ──────────────────────── */
/* Nota: las citas internas usan comillas tipográficas “ ” */

export const EXERCISES: Exercise[] = [
  /* ═══ A1 ═══ */
  { id: "ex-a1-001", type: "mc", level: "A1", topic: "articoli", prompt: "Completa: “___ libro è interessante.”",
    options: ["Il", "Lo", "La", "I"], answer: 0, explain: "“Libro” es masculino y empieza por consonante simple → il libro." },
  { id: "ex-a1-002", type: "mc", level: "A1", topic: "articoli", prompt: "Completa: “___ studente è nuovo.” (estudiante, masculino, empieza por “st”)",
    options: ["Il", "Lo", "La", "Gli"], answer: 1, explain: "Ante s + consonante (st, sc, sp) masculino singular → lo studente." },
  { id: "ex-a1-003", type: "mc", level: "A1", topic: "verbi", prompt: "Completa: “Io ___ fame.” (Tengo hambre)",
    options: ["ho", "sono", "hai", "ha"], answer: 0, explain: "Tener hambre = avere fame. io → ho." },
  { id: "ex-a1-004", type: "mc", level: "A1", topic: "verbi", prompt: "Completa: “Noi ___ italiani.”",
    options: ["siamo", "sono", "siete", "sei"], answer: 0, explain: "essere: noi siamo." },
  { id: "ex-a1-005", type: "mc", level: "A1", topic: "presente", prompt: "Completa: “Tu ___ il caffè ogni mattina.” (bere)",
    options: ["bevi", "bevo", "beve", "beviamo"], answer: 0, explain: "bere: io bevo, tu bevi, lui beve." },
  { id: "ex-a1-006", type: "mc", level: "A1", topic: "presente", prompt: "Completa: “Lei ___ all'università.” (frequentare)",
    options: ["frequenta", "frequentano", "frequento", "frequentiamo"], answer: 0, explain: "frequentare: lui/lei → frequenta." },
  { id: "ex-a1-007", type: "mc", level: "A1", topic: "plurale", prompt: "El plural de “la casa” es…",
    options: ["le case", "i casi", "le casae", "il case"], answer: 0, explain: "Femenino -a → -e: le case." },
  { id: "ex-a1-008", type: "mc", level: "A1", topic: "genere", prompt: "¿Cuál de estas palabras es femenina?",
    options: ["la chiave", "il tavolo", "lo studente", "il pane"], answer: 0, explain: "la chiave es femenina (plural: le chiavi)." },
  { id: "ex-a1-009", type: "mc", level: "A1", topic: "numeri", prompt: "“Che ore sono?” → Son las 3:30.",
    options: ["Sono le tre e mezza.", "È l'una e mezza.", "Sono le quattro e mezza.", "È mezzogiorno."], answer: 0, explain: "3:30 = le tre e mezza. A la una en punto: è l'una." },
  { id: "ex-a1-010", type: "mc", level: "A1", topic: "vocabolario", prompt: "¿Qué significa “A presto!”?",
    options: ["¡Hasta pronto!", "¡Buen provecho!", "¡Feliz cumpleaños!", "¡De nada!"], answer: 0, explain: "a presto = hasta pronto; a dopo = hasta luego." },
  { id: "ex-a1-011", type: "mc", level: "A1", topic: "domande", prompt: "Para preguntar el nombre en registro formal:",
    options: ["Come si chiama, Lei?", "Come ti chiami?", "Come stai?", "Quanti anni hai?"], answer: 0, explain: "Formal usa Lei: Come si chiama? Informal: Come ti chiami?" },
  { id: "ex-a1-012", type: "tf", level: "A1", topic: "verbi", prompt: "¿“Voi siete spagnoli” es correcto?", statement: "Voi siete spagnoli.", answer: true, explain: "essere: voi siete. Correcto." },
  { id: "ex-a1-013", type: "tf", level: "A1", topic: "articoli", prompt: "¿“La problema è difficile” es correcto?", statement: "La problema è difficile.", answer: false, explain: "il problema es masculino pese a terminar en -a: IL problema." },
  { id: "ex-a1-014", type: "tf", level: "A1", topic: "negazione", prompt: "¿“Non ho un fratello” significa “No tengo un hermano”?", statement: "Non ho un fratello.", answer: true, explain: "La negación se forma con non antes del verbo." },
  { id: "ex-a1-015", type: "fill", level: "A1", topic: "verbi", prompt: "Completa con essere: io ___ studente.", sentence: "Io ___ studente.", accepted: ["sono"], explain: "essere (io) = sono." },
  { id: "ex-a1-016", type: "fill", level: "A1", topic: "verbi", prompt: "Completa con avere: loro ___ fame.", sentence: "Loro ___ fame.", accepted: ["hanno"], explain: "avere (loro) = hanno." },
  { id: "ex-a1-017", type: "fill", level: "A1", topic: "presente", prompt: "Completa: noi ___ (parlare) italiano.", sentence: "Noi ___ italiano.", accepted: ["parliamo"], explain: "parlare: noi parliamo." },
  { id: "ex-a1-018", type: "fill", level: "A1", topic: "articoli", prompt: "Completa: ___ zaino è nuovo. (mochila, masculino)", sentence: "___ zaino è nuovo.", accepted: ["lo"], explain: "z + consonante → lo zaino." },
  { id: "ex-a1-019", type: "order", level: "A1", topic: "domande", prompt: "Ordena la frase: “¿Dónde está la estación, por favor?”", words: ["dov'è", "la", "stazione", "per", "favore"], answer: ["dov'è", "la", "stazione", "per", "favore"], explain: "dov'è = contracción de dove + è." },
  { id: "ex-a1-020", type: "order", level: "A1", topic: "presente", prompt: "Ordena la frase: “Vivo en Roma con mi familia.”", words: ["abito", "a", "Roma", "con", "la", "mia", "famiglia"], answer: ["abito", "a", "Roma", "con", "la", "mia", "famiglia"], explain: "abitare: io abito. Ciudad con preposición a." },
  { id: "ex-a1-021", type: "order", level: "A1", topic: "situazioni", prompt: "Ordena la frase: “Un café, por favor.”", words: ["un", "caffè", "per", "favore"], answer: ["un", "caffè", "per", "favore"], explain: "Frase mínima de supervivencia en el bar." },
  { id: "ex-a1-022", type: "dictation", level: "A1", topic: "ascolto", prompt: "Escucha y escribe lo que oyes.", text: "Buongiorno, come stai?", es: "Buenos días, ¿cómo estás?" },
  { id: "ex-a1-023", type: "dictation", level: "A1", topic: "ascolto", prompt: "Escucha y escribe lo que oyes.", text: "Mi chiamo Anna e sono italiana.", es: "Me llamo Anna y soy italiana." },
  { id: "ex-a1-024", type: "dictation", level: "A1", topic: "ascolto", prompt: "Escucha y escribe lo que oyes.", text: "Quanto costa questo libro?", es: "¿Cuánto cuesta este libro?" },
  { id: "ex-a1-025", type: "translate", level: "A1", topic: "presente", prompt: "Traduce al italiano: “Me llamo Marco.”", to: "it", source: "Me llamo Marco.", accepted: ["mi chiamo marco", "io mi chiamo marco"], explain: "chiamarsi (verbo reflexivo): mi chiamo." },
  { id: "ex-a1-026", type: "translate", level: "A1", topic: "verbi", prompt: "Traduce al italiano: “Tengo dos hermanos.”", to: "it", source: "Tengo dos hermanos.", accepted: ["ho due fratelli"], explain: "Tener = avere: ho due fratelli." },
  { id: "ex-a1-027", type: "translate", level: "A1", topic: "domande", prompt: "Traduce: “¿Cómo se llama usted?”", to: "it", source: "¿Cómo se llama usted?", accepted: ["come si chiama", "come si chiama lei"], explain: "Formal: Come si chiama (Lei)?" },
  { id: "ex-a1-028", type: "mc", level: "A1", topic: "vocabolario", prompt: "“Grazie mille” significa…",
    options: ["Muchas gracias", "Mil disculpas", "Buenos días", "Hasta luego"], answer: 0, explain: "mille = mil → muchísimas gracias." },
  { id: "ex-a1-029", type: "mc", level: "A1", topic: "aggettivi", prompt: "Completa: “Maria è ___.” (alto, en femenino)",
    options: ["alta", "alto", "alti", "alte"], answer: 0, explain: "El adjetivo concuerda: femenino singular → alta." },
  { id: "ex-a1-030", type: "mc", level: "A1", topic: "numeri", prompt: "¿Cuánto es “sedici”?",
    options: ["16", "60", "6", "66"], answer: 0, explain: "sedici = 16; sessanta = 60; sei = 6." },

  /* ═══ A2 ═══ */
  { id: "ex-a2-001", type: "mc", level: "A2", topic: "passato", prompt: "Completa: “Ieri ___ al cinema.” (andare)",
    options: ["sono andato", "ho andato", "sono andare", "ho andare"], answer: 0, explain: "andare usa ESSERE como auxiliar: sono andato." },
  { id: "ex-a2-002", type: "mc", level: "A2", topic: "passato", prompt: "Completa: “Ho ___ la pizza.” (mangiare)",
    options: ["mangiato", "mangiata", "mangiati", "mangiare"], answer: 0, explain: "Con avere el participio no concuerda: ho mangiato." },
  { id: "ex-a2-003", type: "mc", level: "A2", topic: "passato", prompt: "Completa: “Da bambina ___ sempre felice.” (essere, imperfecto)",
    options: ["ero", "sono stata", "fui", "sarò"], answer: 0, explain: "Descripción en el pasado → imperfetto: ero." },
  { id: "ex-a2-004", type: "mc", level: "A2", topic: "preposizioni", prompt: "Completa: “Il libro è ___ tavolo.” (sobre el)",
    options: ["sul", "nel", "al", "dal"], answer: 0, explain: "su + il = sul (sobre el)." },
  { id: "ex-a2-005", type: "mc", level: "A2", topic: "preposizioni", prompt: "Completa: “Vado ___ dottore.” (al médico)",
    options: ["dal", "al", "del", "nel"], answer: 0, explain: "andare da + persona: dal dottore." },
  { id: "ex-a2-006", type: "mc", level: "A2", topic: "futuro", prompt: "Completa: “Domani ___ a Roma.” (andare)",
    options: ["andrò", "ando", "andrei", "vado"], answer: 0, explain: "Futuro de andare: andrò." },
  { id: "ex-a2-007", type: "mc", level: "A2", topic: "aggettivi", prompt: "Completa: “Marco è ___ alto di Luca.” (más alto)",
    options: ["più", "molto", "meno", "tanto"], answer: 0, explain: "Comparativo: più… di." },
  { id: "ex-a2-008", type: "mc", level: "A2", topic: "verbi", prompt: "Completa: “Io ___ alle sette.” (levantarse)",
    options: ["mi alzo", "alzo", "si alza", "alzami"], answer: 0, explain: "Verbo reflexivo: mi alzo." },
  { id: "ex-a2-009", type: "tf", level: "A2", topic: "passato", prompt: "¿“Ho andato a Roma” es correcto?", statement: "Ho andato a Roma.", answer: false, explain: "andare pide ESSERE: Sono andato a Roma." },
  { id: "ex-a2-010", type: "tf", level: "A2", topic: "passato", prompt: "¿“Mentre studiavo, ascoltavo musica” combina dos imperfectos correctamente?", statement: "Mentre studiavo, ascoltavo musica.", answer: true, explain: "Acciones simultáneas en el pasado → imperfetto en ambas." },
  { id: "ex-a2-011", type: "fill", level: "A2", topic: "passato", prompt: "Completa: “Ieri sera ___ un film.” (guardare)", sentence: "Ieri sera ___ un film.", accepted: ["ho guardato"], explain: "guardare + avere: ho guardato." },
  { id: "ex-a2-012", type: "fill", level: "A2", topic: "passato", prompt: "Completa: “Lei è ___ stamattina.” (partire, ella)", sentence: "Lei è ___ stamattina.", accepted: ["partita"], explain: "partire + essere, participio concuerda (ella): partita." },
  { id: "ex-a2-013", type: "fill", level: "A2", topic: "preposizioni", prompt: "Completa: “Abito ___ Italia, ___ Milano.” (en Italia, en Milán)", sentence: "Abito ___ Italia, ___ Milano.", accepted: ["in italia a milano", "in italia,a milano"], explain: "Países: in; ciudades: a." },
  { id: "ex-a2-014", type: "fill", level: "A2", topic: "verbi", prompt: "Completa con el imperfecto: “Quando ero piccolo ___ sempre fuori.” (giocare)", sentence: "Quando ero piccolo ___ sempre fuori.", accepted: ["giocavo"], explain: "imperfetto de giocare: giocavo." },
  { id: "ex-a2-015", type: "order", level: "A2", topic: "passato", prompt: "Ordena la frase: “Ayer fui al cine con amigos.”", words: ["ieri", "sono", "andato", "al", "cinema", "con", "gli", "amici"], answer: ["ieri", "sono", "andato", "al", "cinema", "con", "gli", "amici"], explain: "passato prossimo de andare + al (a+il) + gli amici." },
  { id: "ex-a2-016", type: "order", level: "A2", topic: "situazioni", prompt: "Ordena la frase: “Querría una habitación doble por dos noches.”", words: ["vorrei", "una", "camera", "doppia", "per", "due", "notti"], answer: ["vorrei", "una", "camera", "doppia", "per", "due", "notti"], explain: "vorrei = condizionale de volere (cortesía)." },
  { id: "ex-a2-017", type: "dictation", level: "A2", topic: "ascolto", prompt: "Escucha y escribe lo que oyes.", text: "Vorrei prenotare una camera per questa notte.", es: "Querría reservar una habitación por esta noche." },
  { id: "ex-a2-018", type: "dictation", level: "A2", topic: "ascolto", prompt: "Escucha y escribe lo que oyes.", text: "Che tempo fa oggi? C'è il sole.", es: "¿Qué tiempo hace hoy? Hace sol." },
  { id: "ex-a2-019", type: "translate", level: "A2", topic: "passato", prompt: "Traduce: “Esta mañana he tomado un café.”", to: "it", source: "Esta mañana he tomado un café.", accepted: ["stamattina ho preso un caffe", "stamattina ho bevuto un caffe", "ho preso un caffe stamattina"], explain: "prendere un caffè = tomar un café." },
  { id: "ex-a2-020", type: "translate", level: "A2", topic: "futuro", prompt: "Traduce: “Mañana iré al mercado.”", to: "it", source: "Mañana iré al mercado.", accepted: ["domani andro al mercato"], explain: "Futuro: andrò; a + il = al." },
  { id: "ex-a2-021", type: "mc", level: "A2", topic: "vocabolario", prompt: "En el mercado: “Un chilo di pane” significa…",
    options: ["Un kilo de pan", "Un pedazo de pan", "Un pan dulce", "Una barra pequeña"], answer: 0, explain: "chilo = kilo. También: mezzo chilo (medio kilo)." },
  { id: "ex-a2-022", type: "mc", level: "A2", topic: "situazioni", prompt: "En el hotel, para pedir la cuenta:",
    options: ["Il conto, per favore.", "La casa, per favore.", "Il menù, per favore.", "La chiave, per favore."], answer: 0, explain: "il conto = la cuenta." },
  { id: "ex-a2-023", type: "mc", level: "A2", topic: "ascolto", prompt: "En el diálogo del aeropuerto: ¿qué pide el agente?",
    options: ["El pasaporte y el billete", "Solo la maleta", "El desayuno", "La reserva del hotel"], answer: 0, explain: "“Passaporto e biglietto, per favore” — documentos de viaje." },
  { id: "ex-a2-024", type: "fill", level: "A2", topic: "preposizioni", prompt: "Completa: “Il telefono è ___ borsa.” (en la bolsa)", sentence: "Il telefono è ___ borsa.", accepted: ["nella"], explain: "in + la = nella." },
  { id: "ex-a2-025", type: "mc", level: "A2", topic: "pronomi", prompt: "Sustituye: “Vedo Maria” → …",
    options: ["La vedo", "Le vedo", "Lo vedo", "Mi vedo"], answer: 0, explain: "Pronombre directo femenino: la." },

  /* ═══ B1 ═══ */
  { id: "ex-b1-001", type: "mc", level: "B1", topic: "condizionale", prompt: "Completa: “___ un caffè, per favore.” (Querría)",
    options: ["Vorrei", "Voglio", "Volevo", "Vorremmo"], answer: 0, explain: "Vorrei = condicional de volere, la forma cortés por excelencia." },
  { id: "ex-b1-002", type: "mc", level: "B1", topic: "congiuntivo", prompt: "Completa: “Penso che ___ tardi.” (essere)",
    options: ["sia", "è", "sarà", "era"], answer: 0, explain: "Tras “penso che” → congiuntivo: sia." },
  { id: "ex-b1-003", type: "mc", level: "B1", topic: "pronomi", prompt: "Completa: “Ho scritto ___ Maria.” (a María)",
    options: ["a", "le", "la", "gli"], answer: 0, explain: "Escribir A alguien = complemento indirecto: a Maria (pronombre: le)." },
  { id: "ex-b1-004", type: "mc", level: "B1", topic: "imperativo", prompt: "Formal: “Si accomodi” significa…",
    options: ["Tómese asiento", "Disculpe", "Espere", "Venga aquí"], answer: 0, explain: "accomodarsi en imperativo formal: Si accomodi." },
  { id: "ex-b1-005", type: "mc", level: "B1", topic: "congiuntivo", prompt: "Completa: “Credo che Marco ___ ragione.” (avere)",
    options: ["abbia", "ha", "avrà", "aveva"], answer: 0, explain: "credere che + congiuntivo: abbia ragione." },
  { id: "ex-b1-006", type: "tf", level: "B1", topic: "condizionale", prompt: "¿“Se avrei tempo, viaggerei” es correcto?", statement: "Se avrei tempo, viaggerei.", answer: false, explain: "Correcto: “Se avessi tempo, viaggerei” (congiuntivo imperfecto tras se hipotético)." },
  { id: "ex-b1-007", type: "fill", level: "B1", topic: "pronomi", prompt: "Sustituye el objeto: “Questo libro? ___ leggo subito.”", sentence: "Questo libro? ___ leggo subito.", accepted: ["lo"], explain: "Libro = masculino singular → pronombre directo LO." },
  { id: "ex-b1-008", type: "fill", level: "B1", topic: "congiuntivo", prompt: "Completa: “Spero che tu ___ bene.” (stare)", sentence: "Spero che tu ___ bene.", accepted: ["stia"], explain: "sperare che + congiuntivo: stia." },
  { id: "ex-b1-009", type: "order", level: "B1", topic: "condizionale", prompt: "Ordena la frase: “Querría cambiar la reserva si es posible.”", words: ["vorrei", "cambiare", "la", "prenotazione", "se", "è", "possibile"], answer: ["vorrei", "cambiare", "la", "prenotazione", "se", "è", "possibile"], explain: "Fórmula cortés estándar en hoteles." },
  { id: "ex-b1-010", type: "dictation", level: "B1", topic: "ascolto", prompt: "Escucha y escribe lo que oyes.", text: "Secondo me, questo film è il migliore dell'anno.", es: "En mi opinión, esta película es la mejor del año." },
  { id: "ex-b1-011", type: "translate", level: "B1", topic: "congiuntivo", prompt: "Traduce: “Creo que es una buena idea.”", to: "it", source: "Creo que es una buena idea.", accepted: ["credo che sia una buona idea", "penso che sia una buona idea"], explain: "credo che + SIA (congiuntivo)." },
  { id: "ex-b1-012", type: "translate", level: "B1", topic: "pronomi", prompt: "Traduce: “¿Me lo puedes prestar?” (el libro)", to: "it", source: "¿Me lo puedes prestar?", accepted: ["me lo puoi prestare", "puoi prestarmelo"], explain: "Pronombres combinados: me (CI) + lo (CD)." },
  { id: "ex-b1-013", type: "mc", level: "B1", topic: "passato", prompt: "Completa: “Non ___ mai a Firenze.” (io, andare)",
    options: ["sono mai andato", "ho mai andato", "sono mai andare", "fui mai"], answer: 0, explain: "essere + mai + participio: non sono mai andato." },
  { id: "ex-b1-014", type: "mc", level: "B1", topic: "vocabolario", prompt: "“Fare un colloquio” significa…",
    options: ["Tener una entrevista", "Hacer una llamada", "Tomar un café", "Darse la mano"], answer: 0, explain: "il colloquio (di lavoro) = entrevista de trabajo." },
  { id: "ex-b1-015", type: "mc", level: "B1", topic: "situazioni", prompt: "En una reunión: “Restiamo in contatto” significa…",
    options: ["Mantengámonos en contacto", "Salgamos de la sala", "Escribamos el acta", "Terminemos ya"], answer: 0, explain: "restare/rimanere in contatto = mantener el contacto." },

  /* ═══ B2 ═══ */
  { id: "ex-b2-001", type: "mc", level: "B2", topic: "congiuntivo", prompt: "Completa: “Se ___ più tempo, leggerei di più.” (avere)",
    options: ["avessi", "avrei", "ho", "avrò"], answer: 0, explain: "Período hipotético 2º tipo: se + congiuntivo imperfecto → condizionale." },
  { id: "ex-b2-002", type: "mc", level: "B2", topic: "congiuntivo", prompt: "Completa: “Se avessi studiato, ___ l'esame.” (passare)",
    options: ["avrei passato", "sarei passato", "passerei", "avevo passato"], answer: 0, explain: "3er tipo: se + congiuntivo trapassado → condicional compuesto." },
  { id: "ex-b2-003", type: "mc", level: "B2", topic: "pronomi", prompt: "Completa: “Pensi ___?” (a esto)",
    options: ["ci", "ne", "lo", "gli"], answer: 0, explain: "ci sustituye complementos con a (a esto → ci)." },
  { id: "ex-b2-004", type: "mc", level: "B2", topic: "pronomi", prompt: "Completa: “Quanti anni ___ hai?” (de esto)",
    options: ["ne", "ci", "li", "le"], answer: 0, explain: "ne sustituye cantidades: ne ho ventitré." },
  { id: "ex-b2-005", type: "mc", level: "B2", topic: "grammatica", prompt: "Estilo indirecto: “Sono stanco” → Ha detto che…",
    options: ["era stanco", "è stanco", "sarà stanco", "fosse stanco"], answer: 0, explain: "Presente → imperfetto en estilo indirecto: era stanco." },
  { id: "ex-b2-006", type: "tf", level: "B2", topic: "congiuntivo", prompt: "¿Tras “secondo me” el subjuntivo es obligatorio?", statement: "Secondo me, Marco ha ragione.", answer: false, explain: "“Secondo me” expresa opinión sin que → indicativo. Subjuntivo tras “penso/credo che”." },
  { id: "ex-b2-007", type: "fill", level: "B2", topic: "congiuntivo", prompt: "Completa: “Vorrei che tu ___ qui.” (essere)", sentence: "Vorrei che tu ___ qui.", accepted: ["fossi"], explain: "vorrei che + congiuntivo imperfecto: fossi." },
  { id: "ex-b2-008", type: "fill", level: "B2", topic: "pronomi", prompt: "Sustituye: “Parliamo di questo domani” → “___ parliamo domani.”", sentence: "___ parliamo domani.", accepted: ["ne"], explain: "ne = de esto / de ello." },
  { id: "ex-b2-009", type: "translate", level: "B2", topic: "congiuntivo", prompt: "Traduce: “Si hubiera sabido, habría venido.”", to: "it", source: "Si hubiera sabido, habría venido.", accepted: ["se lo avessi saputo sarei venuto", "se l'avessi saputo sarei venuto", "se lo avessi saputo, sarei venuta"], explain: "Se + congiuntivo trapassato → condizionale composto (con essere: sarei venuto)." },
  { id: "ex-b2-010", type: "mc", level: "B2", topic: "grammatica", prompt: "¿Cuál es más formal?",
    options: ["La contatto quanto prima.", "Ti scrivo presto!", "Ci sentiamo!", "Dammi un colpo di telefono."], answer: 0, explain: "Registro formal: pronombre Lei, sin contracciones coloquiales." },
  { id: "ex-b2-011", type: "mc", level: "B2", topic: "vocabolario", prompt: "“Andare in porto” (idiomático) significa…",
    options: ["Llegar a buen término", "Ir de vacaciones", "Nadar al puerto", "Perder el barco"], answer: 0, explain: "Metafórico náutico: un proyecto que va in porto se realiza." },
  { id: "ex-b2-012", type: "dictation", level: "B2", topic: "ascolto", prompt: "Escucha y escribe lo que oyes.", text: "Se tutti contribuissero, l'inquinamento diminuirebbe sensibilmente.", es: "Si todos contribuyeran, la contaminación disminuiría sensiblemente." },

  /* ═══ C1 ═══ */
  { id: "ex-c1-001", type: "mc", level: "C1", topic: "grammatica", prompt: "Completa: “Nonostante ___ tardi, uscimmo.” (essere)",
    options: ["fosse", "era", "sia", "fossero"], answer: 0, explain: "nonostante + congiuntivo (imperfecto para el pasado): fosse." },
  { id: "ex-c1-002", type: "mc", level: "C1", topic: "grammatica", prompt: "¿Cuál suena más académico?",
    options: ["Il presente studio si propone di analizzare…", "In questo paper voglio parlare di…", "Adesso ti spiego una cosa…", "Ora vediamo un po'…"], answer: 0, explain: "Registro académico: nominalización, “si propone di”." },
  { id: "ex-c1-003", type: "mc", level: "C1", topic: "grammatica", prompt: "Concordancia: “Maria è ___ a casa.” (andarsene)",
    options: ["andata via", "andato via", "andati via", "andare via"], answer: 0, explain: "Con essere el participio concuerda con María: andata." },
  { id: "ex-c1-004", type: "fill", level: "C1", topic: "grammatica", prompt: "Impersonal: “___ che pioverà.” (parecer)", sentence: "___ che pioverà.", accepted: ["pare"], explain: "Pare che + futuro; verbo impersonal en 3ª persona singular." },
  { id: "ex-c1-005", type: "translate", level: "C1", topic: "grammatica", prompt: "Traduce (registro formal): “Les comunico que la reunión ha sido pospuesta.”", to: "it", source: "Les comunico que la reunión ha sido pospuesta.", accepted: ["vi comunico che la riunione e stata rinviata", "si comunica che la riunione e stata rinviata", "le comunico che la riunione e stata rinviata"], explain: "rinviare = posponer; con essere el participio concuerda con riunione (fem.): rinviata." },
  { id: "ex-c1-006", type: "mc", level: "C1", topic: "vocabolario", prompt: "El conector “peraltro” significa…",
    options: ["por lo demás / además", "sin embargo", "por lo tanto", "a pesar de"], answer: 0, explain: "peraltro = por lo demás; conector de refinamiento." },

  /* ═══ C2 ═══ */
  { id: "ex-c2-001", type: "mc", level: "C2", topic: "vocabolario", prompt: "“Sprezzatura” designa…",
    options: ["la elegancia sin esfuerzo, estudiada", "un plato de risotto", "un retraso del tren", "una moneda antigua"], answer: 0, explain: "Acuñado por Castiglione (1528): el arte de hacer difícil parecer fácil." },
  { id: "ex-c2-002", type: "mc", level: "C2", topic: "cultura", prompt: "El “endecasílabo” italiano tiene…",
    options: ["11 sílabas", "10 sílabas", "14 sílabas", "7 sílabas"], answer: 0, explain: "endecasillabo = 11 sílabas, el verso de la Divina Commedia." },
  { id: "ex-c2-003", type: "mc", level: "C2", topic: "grammatica", prompt: "¿Cuál es una variante regional toscana correcta?",
    options: ["“fo” por “faccio”", "“fo” por “facciamo”", "“fo” por “farò”", "“fo” por “facevo”"], answer: 0, explain: "En toscano “fo” = faccio; también “ve'” = vai." },
  { id: "ex-c2-004", type: "translate", level: "C2", topic: "grammatica", prompt: "Traduce con matiz: “No es que no quiera, es que no puedo.”", to: "it", source: "No es que no quiera, es que no puedo.", accepted: ["non e che non voglia, e che non posso", "non e che non voglia, semplicemente non posso"], explain: "“Non è che non voglia” + subjuntivo para el matiz concesivo." },

  /* ═══ Cultura ═══ */
  { id: "ex-cul-001", type: "mc", level: "A2", topic: "cultura", prompt: "¿Cuántas regiones tiene Italia?",
    options: ["20", "18", "22", "15"], answer: 0, explain: "Italia tiene 20 regiones, 5 con estatuto especial." },
  { id: "ex-cul-002", type: "mc", level: "B1", topic: "cultura", prompt: "El espresso se llama en italiano…",
    options: ["caffè", "espresso", "caffè nero", "caffotto"], answer: 0, explain: "En Italia el espresso simplemente es “un caffè”." },
  { id: "ex-cul-003", type: "mc", level: "B1", topic: "cultura", prompt: "La Divina Commedia se escribió en…",
    options: ["florentino del siglo XIV", "latín clásico", "siciliano", "milanés moderno"], answer: 0, explain: "Dante escribió en el vernáculo florentino, base del italiano moderno." },
  { id: "ex-cul-004", type: "mc", level: "A2", topic: "cultura", prompt: "El gesto de las puntas de los dedos juntas expresa…",
    options: ["¿qué quieres? / incredulidad", "aprobación", "hambre", "saludo militar"], answer: 0, explain: "Gesto icónico de incredulidad o pregunta perpleja." },

  /* ═══ Situaciones ═══ */
  { id: "ex-sit-aer-1", type: "mc", level: "A2", topic: "situazioni", prompt: "En el check-in: “Imbarco” significa…",
    options: ["Embarque", "Facturación", "Aduana", "Salida"], answer: 0, explain: "imbarco = embarque; check-in = accettazione." },
  { id: "ex-sit-aer-2", type: "order", level: "A2", topic: "situazioni", prompt: "Ordena la frase: “¿A qué hora sale el vuelo para Roma?”", words: ["a", "che", "ora", "parte", "il", "volo", "per", "Roma"], answer: ["a", "che", "ora", "parte", "il", "volo", "per", "Roma"], explain: "partire: il volo parte." },
  { id: "ex-sit-hot-1", type: "mc", level: "A2", topic: "situazioni", prompt: "En el hotel: “La colazione è inclusa?” pregunta por…",
    options: ["el desayuno", "la llave", "el ascensor", "el check-out"], answer: 0, explain: "colazione = desayuno." },
  { id: "ex-sit-hot-2", type: "fill", level: "A2", topic: "situazioni", prompt: "Completa: “Ho una ___ a nome Rossi.” (reserva)", sentence: "Ho una ___ a nome Rossi.", accepted: ["prenotazione"], explain: "prenotazione = reserva." },
  { id: "ex-sit-res-1", type: "mc", level: "A1", topic: "situazioni", prompt: "En el restaurante: “Il conto, per favore” es…",
    options: ["la cuenta, por favor", "el menú, por favor", "la mesa, por favor", "el vino, por favor"], answer: 0, explain: "conto = cuenta; menù = carta." },
  { id: "ex-sit-res-2", type: "order", level: "A1", topic: "situazioni", prompt: "Ordena la frase: “De primero comeré espaguetis.”", words: ["per", "primo", "mangio", "gli", "spaghetti"], answer: ["per", "primo", "mangio", "gli", "spaghetti"], explain: "per primo / per secondo = de primero / de segundo." },
  { id: "ex-sit-sup-1", type: "mc", level: "A1", topic: "situazioni", prompt: "En el supermercado: “Il reparto freschi” es…",
    options: ["la sección de frescos", "la caja", "el aparcamiento", "los congelados"], answer: 0, explain: "reparto = sección; freschi = productos frescos." },
  { id: "ex-sit-dir-1", type: "mc", level: "A1", topic: "situazioni", prompt: "Para pedir direcciones: “È lontano?” significa…",
    options: ["¿Está lejos?", "¿Está abierto?", "¿Está incluido?", "¿Está libre?"], answer: 0, explain: "lontano / vicino = lejos / cerca." },
  { id: "ex-sit-dir-2", type: "order", level: "A1", topic: "situazioni", prompt: "Ordena la frase: “Gire a la derecha en la plaza.”", words: ["giri", "a", "destra", "in", "piazza"], answer: ["giri", "a", "destra", "in", "piazza"], explain: "girare a destra / a sinistra." },
  { id: "ex-sit-med-1", type: "mc", level: "A2", topic: "situazioni", prompt: "En el médico: “Ho la febbre” significa…",
    options: ["Tengo fiebre", "Tengo hambre", "Tengo dolor", "Tengo frío"], answer: 0, explain: "la febbre = la fiebre." },
  { id: "ex-sit-tax-1", type: "mc", level: "A1", topic: "situazioni", prompt: "En el taxi: “Mi porti in centro, per favore” significa…",
    options: ["Lléveme al centro, por favor", "Espere aquí, por favor", "Pare aquí, por favor", "¿Cuánto cuesta?"], answer: 0, explain: "portare = llevar (transportar)." },

  /* ═══ Lecturas ═══ */
  { id: "ex-let-001", type: "tf", level: "A1", topic: "vocabolario", prompt: "Según la postal de Anna: Anna está en Roma de vacaciones.", statement: "Anna è a Roma in vacanza.", answer: true, explain: "“Sono arrivata a Roma” y habla de vacaciones." },
  { id: "ex-let-002", type: "mc", level: "A1", topic: "vocabolario", prompt: "¿Qué hace Anna cada día en Roma?",
    options: ["Visita un sitio nuevo", "Va al supermercado", "Trabaja en la oficina", "Va al médico"], answer: 0, explain: "“Ogni giorno visito un posto nuovo”." },
  { id: "ex-let-003", type: "tf", level: "A2", topic: "vocabolario", prompt: "Según la historia del mercado: Marco compró primero el pan.", statement: "Marco ha comprato prima il pane.", answer: false, explain: "En el relato compra primero la fruta, después el pan." },
  { id: "ex-let-004", type: "mc", level: "B1", topic: "vocabolario", prompt: "En la noticia del tren: el tema central es…",
    options: ["la alta velocidad ferroviaria italiana", "la historia de las estaciones", "la contaminación de Milán", "las huelgas de trenes"], answer: 0, explain: "Tema: alta velocità, Frecciarossa e Italo." },
  { id: "ex-let-005", type: "mc", level: "A2", topic: "vocabolario", prompt: "En la historia de Marco: ¿qué compró primero?",
    options: ["Fruta", "Pan", "Queso", "Vino"], answer: 0, explain: "Orden del relato: primero la fruta." },
  { id: "ex-let-006", type: "tf", level: "B2", topic: "vocabolario", prompt: "En el artículo del made in Italy: la calidad percibida es parte del éxito.", statement: "La qualità percepita fa parte del successo del made in Italy.", answer: true, explain: "El texto vincula marca + calidad percibida." },

  /* ═══ Escucha ═══ */
  { id: "ex-asc-001", type: "mc", level: "A1", topic: "ascolto", prompt: "En el diálogo del bar: ¿qué pide el cliente?",
    options: ["Un café y un croissant", "Un té", "Un capuchino y agua", "Solo agua"], answer: 0, explain: "“Un caffè e un cornetto, per favore”." },
  { id: "ex-asc-002", type: "mc", level: "A1", topic: "ascolto", prompt: "¿Dónde se desarrolla el diálogo del bar?",
    options: ["En un bar", "En una estación", "En un museo", "En un hotel"], answer: 0, explain: "Contexto: al banco del bar." },
  { id: "ex-asc-003", type: "mc", level: "A2", topic: "ascolto", prompt: "En el diálogo de la estación: ¿hacia qué ciudad viaja la señora?",
    options: ["Florencia", "Roma", "Nápoles", "Turín"], answer: 0, explain: "“Un biglietto per Firenze”." },
  { id: "ex-asc-004", type: "mc", level: "A2", topic: "ascolto", prompt: "¿Qué problema hay con el tren?",
    options: ["Va con 15 minutos de retraso", "Está cancelado", "Es directo", "Está lleno"], answer: 0, explain: "“Il treno è in ritardo di quindici minuti”." },
  { id: "ex-asc-005", type: "mc", level: "B1", topic: "ascolto", prompt: "En la entrevista de trabajo: ¿qué idiomas dice dominar la candidata?",
    options: ["Italiano, español e inglés", "Solo italiano", "Italiano y francés", "Italiano, alemán y chino"], answer: 0, explain: "“Parlo italiano, spagnolo e inglese”." },
  { id: "ex-asc-006", type: "mc", level: "A2", topic: "ascolto", prompt: "En el diálogo del médico: ¿qué le duele al paciente?",
    options: ["La garganta y la cabeza", "El estómago", "La espalda", "Una pierna"], answer: 0, explain: "“Ho mal di gola e mi fa male la testa”." },
];

export const EXERCISES_BY_ID: Record<string, Exercise> = Object.fromEntries(EXERCISES.map((e) => [e.id, e]));

export function getExercises(ids: string[]): Exercise[] {
  return ids.map((id) => EXERCISES_BY_ID[id]).filter(Boolean);
}

export function exercisesByLevel(level: string, limit = 12): Exercise[] {
  const pool = EXERCISES.filter((e) => e.level === level && e.type !== "match");
  const seed = pool.length;
  const arr = [...pool].sort((a, b) => ((a.id.length * 31 + seed) % 97) - ((b.id.length * 31 + seed) % 97));
  return arr.slice(0, limit);
}

export function exercisesByTopic(topic: string, limit = 8): Exercise[] {
  return EXERCISES.filter((e) => e.topic === topic).slice(0, limit);
}
