/* ── Letture EXTRA · Paquete v9.11 · Parte 7: 5 cultura ─────────────────
   cult-gelato-31 (A1): il gelato artigianale.
   cult-ferragosto-32 (A2): Ferragosto e le feste italiane.
   cult-calcio-33 (A2): il calcio, passione nazionale.
   cult-teatro-34 (C1): la commedia dell'arte.
   cult-design-35 (C1): il design italiano.
   100% contenido original.                                            */

import type { CefrLevel } from "./types";
import type { Lettura } from "./letture";

/* ═══ CULTURA EXTRA v9.11 ═════════════════════════════════════════════ */

export const CULTURA_EXTRA7: Lettura[] = [
  {
    id: "cult-gelato-31",
    cat: "cultura",
    level: "A1",
    title: "Il gelato artigianale: un piccolo piacere italiano",
    titleEs: "El helado artesanal: un pequeño placer italiano",
    minutes: 2,
    lines: [
      { it: "In Italia il gelato è una cosa seria. Si mangia d'estate, ma anche d'inverno! In molte città italiane la gelateria è aperta tutto l'anno, e la sera è piena di famiglie con i bambini.", es: "En Italia el helado es algo serio. Se come en verano, ¡pero también en invierno! En muchas ciudades italianas la heladería está abierta todo el año, y por la noche está llena de familias con niños." },
      { it: "I gusti classici sono cioccolato, vaniglia, fragola, nocciola, limone e fior di latte. Il pistacchio è molto amato dagli italiani. E tu? Qual è il tuo gusto preferito?", es: "Los sabores clásicos son chocolate, vainilla, fresa, avellana, limón y fior di latte. El pistacho es muy querido por los italianos. ¿Y tú? ¿Cuál es tu sabor preferido?" },
      { it: "In gelateria puoi scegliere il cono o la coppetta. Il cono è croccante, la coppetta è comoda. Poi scegli la misura: piccola, media o grande. E infine la domanda più importante: «Con panna?» La panna è la crema de leche batida, dulce e morbida.", es: "En la heladería puedes elegir el cono o la vasito. El cono es crocante, el vasito es cómodo. Luego eliges el tamaño: pequeño, mediano o grande. Y al final la pregunta más importante: «¿Con crema?» La panna es la crema de leche batida, dulce y suave." },
      { it: "Attenzione: non tutti i gelati sono uguali! Il gelato artigianale è fatto ogni giorno nella gelateria, con latte fresco e frutta vera. Il gelato industriale è fatto in fabbrica, mesi prima, e si compra al supermercato. Come si riconosce il gelato artigianale? Il colore è naturale: il gelato al pistacchio non è verde brillante, è verde-grigio!", es: "Atención: ¡no todos los helados son iguales! El helado artesanal se hace cada día en la heladería, con leche fresca y fruta verdadera. El helado industrial se hace en fábrica, meses antes, y se compra en el supermercado. ¿Cómo se reconoce el helado artesanal? El color es natural: ¡el helado de pistacho no es verde brillante, es verde-gris!" },
      { it: "Un consiglio: cerca la gelateria con la targa «gelateria artigianale» e guarda i prezzi onesti. Poi ordina, assaggia e... buon appetito! Il gelato è un piacere semplice e perfetto della vita italiana.", es: "Un consejo: busca la heladería con el cartel «gelateria artigianale» y mira los precios honestos. Luego pide, prueba y... ¡buen provecho! El helado es un placer simple y perfecto de la vida italiana." },
    ],
    glossary: [
      { it: "il gusto", es: "el sabor" },
      { it: "il cono", es: "el cono" },
      { it: "la coppetta", es: "el vasito" },
      { it: "la panna", es: "la crema de leche batida" },
      { it: "artigianale", es: "artesanal" },
      { it: "assaggiare", es: "probar / degustar" },
    ],
    questions: [
      { q: "¿Cuándo se come helado en Italia?", options: ["Solo d'estate", "D'estate ma anche d'inverno", "Solo a Natale", "Mai"], answer: 1, why: "«Si mangia d'estate, ma anche d'inverno»: la geladería abre todo el año." },
      { q: "¿Cuál es el color natural del helado de pistacho?", options: ["Verde brillante", "Verde-grigio, non brillante", "Rosso", "Blu"], answer: 1, why: "El color natural es verde-gris; el verde brillante es señal de colorantes." },
      { q: "¿Cómo se reconoce el helado artesanal?", options: ["Costa meno", "È fatto ogni giorno nella gelateria con latte fresco e frutta vera", "È verde brillante", "Si compra al supermercato"], answer: 1, why: "Se hace cada día en la heladería con leche fresca y fruta verdadera; el industrial se hace en fábrica." },
      { q: "¿Qué significa la pregunta «Con panna?»", options: ["¿Con chocolate?", "¿Con crema de leche batida?", "¿Con café?", "¿Con fresa?"], answer: 1, why: "La panna es la crema de leche batida, dulce y suave." },
    ],
    discuss: [
      { it: "Qual è il tuo gusto di gelato preferito? Esistono gusti tipici del tuo paese?", es: "¿Cuál es tu sabor de helado preferido? ¿Existen sabores típicos de tu país?" },
      { it: "Nel tuo paese si mangia il gelato d'inverno? Quando?", es: "¿En tu país se come helado en invierno? ¿Cuándo?" },
      { it: "Cono o coppetta? E perché?", es: "¿Cono o vasito? ¿Y por qué?" },
    ],
  },
  {
    id: "cult-ferragosto-32",
    cat: "cultura",
    level: "A2",
    title: "Ferragosto: le città vuote e il mare pieno",
    titleEs: "Ferragosto: las ciudades vacías y el mar lleno",
    minutes: 3,
    lines: [
      { it: "Il 15 agosto in Italia è Ferragosto, e per gli italiani è una festa importantissima. Il nome è antichissimo: viene dalle «Feriae Augusti», le feste dell'imperatore Augusto, duemila anni fa! Era il momento del riposo dopo i lavori agricoli dell'estate. Oggi non ci sono più i campi da sistemare, ma il riposo è rimasto.", es: "El 15 de agosto en Italia es Ferragosto, y para los italianos es una fiesta importantísima. El nombre es antiquísimo: viene de las «Feriae Augusti», las fiestas del emperador Augusto, ¡hace dos mil años! Era el momento del descanso después de los trabajos agrícolas del verano. Hoy ya no hay campos que arreglar, pero el descanso se quedó." },
      { it: "Cosa succede il 15 agosto? Le città si svuotano. Negozi chiusi, uffici chiusi, strade deserte. Dappertutto cartelli con scritto «chiuso per ferie». Gli italiani vanno al mare o in montagna, e le spiagge si riempiono di ombrelloni. Per uno straniero è una sorpresa: «Ma è tutto chiuso?!» Sì, è tutto chiuso. È Ferragosto!", es: "¿Qué pasa el 15 de agosto? Las ciudades se vacían. Tiendas cerradas, oficinas cerradas, calles desiertas. Por todas partes carteles con escrito «cerrado por vacaciones». Los italianos van al mar o a la montaña, y las playas se llenan de sombrillas. Para un extranjero es una sorpresa: «¡¿Pero está todo cerrado?!» Sí, está todo cerrado. ¡Es Ferragosto!" },
      { it: "Il pranzo di Ferragosto è un rito. Spesso si mangia all'aperto, in giardino o in terrazza, con parenti e amici. Il menù classico? Watermelon, pomodori ripieni, pollo freddo... e in molte zone il pranzo finisce con un gelato. Nei piccoli borghi c'è sempre una sagra: la sagra dell'agnello, della porchetta, del pesce, con musica e balli in piazza.", es: "El almuerzo de Ferragosto es un rito. A menudo se come al aire libre, en el jardín o la terraza, con parientes y amigos. ¿El menú clásico? Sandía, tomates rellenos, pollo frío... y en muchas zonas el almuerzo termina con un helado. En los pueblos pequeños siempre hay una sagra: la sagra del cordero, de la porchetta, del pescado, con música y bailes en la plaza." },
      { it: "La sera ci sono feste e fuochi d'artificio in molte città. A Siena, il 16 agosto, c'è addirittura il Palio dell'Assunta: una corsa di cavalli in piazza del Campo, con migliaia di persone e una passione difficile da descrivere. È uno degli eventi più antichi e amati d'Italia.", es: "Por la noche hay fiestas y fuegos artificiales en muchas ciudades. En Siena, el 16 de agosto, hay incluso el Palio dell'Assunta: una carrera de caballos en la piazza del Campo, con miles de personas y una pasión difícil de describir. Es uno de los eventos más antiguos y queridos de Italia." },
      { it: "Ferragosto è solo un esempio del calendario italiano delle feste. Ci sono le feste religiose (Natale, Pasqua, Ferragosto), le feste civili (il 25 aprile, la Liberazione; il 1º maggio, il lavoro; il 2 giugno, la Repubblica) e i ponti: quando una festa cade vicino al weekend, gli italiani «fanno il ponte» e prendono tre o quattro giorni di vacanza insieme!", es: "Ferragosto es solo un ejemplo del calendario italiano de fiestas. Están las fiestas religiosas (Navidad, Pascua, Ferragosto), las fiestas civiles (el 25 de abril, la Liberación; el 1º de mayo, el trabajo; el 2 de junio, la República) y los puentes: cuando una fiesta cae cerca del fin de semana, los italianos «hacen el puente» ¡y toman tres o cuatro días de vacaciones juntos!" },
      { it: "Per uno studente di italiano, Ferragosto è una lezione di cultura (e di imperfetto!): «Da piccolo andavo sempre al mare il 15 agosto». Se capisci Ferragosto, capisci un pezzo dell'anima italiana: il valore del riposo condiviso, del cibo all'aperto, della città che si ferma e riparte.", es: "Para un estudiante de italiano, Ferragosto es una lección de cultura (¡y de imperfecto!): «De pequeño iba siempre al mar el 15 de agosto». Si entiendes Ferragosto, entiendes un pedazo del alma italiana: el valor del descanso compartido, de la comida al aire libre, de la ciudad que se detiene y vuelve a arrancar." },
    ],
    glossary: [
      { it: "le ferie", es: "las vacaciones (de un negocio)" },
      { it: "deserto", es: "desierto / desierto (vacío)" },
      { it: "il rito", es: "el rito" },
      { it: "la sagra", es: "la sagra (fiesta gastronómica del pueblo)" },
      { it: "la porchetta", es: "la porchetta (cerdo asado especiado)" },
      { it: "fare il ponte", es: "hacer el puente (alargar la fiesta)" },
    ],
    questions: [
      { q: "¿De dónde viene el nombre «Ferragosto»?", options: ["Dal nome di un santo", "Dalle «Feriae Augusti», le feste dell'imperatore Augusto", "Dalla parola «agosto» soltanto", "Da un film"], answer: 1, why: "De las Feriae Augusti, las fiestas del emperador Augusto, hace dos mil años." },
      { q: "¿Qué se ve por todas partes el 15 de agosto en las ciudades italianas?", options: ["Code ai musei", "Cartelli «chiuso per ferie»: negozi e uffici chiusi, strade deserte", "Concerti gratuiti", "Nevicate"], answer: 1, why: "Las ciudades se vacían: «chiuso per ferie» por doquier, todos al mar o a la montaña." },
      { q: "¿Qué es una «sagra»?", options: ["Una gara sportiva", "Una festa gastronomica di paese, con musica e balli in piazza", "Un tipo di vacanza", "Una processione religiosa soltanto"], answer: 1, why: "Es la fiesta gastronómica del pueblo: sagra dell'agnello, della porchetta, del pesce, con música y bailes." },
      { q: "¿Qué es el «Palio dell'Assunta»?", options: ["Un concerto a Roma", "La corsa di cavalli del 16 agosto in piazza del Campo, a Siena", "Una gara di nuoto", "Una parata militare"], answer: 1, why: "La carrera de caballos del 16 de agosto en Siena, uno de los eventos más antiguos y queridos." },
      { q: "¿Qué significa «fare il ponte»?", options: ["Costruire un ponte vero", "Prendere 3-4 giorni di vacanza quando una festa cade vicino al weekend", "Andare a pesca", "Tornare a lavorare"], answer: 1, why: "Cuando la fiesta cae cerca del fin de semana, se «alarga» el descanso varios días." },
    ],
    discuss: [
      { it: "Qual è la festa più importante del tuo paese? Come si festeggia?", es: "¿Cuál es la fiesta más importante de tu país? ¿Cómo se celebra?" },
      { it: "«Fare il ponte»: esiste qualcosa di simile nel tuo paese? Ti sembra giusto o sbagliato?", es: "«Hacer el puente»: ¿existe algo parecido en tu país? ¿Te parece justo o malo?" },
      { it: "Immagina il tuo Ferragosto ideale: città, persone, cibo, musica. Racconta.", es: "Imagina tu Ferragosto ideal: ciudad, personas, comida, música. Cuenta." },
    ],
  },
  {
    id: "cult-calcio-33",
    cat: "cultura",
    level: "A2",
    title: "Il calcio: una passione nazionale",
    titleEs: "El fútbol: una pasión nacional",
    minutes: 3,
    lines: [
      { it: "In Italia il calcio non è solo uno sport: è una passione nazionale. Si gioca nei campetti di periferia, si guarda al bar, si commenta in ufficio e in famiglia. Quando gioca la Nazionale, tutta l'Italia si ferma davanti alla televisione — e nelle città, durante la partita, le strade sono così vuote che si sentono i telecronisti dalle finestre aperte.", es: "En Italia el fútbol no es solo un deporte: es una pasión nacional. Se juega en las canchitas de la periferia, se mira en el bar, se comenta en la oficina y en la familia. Cuando juega la Nazionale, toda Italia se detiene frente al televisor —y en las ciudades, durante el partido, las calles están tan vacías que se escuchan los relatores desde las ventanas abiertas." },
      { it: "Il campionato italiano si chiama Serie A. Le squadre più famose sono la Juventus di Torino, il Milan e l'Inter di Milano, il Napoli, la Roma e la Lazio. Alcune partite sono speciali: il derby. Il derby della Madonnina è Milan-Inter, il Derby d'Italia è Juventus-Inter, il derby della capitale è Roma-Lazio. In quelle settimane la città si divide in due.", es: "El campeonato italiano se llama Serie A. Los equipos más famosos son la Juventus de Turín, el Milan y el Inter de Milán, el Nápoles, la Roma y el Lazio. Algunos partidos son especiales: el derbi. El derbi della Madonnina es Milan-Inter, el Derbi de Italia es Juventus-Inter, el derbi de la capital es Roma-Lazio. En esas semanas la ciudad se divide en dos." },
      { it: "La Nazionale italiana — gli «Azzurri», per il colore della maglia — è una delle squadre più forti della storia: ha vinto quattro volte i mondiali (1934, 1938, 1982 e 2006) e due volte gli europei (1968 e 2020). La vittoria del 1982, in Spagna, è leggenda: una squadra criticata da tutti che diventa campione del mondo, con Paolo Rossi che segna tre gol al Brasile. Quella del 2006 è la vendetta dopo lo scandalo del calcio italiano: gli Azzurri vincono in Germania e l'Italia ritrova l'orgoglio.", es: "La Nazionale italiana —los «Azzurri», por el color de la camiseta— es uno de los equipos más fuertes de la historia: ganó cuatro veces el mundial (1934, 1938, 1982 y 2006) y dos veces la Eurocopa (1968 y 2020). La victoria de 1982, en España, es leyenda: un equipo criticado por todos que se vuelve campeón del mundo, con Paolo Rossi que hace tres goles a Brasil. La de 2006 es la revancha después del escándalo del fútbol italiano: los Azzurri ganan en Alemania e Italia recupera el orgullo." },
      { it: "Il calcio è anche lingua. L'italiano usa parole del calcio ogni giorno: «salvare in corner» (evitare un problema all'ultimo momento), «giocare in contropiede» (rispondere in modo inaspettato), «andare in rete» (avere successo). E il lunedì mattina dopo le partite della domenica c'è il «processo del lunedì»: ore di radio e televisione dove tutti — tifosi, giornalisti, barbieri — fanno il processo all'arbitro.", es: "El fútbol también es lengua. El italiano usa palabras del fútbol cada día: «salvare in corner» (evitar un problema en el último momento), «giocare in contropiede» (responder de manera inesperada), «andare in rete» (tener éxito). Y el lunes por la mañana después de los partidos del domingo está el «proceso del lunes»: horas de radio y televisión donde todos —hinchas, periodistas, barberos— le hacen el juicio al árbitro." },
      { it: "Naturalmente, il calcio italiano ha anche i suoi problemi: troppi soldi, qualche episodio di violenza negli stadi del passato, casi di razzismo che ancora oggi guastano le partite. Ma il bilancio resta straordinario: il calcio è il grande collante sociale del paese, l'unico momento in cui l'Italia si sente davvero una squadra. E per uno studente di italiano, guardare una partita con commento originale è una lezione perfetta di lingua viva: passionale, veloce e piena di parole che non trovi sui libri.", es: "Naturalmente, el fútbol italiano también tiene sus problemas: demasiado dinero, algún episodio de violencia en los estadios del pasado, casos de racismo que aún hoy dañan los partidos. Pero el balance sigue siendo extraordinario: el fútbol es el gran pegamento social del país, el único momento en que Italia se siente de verdad un equipo. Y para un estudiante de italiano, mirar un partido con comentario original es una lección perfecta de lengua viva: apasionada, rápida y llena de palabras que no encuentras en los libros." },
    ],
    glossary: [
      { it: "il campionato", es: "el campeonato" },
      { it: "il derby", es: "el derbi (partido entre rivales de la misma ciudad o país)" },
      { it: "il tifoso", es: "el hincha" },
      { it: "la maglia", es: "la camiseta" },
      { it: "il contropiede", es: "el contragolpe" },
      { it: "il collante sociale", es: "el pegamento social" },
    ],
    questions: [
      { q: "¿Cuántos mundiales ha ganado la Nazionale?", options: ["Due", "Tre", "Quattro (1934, 1938, 1982, 2006)", "Cinque"], answer: 2, why: "Cuatro títulos mundiales, más dos Eurocopas (1968 y 2020)." },
      { q: "¿Qué es el «derby della Madonnina»?", options: ["Roma-Lazio", "Milan-Inter", "Juventus-Inter", "Napoli-Roma"], answer: 1, why: "Es el derbi de Milán: Milan contra Inter." },
      { q: "¿Por qué es legendaria la victoria de 1982?", options: ["Perché ha vinto senza giocare", "Una squadra criticata da tutti diventa campione, con Paolo Rossi che segna tre gol al Brasile", "Perché non c'era la finale", "Perché ha vinto il Brasile"], answer: 1, why: "Un equipo criticado por todos se coronó campeón; Rossi hizo tres goles a Brasil." },
      { q: "¿Qué significa «salvare in corner» en la vida diaria?", options: ["Guadagnare molto", "Evitare un problema all'ultimo momento", "Perdere una partita", "Fare un gol"], answer: 1, why: "Es evitar un problema en el último instante: una de las muchas expresiones futbolísticas del italiano." },
      { q: "¿Qué es el «processo del lunedì»?", options: ["Un processo giudiziario", "Ore di radio e TV dove tutti commentano (e processano) l'arbitro e le partite della domenica", "Un allenamento", "Una partita di recupero"], answer: 1, why: "El lunes se comenta todo: hinchas, periodistas y barberos «juzgan» al árbitro y a los equipos." },
    ],
    discuss: [
      { it: "Il calcio o un altro sport? Qual è la passione nazionale del tuo paese?", es: "¿El fútbol u otro deporte? ¿Cuál es la pasión nacional de tu país?" },
      { it: "«Salvare in corner», «giocare in contropiede»: nel tuo paese lo sport dà espressioni alla lingua? Quali?", es: "«Salvar en corner», «jugar al contragolpe»: ¿en tu país el deporte da expresiones a la lengua? ¿Cuáles?" },
      { it: "Il calcio unisce o divide? Racconta un esempio della tua esperienza.", es: "¿El fútbol une o divide? Cuenta un ejemplo de tu experiencia." },
    ],
  },
  {
    id: "cult-teatro-34",
    cat: "cultura",
    level: "C1",
    title: "La commedia dell'arte: le maschere che ancora ridono",
    titleEs: "La commedia dell'arte: las máscaras que todavía hacen reír",
    minutes: 6,
    lines: [
      { it: "Nel Cinquecento, mentre i letterati scrivevano commedie erudite destinate alle corti, nelle piazze e sulle tavole dei palchi itineranti nasceva un teatro completamente diverso: la commedia dell'arte. «Arte» qui non significa «arte» in senso moderno, ma «mestiere»: era il teatro dei professionisti, attori pagati che vivevano di palcoscenico, organizzati in compagnie stabili — con capocomico, rubriche di ruoli e perfino contratti verbali — decenni prima che l'Europa scoprisse che recitare poteva essere una professione.", es: "En el Cinquecento, mientras los letrados escribían comedias eruditas destinadas a las cortes, en las plazas y sobre los tablados de los palcos itinerantes nacía un teatro completamente distinto: la commedia dell'arte. «Arte» aquí no significa «arte» en sentido moderno, sino «oficio»: era el teatro de los profesionales, actores pagados que vivían del escenario, organizados en compañías estables —con capocómico, repertorios de roles e incluso contratos verbales— décadas antes de que Europa descubriera que actuar podía ser una profesión." },
      { it: "Il segreto di questo teatro era l'improvvisazione, ma un'improvvisazione paradossalmente disciplinata. Gli attori non recitavano un testo scritto: lavoravano su un canovaccio, una scaletta di scene con la traccia degli eventi, e riempivano lo spazio con lazzi — battute, gesti, acrobazie, scherzi fissi del repertorio — e con dialoghi inventati lì per lì. Per farlo senza naufragare serviva una grammatica condivisa: ecco allora le maschere, personaggi fissi riconoscibili al primo sguardo, che il pubblico conosceva già prima che lo spettacolo cominciasse.", es: "El secreto de este teatro era la improvisación, pero una improvisación paradójicamente disciplinada. Los actores no recitaban un texto escrito: trabajaban sobre un canovaccio, una escaleta de escenas con la traza de los acontecimientos, y llenaban el espacio con lazzi —réplicas, gestos, acrobacias, bromas fijas del repertorio— y con diálogos inventados en el momento. Para hacerlo sin naufragar hacía falta una gramática compartida: he ahí las máscaras, personajes fijos reconocibles a primera vista, que el público conocía ya antes de que el espectáculo comenzara." },
      { it: "Arlecchino è la maschera più famosa: servo bergamasco, affamato e furbo, vestito di toppe multicolori, acrobatico e vigliacco, capace in un istante di passare dall'ingenuità alla malizia. Il suo padrone, o antagonista, è Pantalone: vecchio mercante veneziano, avaro, geloso, in continua guerra con il denaro che pure adora. Accanto a loro, il Dottore — bolognese, dottorato di Ballanella, come dice la tradizione — parla dotto e dice scemenze, mescolando latino maccheronico e sentenze a rovescio. Brighella, servo astuto e cinico, manovra tutti; il Capitano, spagnolo vanaglorioso, si vanta di battaglie mai combattute e sviene davanti a una spada sguainata. E sopra le maschere, gli Innamorati: giovani senza maschera, eleganti, che parlano bene — gli unici, insieme ai servi scelti come Arlecchino, a poter usare la lingua colta e i versi.", es: "Arlequín es la máscara más famosa: siervo bergamasco, hambriento y astuto, vestido de parches multicolores, acrobático y cobarde, capaz en un instante de pasar de la ingenuidad a la malicia. Su amo, o antagonista, es Pantalone: viejo mercader veneciano, avaro, celoso, en guerra continua con el dinero que sin embargo adora. Junto a ellos, el Dottore —boloñés, doctorado de Ballanella, como dice la tradición— habla culto y dice tonterías, mezclando latín macarrónico y sentencias al revés. Brighella, siervo astuto y cínico, maneja a todos; el Capitano, español vanaglorioso, se jacta de batallas nunca libradas y se desmaya frente a una espada desenvainada. Y sobre las máscaras, los Enamorados: jóvenes sin máscara, elegantes, que hablan bien —los únicos, junto con los siervos elegidos como Arlequín, en poder usar la lengua culta y los versos." },
      { it: "Un aspetto spesso dimenticato: le attrici. La commedia dell'arte porta sul palcoscenico professionista le prime donne della storia moderna del teatro occidentale — figure come Vincenza Armani o Isabella Andreini, star internazionali ammirate dai duchi — in un'epoca in cui, in Inghilterra, i ruoli femminili erano ancora recitati da ragazzi. Isabella Andreini, poetessa oltre che attrice, trasformò la servetta Colombina in un personaggio di intelligenza e profondità tali che i letterati scrivevano per lei.", es: "Un aspecto a menudo olvidado: las actrices. La commedia dell'arte lleva al escenario profesional a las primeras mujeres de la historia moderna del teatro occidental —figuras como Vincenza Armani o Isabella Andreini, estrellas internacionales admiradas por los duques— en una época en que, en Inglaterra, los roles femeninos eran aún representados por muchachos. Isabella Andreini, poeta además de actriz, transformó a la sirvienta Colombina en un personaje de tal inteligencia y profundidad que los letrados escribían para ella." },
      { it: "Per due secoli la commedia dell'arte conquista l'Europa: troupes italiane giocano a Parigi come a Madrid, influenzano Molière e Shakespeare, esportano maschere e lazzi ovunque. Poi, a metà Settecento, il pubblico cambia gusto: si vuole il testo scritto, il carattere psicologico, la commedia borghese. È Carlo Goldoni, veneziano, a scrivere la riforma: nelle sue commedie la maschera lascia il posto alla persona — il servitore Arlecchino diventa «servitore di due padroni» con nome, fame e cuore — e l'improvvisazione cede alla scrittura. Era la fine? Sembra di no.", es: "Durante dos siglos la commedia dell'arte conquista Europa: troupe italianas actúan en París como en Madrid, influyen en Molière y Shakespeare, exportan máscaras y lazzi a todas partes. Luego, a mediados del Settecento, el público cambia de gusto: se quiere el texto escrito, el carácter psicológico, la comedia burguesa. Es Carlo Goldoni, veneciano, quien escribe la reforma: en sus comedias la máscara deja paso a la persona —el siervo Arlequín se vuelve «servidor de dos amos» con nombre, hambre y corazón— y la improvisación cede ante la escritura. ¿Era el fin? Parece que no." },
      { it: "Le maschere, infatti, non sono morte: sono solo cambiate di pelle. Pulcinella è diventato Punch in Inghilterra; il clown bianco del circo parla ancora la lingua di Pierrot; il cinema comico — da Chaplin a Totò, napoletano, «principe della risata» che portava il corpo di Pulcinella dentro una giacca stinta — è figlio diretto dei lazzi. Nel Novecento, poi, il grande regista Giorgio Strehler ha riportato in vita Arlecchino con «Arlecchino servitore di due padroni» (1947), spettacolo rappresentato in tutto il mondo per mezzo secolo. E l'italiano corrente conserva l'eredità nel lessico: «fare la maschera» significa recitare una parte fissa, e si dice di qualcuno che «è una maschera» quando recita se stesso senza più sorprese. Forse, in fondo, non abbiamo mai smesso di recitare la commedia: abbiamo solo tolto il costume.", es: "Las máscaras, en efecto, no han muerto: solo han cambiado de piel. Pulcinella se volvió Punch en Inglaterra; el payaso blanco del circo habla todavía la lengua de Pierrot; el cine cómico —de Chaplin a Totò, napolitano, «príncipe de la risa» que llevaba el cuerpo de Pulcinella dentro de una chaqueta descolorida— es hijo directo de los lazzi. En el Novecento, además, el gran director Giorgio Strehler devolvió a la vida a Arlequín con «Arlecchino servitore di due padroni» (1947), espectáculo representado en todo el mundo durante medio siglo. Y el italiano corriente conserva la herencia en el léxico: «fare la maschera» significa representar un papel fijo, y se dice de alguien que «è una maschera» cuando se representa a sí mismo sin más sorpresas. Quizá, en el fondo, nunca dejamos de representar la comedia: solo nos quitamos el disfraz." },
    ],
    glossary: [
      { it: "il mestiere", es: "el oficio" },
      { it: "il canovaccio", es: "el canovaccio (escaleta de improvisación)" },
      { it: "il lazzo", es: "el lazzo (broma o gag fijo)" },
      { it: "la toppa", es: "el parche" },
      { it: "vanaglorioso", es: "vanaglorioso / fanfarrón" },
      { it: "maccheronico", es: "macarrónico (latín deformado)" },
      { it: "la troupe", es: "la troupe / compañía" },
    ],
    questions: [
      { q: "¿Qué significa «arte» en «commedia dell'arte»?", options: ["Arte en sentido moderno", "Mestiere: il teatro dei professionisti pagati, organizzati in compagnie stabili", "Un genere pittorico", "Un'associazione culturale"], answer: 1, why: "«Arte» = oficio: actores profesionales con capocómico y contratos, décadas antes de que actuar fuera reconocido como profesión." },
      { q: "¿Qué era el «canovaccio»?", options: ["Il testo completo da memorizzare", "Una scaletta di scene con la traccia degli eventi, che gli attori riempivano improvisando", "Un contratto per gli attori", "Un tipo di maschera"], answer: 1, why: "Era la escaleta con la traza de los acontecimientos: los actores la llenaban con lazzi y diálogos inventados en el momento." },
      { q: "¿Cuál de estos es el rasgo del Dottore?", options: ["È un vecchio avaro veneziano", "Parla dotto e dice scemenze, mescolando latino maccheronico", "È un capitano coraggioso", "È un servo affamato"], answer: 1, why: "El Dottore boloñés habla culto y dice tonterías con latín macarrónico; Pantalone es el viejo avaro." },
      { q: "¿Por qué es importante la presencia de las attrici?", options: ["Erano solo comparse", "Portarono sul palcoscenico professionista le prime donne del teatro occidentale moderno, come Isabella Andreini", "Recitavano solo a corte", "Non esistevano"], answer: 1, why: "Estrellas como Vincenza Armani o Isabella Andreini fueron las primeras mujeres profesionales del teatro occidental, admiradas por los duques." },
      { q: "¿En qué consistió la reforma de Goldoni?", options: ["Eliminò il teatro", "La maschera lascia il posto alla persona e l'improvvisazione cede alla scrittura", "Vietò l'uso della lingua italiana", "Portò il teatro solo a Venezia"], answer: 1, why: "En sus comedias, personajes con nombre y psicología (Arlequín servidor de dos amos) sustituyen a las máscaras fijas: texto escrito." },
      { q: "¿Qué hizo Giorgio Strehler en 1947?", options: ["Scrisse la prima commedia dell'arte", "Riportò in vita Arlecchino con «Arlecchino servitore di due padroni», rappresentato in tutto il mondo", "Chiuse tutti i teatri", "Inventò il circo"], answer: 1, why: "Revivió a Arlequín con el célebre espectáculo, representado mundialmente durante medio siglo." },
    ],
    discuss: [
      { it: "«Siamo tutti maschere»: quanto recitiamo, nella vita quotidiana? Quando togliamo davvero il costume?", es: "«Somos todos máscaras»: ¿cuánto actuamos en la vida diaria? ¿Cuándo nos quitamos de verdad el disfraz?" },
      { it: "L'improvvisazione disciplinata del canovaccio: ti è mai capitato di «improvvisare su struttura» (musica, lavoro, sport)? Racconta.", es: "La improvisación disciplinada del canovaccio: ¿te ha pasado de «improvisar sobre estructura» (música, trabajo, deporte)? Cuenta." },
      { it: "Nel tuo paese esiste un teatro comico popolare con personaggi fissi? Confrontalo con le maschere italiane.", es: "¿En tu país existe un teatro cómico popular con personajes fijos? Compáralo con las máscaras italianas." },
    ],
  },
  {
    id: "cult-design-35",
    cat: "cultura",
    level: "C1",
    title: "Il design italiano: la bellezza degli oggetti quotidiani",
    titleEs: "El diseño italiano: la belleza de los objetos cotidianos",
    minutes: 6,
    lines: [
      { it: "Se un abitante del 1950 potesse passeggiare in un appartamento italiano di oggi, riconoscerebbe quasi tutto: la moka sul fornello, la sedia in cucina, la lampada del salotto, lo scooter parcheggiato sotto casa. Non perché l'Italia sia ferma, ma perché certi oggetti italiani del dopoguerra sono diventati definitivi — talmente riusciti che rifarli sarebbe peggio che lasciarli com'è. Questo è, in definitiva, il design italiano: non il lusso da museo, ma la cura della forma applicata alle cose che tutti usano, tutti i giorni.", es: "Si un habitante de 1950 pudiera pasear por un apartamento italiano de hoy, reconocería casi todo: la moka en la cocina, la silla en la cocina, la lámpara del salón, el scooter estacionado abajo. No porque Italia esté detenida, sino porque ciertos objetos italianos de la posguerra se han vuelto definitivos —tan logrados que rehacerlos sería peor que dejarlos como están. Esto es, en definitiva, el diseño italiano: no el lujo de museo, sino el cuidado de la forma aplicado a las cosas que todos usan, todos los días." },
      { it: "Le origini sono legate alla ricostruzione. Negli anni Cinquanta l'Italia esce dalla guerra povera ma con un patrimonio unico: officine meccaniche che sanno lavorare bene, artigiani di tradizione secolare — falegnami, tappezzieri, vetrai — e una cultura della forma che risale al Rinascimento. La Triennale di Milano, grande esposizione periodica, diventa il laboratorio dove questa miscela si mostra al mondo; i committenti sono piccole imprese, spesso a conduzione familiare, disposte a rischiare: Cassina, Kartell, Olivetti, Alessi.", es: "Los orígenes están ligados a la reconstrucción. En los años Cincuenta Italia sale de la guerra pobre pero con un patrimonio único: talleres mecánicos que saben trabajar bien, artesanos de tradición secular —carpinteros, tapiceros, vidrieros— y una cultura de la forma que se remonta al Renacimiento. La Trienal de Milán, gran exposición periódica, se vuelve el laboratorio donde esta mezcla se muestra al mundo; los comitentes son pequeñas empresas, a menudo de gestión familiar, dispuestas a arriesgar: Cassina, Kartell, Olivetti, Alessi." },
      { it: "Due date bastano a raccontare il decennio magico. 1946: la Vespa, disegnata dall'ingegnere aeronautico Corradino D'Ascanio per conto di Enrico Piaggio — un scooter che si guida da seduti, col cambio sul manubrio, senza sporcare i pantaloni di olio, pensato «per tutti» eppure elegante. 1957: la Fiat 500 di Dante Giacosa, l'auto che motorizza l'Italia — dieci chili di lamiera e un progetto talmente pulito che, ancora oggi, nelle aule di design si studia come esempio di perfezione funzionale. Vespa e Cinquecento non sono mezzi di trasporto: sono dichiarazioni. Dicono che il paese uscito dalla guerra può permettersi il bello, anche con pochi soldi.", es: "Dos fechas bastan para contar la década mágica. 1946: la Vespa, dibujada por el ingeniero aeronáutico Corradino D'Ascanio por encargo de Enrico Piaggio —un scooter que se conduce sentado, con el cambio en el manubrio, sin ensuciarse los pantalones de aceite, pensado «para todos» y sin embargo elegante—. 1957: el Fiat 500 de Dante Giacosa, el auto que motoriza a Italia —diez kilos de chapa y un proyecto tan limpio que todavía hoy, en las aulas de diseño, se estudia como ejemplo de perfección funcional—. Vespa y Cinquecento no son medios de transporte: son declaraciones. Dicen que el país salido de la guerra puede permitirse lo bello, aun con poco dinero." },
      { it: "Gli anni Sessanta e Settanta portano il design italiano nelle case del mondo con gli oggetti-icona. Achille Castiglioni firma la lampada Arco (1962): una mezzaluna di marmo e un arco d'acciaio che porta la luce al centro della stanza senza bucare il soffitto — «un lampadario da terra», diceva lui. Achille e suo fratello Pier Giacomo firmano lo sgabello Sella, con un sellino da bicicletta: «quando telefono, mi muovo, e il piede mi serve da appoggio». Richard Sapper, tedesco d'origine e milanese d'adozione, disegna per Alessi la caffettiera 9090 (1979) con il beccuccio che si chiude a baionetta — la moka elegante che sta nelle raccolte permanenti del MoMA di New York. Alessandro Mendini, anni dopo, decora una poltrona vittoriana a pennellate di colore e la chiama Proust: un gesto che rompe il divieto di ornamento del funzionalismo e ridefinisce il mestiere.", es: "Los años Sesenta y Setenta llevan el diseño italiano a las casas del mundo con los objetos-icono. Achille Castiglioni firma la lámpara Arco (1962): una media luna de mármol y un arco de acero que lleva la luz al centro de la habitación sin perforar el techo —«una lámpara de techo desde el suelo», decía él—. Achille y su hermano Pier Giacomo firman el taburete Sella, con un asiento de bicicleta: «cuando hablo por teléfono, me muevo, y el pie me sirve de apoyo». Richard Sapper, alemán de origen y milanés de adopción, diseña para Alessi la cafetera 9090 (1979) con el pico que se cierra a bayoneta —la moka elegante que está en las colecciones permanentes del MoMA de Nueva York—. Alessandro Mendini, años después, decora un sillón victoriano con pinceladas de color y lo llama Proust: un gesto que rompe la prohibición de ornamento del funcionalismo y redefine el oficio." },
      { it: "C'è un metodo, dietro questi oggetti, e non è soltanto estetica. Gli italiani lo chiamano, a volte, «umanesimo del progetto»: la convinzione che un oggetto si giudica dall'uso reale — come sta in mano, come invecchia, che rapporti crea tra le persone — prima che dalla forma. Da qui l'attenzione maniacale al dettaglio, l'ossessione per il materiale giusto e, insieme, una certa ironia: il design italiano non si prende mai troppo sul serio, e forse è proprio questa leggerezza la sua firma. Il risultato è che, mentre altri paesi producevano macchine migliori o più economiche, l'Italia produceva macchine che la gente desiderava — e il desiderio, alla lunga, si è rivelato un ottimo affare.", es: "Hay un método, detrás de estos objetos, y no es solamente estética. Los italianos lo llaman, a veces, «humanismo del proyecto»: la convicción de que un objeto se juzga por el uso real —cómo está en la mano, cómo envejece, qué relaciones crea entre las personas— antes que por la forma. De ahí la atención maníaca al detalle, la obsesión por el material justo y, a la vez, cierta ironía: el diseño italiano nunca se toma demasiado en serio, y quizá es justamente esa ligereza su firma. El resultado es que, mientras otros países producían máquinas mejores o más económicas, Italia producía máquinas que la gente deseaba —y el deseo, a la larga, se reveló un excelente negocio." },
      { it: "Oggi Milano è considerata una delle capitali mondiali del design: ogni aprile, il Salone del Mobile (nato nel 1961) e il Fuorisalone — gli eventi sparsi in tutta la città, dai showrooms ai cortili — trasformano Milano in una gigantesca vetrina frequentata da centinaia di migliaia di visitatori. E il design italiano ha cambiato fronti: dal progetto dell'oggetto al progetto digitale e dei servizi, dalla bellezza alla sostenibilità — cosa significa, oggi, «oggetto ben fatto» in un pianeta a risorse contate? La domanda è aperta, ma se c'è una cosa che cinquant'anni di successi italiani insegnano è questa: la bellezza non è un ornamento del prodotto. È il prodotto.", es: "Hoy Milán es considerada una de las capitales mundiales del diseño: cada abril, el Salón del Móvil (nacido en 1961) y el Fuorisalone —los eventos repartidos por toda la ciudad, de los showrooms a los patios— transforman Milán en un gigantesco escaparate frecuentado por cientos de miles de visitantes. Y el diseño italiano ha cambiado de frentes: del proyecto del objeto al proyecto digital y de los servicios, de la belleza a la sostenibilidad —¿qué significa, hoy, «objeto bien hecho» en un planeta de recursos contados? La pregunta está abierta, pero si hay algo que cincuenta años de éxitos italianos enseñan es esto: la belleza no es un ornamento del producto. Es el producto." },
    ],
    glossary: [
      { it: "il fornello", es: "la hornilla / la cocina" },
      { it: "riuscito", es: "logrado / conseguido" },
      { it: "il committente", es: "el comitente / cliente que encarga" },
      { it: "a conduzione familiare", es: "de gestión familiar" },
      { it: "il beccuccio", es: "el pico / vertedor" },
      { it: "la poltrona", es: "el sillón" },
      { it: "contato (a risorse contate)", es: "contado (de recursos contados)" },
    ],
    questions: [
      { q: "¿Qué es, en esencia, el diseño italiano según el texto?", options: ["Il lusso da museo", "La cura della forma applicata alle cose che tutti usano ogni giorno", "Solo automobili", "Una moda recente"], answer: 1, why: "«Non il lusso da museo, ma la cura della forma applicata alle cose che tutti usano, tutti i giorni»." },
      { q: "¿Quién diseñó la Vespa y en qué año?", options: ["Dante Giacosa, 1957", "Corradino D'Ascanio, 1946", "Achille Castiglioni, 1962", "Enrico Piaggio, 1950"], answer: 1, why: "El ingeniero aeronáutico Corradino D'Ascanio la dibujó en 1946 para Enrico Piaggio." },
      { q: "¿Qué problema resuelve la lámpara Arco de Castiglioni?", options: ["Risparmia energia", "Porta la luce al centro della stanza senza bucare il soffitto: «un lampadario da terra»", "Si piega in valigia", "Cambia colore"], answer: 1, why: "Una media luna de mármol y un arco de acero: luz central sin perforar el techo." },
      { q: "¿Qué es el «umanesimo del progetto»?", options: ["Una corrente pittorica", "Un oggetto si giudica dall'uso reale — come sta in mano, come invecchia — prima che dalla forma", "Un partito politico", "Un tipo di materiale"], answer: 1, why: "La convicción de que el objeto se juzga por el uso real y las relaciones que crea, antes que por la forma." },
      { q: "¿Qué son el Salone del Mobile y el Fuorisalone?", options: ["Due musei", "La fiera di aprile a Milano e gli eventi sparsi in tutta la città che la trasformano in una gigantesca vetrina", "Due fabbriche di auto", "Due riviste"], answer: 1, why: "El Salón (1961) y los eventos del Fuorisalone convierten Milán cada abril en un escaparate mundial." },
      { q: "¿Qué lección final dejan cincuenta años de diseño italiano?", options: ["Il design costa troppo", "La bellezza non è un ornamento del prodotto: è il prodotto", "Basta copiare", "Servono più ornamenti"], answer: 1, why: "«La bellezza non è un ornamento del prodotto. È il prodotto.»" },
    ],
    discuss: [
      { it: "Qual è l'oggetto italiano che possiedi (o vorresti possedere)? Racconta la sua forma e il suo uso.", es: "¿Cuál es el objeto italiano que tienes (o te gustaría tener)? Cuenta su forma y su uso." },
      { it: "«La bellezza è il prodotto»: sei d'accordo? Vale anche per gli oggetti digitali (app, siti web)?", es: "«La belleza es el producto»: ¿estás de acuerdo? ¿Vale también para los objetos digitales (apps, sitios web)?" },
      { it: "Nel tuo paese esiste un «design nazionale» riconoscibile? Quali oggetti lo rappresentano?", es: "¿En tu país existe un «diseño nacional» reconocible? ¿Qué objetos lo representan?" },
    ],
  },
];
