/* ── Letture EXTRA · Paquete v9.10 · Parte 4: 2 cultura ───────────────
   cult-dante-29 (C1): Dante e la Divina Commedia.
   cult-ferrante-30 (C2): Elena Ferrante e la Napoli letteraria.
   100% contenido original.                                            */

import type { CefrLevel } from "./types";
import type { Lettura } from "./letture";

/* ═══ CULTURA NUOVE ══════════════════════════════════════════════════ */

export const CULTURA_EXTRA: Lettura[] = [
  {
    id: "cult-dante-29",
    cat: "cultura",
    level: "C1",
    title: "Dante e la Divina Commedia: un viaggio nell'aldilà",
    titleEs: "Dante y la Divina Comedia: un viaje al más allá",
    minutes: 6,
    lines: [
      { it: "«Nel mezzo del cammin di nostra vita mi ritrovai per una selva oscura, ché la diritta via era smarrita». Con questi versi comincia il poema più famoso della lingua italiana. Lo scrive, all'inizio del Trecento, un esule fiorentino di mezza età, povero e amareggiato, che si chiama Dante Alighieri. Non poteva sapere che quel viaggio immaginario nell'aldilà sarebbe diventato il fondamento di una letteratura intera.", es: "«A mitad del camino de nuestra vida me encontré en una selva oscura, porque la vía recta estaba perdida». Con estos versos comienza el poema más famoso de la lengua italiana. Lo escribe, a comienzos del Trecento, un exiliado florentino de mediana edad, pobre y amargado, que se llama Dante Alighieri. No podía saber que aquel viaje imaginario al más allá se convertiría en el fundamento de toda una literatura." },
      { it: "La vita di Dante era stata segnata proprio dall'esilio. Nato nel 1265 in una Firenze ricca ma lacerata dalle lotte tra fazioni — i guelfi bianchi e i guelfi neri — si era trovato, come altri cittadini, implicato nella politica. Nel 1302, quando la fazione avversaria prese il potere, fu condannato all'esilio con l'accusa di baratteria, cioè di corruzione. Se fosse rientrato in città, rischiava di essere bruciato vivo. Non rivide mai più Firenze.", es: "La vida de Dante había estado marcada justamente por el exilio. Nacido en 1265 en una Florencia rica pero desgarrada por las luchas entre facciones —los güelfos blancos y los güelfos negros—, se había visto, como otros ciudadanos, implicado en la política. En 1302, cuando la facción adversaria tomó el poder, fue condenado al exilio con la acusación de barattería, es decir, de corrupción. Si hubiera regresado a la ciudad, arriesgaba ser quemado vivo. Nunca volvió a ver Florencia." },
      { it: "Fu proprio nell'esilio che maturò l'opera monumentale. La «Commedia» — l'aggettivo «divina» fu aggiunto più tardi, per ammirazione — racconta un viaggio di sette giorni attraverso i tre regni dell'oltretomba: l'Inferno, con i dannati puniti secondo la gravità dei loro peccati; il Purgatorio, una montagna dove le anime si purificano; e il Paradiso, nove cieli concentrici fino alla visione di Dio. La guida dei primi due regni è Virgilio, il poeta latino che Dante considerava il suo maestro; nel Paradiso subentra Beatrice, la donna che Dante aveva amato da giovane e che era morta presto.", es: "Fue justamente en el exilio donde maduró la obra monumental. La «Comedia» —el adjetivo «divina» se añadió más tarde, por admiración— cuenta un viaje de siete días a través de los tres reinos del más allá: el Infierno, con los condenados castigados según la gravedad de sus pecados; el Purgatorio, una montaña donde las almas se purifican; y el Paraíso, nueve cielos concéntricos hasta la visión de Dios. La guía de los dos primeros reinos es Virgilio, el poeta latino que Dante consideraba su maestro; en el Paraíso entra Beatriz, la mujer que Dante había amado de joven y que había muerto temprano." },
      { it: "La struttura è rigorosa, quasi matematica: cento canti, scritti in terzine di endecasillabi con uno schema di rime inventato da Dante stesso. Ma dentro questa architettura perfetta vive un mondo sorprendentemente moderno. Nell'Inferno, infatti, Dante incontra personaggi di ogni tipo: papi corrotti, politici bugiardi, mercanti avidi, ma anche amici, nemici personali, poeti contemporanei. Li tratta non come simboli ma come persone reali, con le loro storie, le loro scuse e le loro dannazioni. È come se l'intera società del suo tempo passasse in rassegna davanti al tribunale dell'aldilà.", es: "La estructura es rigurosa, casi matemática: cien cantos, escritos en tercetos de endecasílabos con un esquema de rimas inventado por el propio Dante. Pero dentro de esta arquitectura perfecta vive un mundo sorprendentemente moderno. En el Infierno, de hecho, Dante se encuentra con personajes de todo tipo: papas corruptos, políticos mentirosos, mercaderes avaros, pero también amigos, enemigos personales, poetas contemporáneos. Los trata no como símbolos sino como personas reales, con sus historias, sus excusas y sus condenas. Es como si toda la sociedad de su tiempo desfilara ante el tribunal del más allá." },
      { it: "La rivoluzione più grande, però, è la lingua. Nel Medioevo i testi seri si scrivevano in latino; le lingue parlate, i «volgari», erano considerate adatte solo alla vita quotidiana. Dante scelse il volgare fiorentino per un poema universale, e con quella scelta fondò di fatto la letteratura italiana. Ancora oggi, sette secoli dopo, gli italiani capiscono (con un po' di fatica) i suoi versi: pochi popoli possono leggere la propria letteratura fondativa nella lingua originale, senza traduzione.", es: "La revolución más grande, sin embargo, es la lengua. En la Edad Media los textos serios se escribían en latín; las lenguas habladas, los «vulgares», se consideraban aptas solo para la vida cotidiana. Dante eligió el vulgar florentino para un poema universal, y con esa elección fundó de hecho la literatura italiana. Todavía hoy, siete siglos después, los italianos entienden (con algo de esfuerzo) sus versos: pocos pueblos pueden leer su literatura fundacional en la lengua original, sin traducción." },
      { it: "Il 25 marzo, data in cui secondo la tradizione inizia il viaggio dantesco, è oggi la «Dantedì», la giornata nazionale dedicata al padre della lingua. E ogni anno, in quel giorno, studenti e lettori italiani — e ormai anche stranieri — rileggono ad alta voce i versi della selva oscura. Non male per un esilio che non volle mai tornare a casa: la sua vendetta più bella è che Firenze, oggi, si vanta di lui senza pudore.", es: "El 25 de marzo, fecha en que según la tradición comienza el viaje dantesco, es hoy el «Dantedì», la jornada nacional dedicada al padre de la lengua. Y cada año, ese día, estudiantes y lectores italianos —y ya también extranjeros— releen en voz alta los versos de la selva oscura. Nada mal para un exiliado que nunca quiso volver a casa: su venganza más hermosa es que Florencia, hoy, se jacta de él sin pudor." },
    ],
    glossary: [
      { it: "la selva oscura", es: "la selva oscura (símbolo del extravío)" },
      { it: "la baratteria", es: "la baratería (corrupción en el cargo)" },
      { it: "la terzina di endecasillabi", es: "terceto de endecasílabos (estrofa dantesca)" },
      { it: "il volgare", es: "la lengua vulgar (frente al latín)" },
      { it: "l'oltretomba", es: "el más allá" },
    ],
    questions: [
      { q: "¿Por qué fue condenado Dante al exilio en 1302?", options: ["Per eresia", "Con l'accusa di baratteria, cioè corruzione, quando la fazione avversaria prese il potere", "Per aver scritto la Commedia", "Per tradimento militare"], answer: 1, why: "Con la acusación de barattería (corrupción); si hubiera vuelto a Florencia arriesgaba ser quemado vivo." },
      { q: "¿Quiénes guían a Dante en su viaje?", options: ["Solo Beatrice", "Virgilio nei primi due regni, poi Beatrice in Paradiso", "Solo Virgilio", "San Pietro"], answer: 1, why: "Virgilio guía el Infierno y el Purgatorio; Beatriz lo acompaña en el Paraíso." },
      { q: "¿Cuántos cantos tiene el poema y en qué verso está escrito?", options: ["50 canti in ottava rima", "100 canti in terzine di endecasillabi", "120 canti in sonetti", "34 canti in versi liberi"], answer: 1, why: "Cien cantos en tercetos de endecasílabos, con un esquema de rimas inventado por Dante." },
      { q: "¿Cuál fue la revolución lingüística de la Comedia?", options: ["La scrisse in latino classico", "Usò il volgare fiorentino per un poema universale, fondando la letteratura italiana", "Inventò l'alfabeto", "La scrisse in francese"], answer: 1, why: "Los textos serios se escribían en latín; Dante eligió el vulgar florentino y fundó de hecho la literatura italiana." },
      { q: "¿Qué se celebra el «Dantedì»?", options: ["La nascita di Dante", "Il 25 marzo, data in cui secondo la tradizione inizia il viaggio dantesco", "La caduta di Firenze", "La pubblicazione del poema"], answer: 1, why: "Es la jornada nacional dedicada a Dante, cada 25 de marzo, aniversario del inicio del viaje." },
    ],
    discuss: [
      { it: "«Nel mezzo del cammin di nostra vita»: perché, secondo te, questa immagine parla ancora ai lettori di oggi?", es: "«A mitad del camino de nuestra vida»: ¿por qué, según tú, esta imagen sigue hablando a los lectores de hoy?" },
      { it: "Nella tua lingua madre esiste un'opera fondativa, antica ma ancora leggibile? Raccontala.", es: "¿En tu lengua materna existe una obra fundacional, antigua pero aún legible? Cuéntala." },
      { it: "Dante mette all'inferno anche papi e politici del suo tempo: un poeta può fare politica con la poesia? Con che risultati?", es: "Dante manda al infierno también a papas y políticos de su época: ¿puede un poeta hacer política con la poesía? ¿Con qué resultados?" },
    ],
  },
  {
    id: "cult-ferrante-30",
    cat: "cultura",
    level: "C2",
    title: "Elena Ferrante e la Napoli letteraria",
    titleEs: "Elena Ferrante y la Nápoles literaria",
    minutes: 7,
    lines: [
      { it: "Nessuno l'ha mai vista. Nessuno sa con certezza chi sia. Eppure, da vent'anni, è una delle scrittrici più lette e discusse del pianeta. «Elena Ferrante» è probabilmente uno pseudonimo, e la persona che si nasconde dietro quel nome ha dichiarato, attraverso l'editore, che i libri contano una volta scritti: «Credo che i libri, una volta scritti, non hanno bisogno dei loro autori». Una posizione radicale, in un'epoca in cui gli scrittori vivono di presentazioni, selfie e social network.", es: "Nadie la ha visto nunca. Nadie sabe con certeza quién es. Y sin embargo, desde hace veinte años, es una de las escritoras más leídas y discutidas del planeta. «Elena Ferrante» es probablemente un seudónimo, y la persona que se esconde tras ese nombre ha declarado, a través del editor, que los libros, una vez escritos, no necesitan a sus autores: «Creo que los libros, una vez escritos, no necesitan a sus autores». Una postura radical, en una época en que los escritores viven de presentaciones, selfies y redes sociales." },
      { it: "La fortuna mondiale arriva con la quadrilogia «L'amica geniale», quattro romanzi pubblicati tra il 2011 e il 2014 e venduti in decine di milioni di copie. La storia copre mezzo secolo, dagli anni Cinquanta a oggi, e segue due bambine di un rione popolare di Napoli: Elena, detta Lenù, che studia e si allontana dal quartiere, e Raffaella, detta Lila, brillantissima ma costretta a lasciare la scuola. La loro amicizia — competitiva, appassionata, a volte crudele — è il vero motore dell'opera: una coppia di donne che si specchia e si misura per tutta la vita.", es: "La fortuna mundial llega con la tetralogía «La amiga genial», cuatro novelas publicadas entre 2011 y 2014 y vendidas en decenas de millones de ejemplares. La historia abarca medio siglo, de los años cincuenta a hoy, y sigue a dos niñas de un barrio popular de Nápoles: Elena, llamada Lenù, que estudia y se aleja del barrio, y Raffaella, llamada Lila, brillantísima pero obligada a dejar la escuela. Su amistad —competitiva, apasionada, a veces cruel— es el verdadero motor de la obra: una pareja de mujeres que se espeja y se mide durante toda la vida." },
      { it: "Il quartiere dei romanzi è un personaggio a sé. Ferrante lo descrive con una crudezza che ha deluso alcuni lettori napoletani — troppo sporco, troppo violento, dicono — ma anche con una precisione antropologica che pochi hanno eguagliato: le case piccole, i soldi contati, la camorra che detta le regole, le madri che urlano dalle finestre e le figlie che sognano di scappare. E poi, sullo sfondo, la città intera: il lungomare, i palazzi signorili del Vomero, la università, i quartieri borghesi dove Lenù si sente sempre un'intrusa.", es: "El barrio de las novelas es un personaje en sí mismo. Ferrante lo describe con una crudeza que ha decepcionado a algunos lectores napolitanos —demasiado sucio, demasiado violento, dicen— pero también con una precisión antropológica que pocos han igualado: las casas pequeñas, el dinero contado, la camorra que dicta las reglas, las madres que gritan desde las ventanas y las hijas que sueñan con escapar. Y luego, al fondo, la ciudad entera: el lungomare, los palacios señoriales del Vomero, la universidad, los barrios burgueses donde Lenù se siente siempre una intrusa." },
      { it: "Il successo dei libri ha prodotto un fenomeno raro: un turismo letterario al contrario. Non i lettori che visitano le case degli scrittori, ma una folla che cerca nei vicoli di Napoli i luoghi immaginari dell'opera — la galleria dove cammina Lila, il tunnel che porta al mare, la scuola elementare delle due bambine. La serie televisiva, co-prodotta da Rai e HBO, ha amplificato il fenomeno: girata interamente in napoletano nei dialoghi d'epoca, ha costretto persino gli attori italiani a recitare in una lingua che non era la loro, con risultati che la critica ha giudicato straordinari.", es: "El éxito de los libros ha producido un fenómeno raro: un turismo literario al revés. No lectores que visitan las casas de los escritores, sino una multitud que busca en los callejones de Nápoles los lugares imaginarios de la obra —la galería donde camina Lila, el túnel que lleva al mar, la escuela elemental de las dos niñas—. La serie televisiva, coproducida por Rai y HBO, amplificó el fenómeno: rodada enteramente en napolitano en los diálogos de época, obligó incluso a los actores italianos a actuar en una lengua que no era la suya, con resultados que la crítica consideró extraordinarios." },
      { it: "Ma il cuore dell'opera non è il mistero dell'autrice né il paesaggio napoletano: è la domanda su cosa significa diventare se stessi. Lenù scala la montagna sociale — il liceo, l'università, i libri pubblicati, il matrimonio borghese — e resta comunque prigioniera dello sguardo di Lila, l'unica che la vede davvero. Lila, che resta al rione e diventa programmatrice di computer in un'epoca in cui le donne non lo diventavano, possiede una libertà interiore che nessun titolo di studio le può dare. Alla fine, la domanda di Ferrante resta aperta: chi è davvero «l'amica geniale»? La scrittrice di successo o la donna che è rimasta?", es: "Pero el corazón de la obra no es el misterio de la autora ni el paisaje napolitano: es la pregunta por lo que significa llegar a ser uno mismo. Lenù escala la montaña social —el liceo, la universidad, los libros publicados, el matrimonio burgués— y queda sin embargo prisionera de la mirada de Lila, la única que la ve de verdad. Lila, que se queda en el barrio y se vuelve programadora de computadoras en una época en que las mujeres no lo eran, posee una libertad interior que ningún título de estudio le puede dar. Al final, la pregunta de Ferrante queda abierta: ¿quién es de verdad «la amiga genial»? ¿La escritora de éxito o la mujer que se quedó?" },
      { it: "Che si scopra o no, un giorno, chi si nasconde dietro lo pseudonimo — e ogni due o tre anni un'ipotesi nuova fa il giro dei giornali — l'anonimato di Ferrante è ormai parte dell'opera, come la selva oscura fa parte di Dante. Nel frattempo, nelle librerie di mezzo mondo, si continuano a leggere le sue pagine dove l'amicizia, l'invidia, l'intelligenza e la città di Napoli si tengono insieme con la forza disperata con cui si tengono insieme le cose vere.", es: "Se se descubra o no, algún día, quién se esconde tras el seudónimo —y cada dos o tres años una hipótesis nueva da la vuelta a los periódicos—, el anonimato de Ferrante es ya parte de la obra, como la selva oscura forma parte de Dante. Mientras tanto, en las librerías de medio mundo, se siguen leyendo sus páginas donde la amistad, la envidia, la inteligencia y la ciudad de Nápoles se mantienen unidas con la fuerza desesperada con que se mantienen unidas las cosas verdaderas." },
    ],
    glossary: [
      { it: "lo pseudonimo", es: "el seudónimo" },
      { it: "la quadrilogia", es: "la tetralogía (serie de cuatro obras)" },
      { it: "il rione popolare", es: "el barrio popular" },
      { it: "la camorra", es: "la camorra (mafia napolitana)" },
      { it: "antropologico", es: "antropológico" },
      { it: "un'intrusa", es: "una intrusa" },
    ],
    questions: [
      { q: "¿Qué ha declarado «Ferrante» sobre los libros y sus autores?", options: ["Che i libri hanno sempre bisogno dell'autore", "Che i libri, una volta scritti, non hanno bisogno dei loro autori", "Che gli autori devono fare più presentazioni", "Che lo pseudonimo è uno scherzo"], answer: 1, why: "A través del editor sostuvo que los libros, una vez escritos, no necesitan a sus autores: una postura radical en la era del yo público." },
      { q: "¿Quiénes son Lenù y Lila?", options: ["Due sorelle borghesi", "Due bambine di un rione popolare di Napoli: una studia e si allontana, l'altra lascia la scuola", "Due attrici della serie TV", "Madre e figlia"], answer: 1, why: "Elena/Lenù estudia y sale del barrio; Raffaella/Lila, brillantísima, debe dejar la escuela: su amistad competitiva es el motor de la saga." },
      { q: "¿Qué fenómeno turístico han provocado los libros?", options: ["Turisti che visitano la casa dell'autrice", "Lettori che cercano nei vicoli di Napoli i luoghi immaginari dell'opera", "Crocierе nel Mediterraneo", "Nessun fenomeno"], answer: 1, why: "Un turismo literario «al revés»: la multitud busca en los callejones reales los lugares ficticios de la novela." },
      { q: "¿Qué rasgo tiene la serie televisiva, según el texto?", options: ["È girata in inglese", "È girata interamente in napoletano nei dialoghi d'epoca", "È ambientata a Roma", "Non ha avuto successo"], answer: 1, why: "Coproducida por Rai y HBO, se rodó en napolitano de época, incluso para actores no napolitanos." },
      { q: "¿Cuál es la pregunta abierta que deja la obra?", options: ["Chi è l'autrice, davvero", "Chi è davvero «l'amica geniale»: la scrittrice di successo o la donna rimasta al rione", "Perché Napoli è povera", "Se Lenù tornerà al rione"], answer: 1, why: "El corazón de la obra es la pregunta sobre la identidad: ¿la genial es la que se fue o la que se quedó?" },
    ],
    discuss: [
      { it: "Ferrante scrive di amicizia femminile con una crudeltà e una onestà rare. Perché, secondo te, è così difficile trovare ritratti simili nella letteratura?", es: "Ferrante escribe sobre la amistad femenina con una crueldad y una honestidad raras. ¿Por qué, según tú, es tan difícil encontrar retratos así en la literatura?" },
      { it: "L'anonimato dell'autrice: una scelta di libertà o una strategia di marketing? Argomenta la tua posizione.", es: "El anonimato de la autora: ¿una elección de libertad o una estrategia de marketing? Argumenta tu posición." },
      { it: "Lenù si allontana dal quartiere ma resta legata a Lila: hai mai avuto un'amicizia che funzionava come uno specchio? Racconta.", es: "Lenù se aleja del barrio pero queda atada a Lila: ¿has tenido alguna vez una amistad que funcionara como un espejo? Cuenta." },
    ],
  },
];
