/* ── Letture EXTRA · Paquete v9.11 · Parte 6: 2 storia-italia + 2 storia-mondo ─
   it-medioevo-15 (B1): i comuni medievali.
   it-piombo-16 (B2): gli anni di piombo.
   mon-vichinghi-20 (A2): i vichinghi, navigatori del Nord.
   mon-spazio-21 (B1): la corsa allo spazio.
   100% contenido original.                                            */

import type { CefrLevel } from "./types";
import type { Lettura } from "./letture";

/* ═══ STORIA ITALIA EXTRA v9.11 ═══════════════════════════════════════ */

export const STORIA_ITALIA_EXTRA6: Lettura[] = [
  {
    id: "it-medioevo-15",
    cat: "storia-italia",
    level: "B1",
    title: "I comuni: quando le città si governavano da sole",
    titleEs: "Los comunas: cuando las ciudades se gobernaban solas",
    minutes: 5,
    lines: [
      { it: "Quando pensiamo al Medioevo, immaginiamo spesso castelli, cavalieri e contadini. Ma in Italia, dopo l'anno Mille, succede qualcosa di sorprendente: le città tornano a vivere. Cresce la popolazione, riprendono i commerci, si riempiono i mercati. E con la ricchezza arriva una domanda nuova: chi decide, in città? Non un castello lontano, non un nobile guerriero: i cittadini stessi.", es: "Cuando pensamos en la Edad Media, solemos imaginar castillos, caballeros y campesinos. Pero en Italia, después del año Mil, sucede algo sorprendente: las ciudades vuelven a vivir. Crece la población, se reanudan los comercios, se llenan los mercados. Y con la riqueza llega una pregunta nueva: ¿quién decide, en la ciudad? No un castillo lejano, no un noble guerrero: los propios ciudadanos." },
      { it: "Nasce così il comune: un giuramento collettivo con cui i cittadini — mercanti, notai, artigiani, proprietari — si promettono reciproca protezione e si danno delle regole. È una parola che oggi usiamo per indicare il municipio, e non è un caso: quando in italiano diciamo «il Comune», con la maiuscola, parliamo ancora del discendente diretto di quei giuramenti medievali. All'inizio il potere è affidato a dei consoli, scelti tra le famiglie più influenti; più tardi, per evitare favoritismi, si preferisce chiamare un podestà: un signore forestiero, pagato per governare con neutralità per un anno e poi andare via.", es: "Nace así la comuna: un juramento colectivo con el que los ciudadanos —mercaderes, notarios, artesanos, propietarios— se prometen protección recíproca y se dan reglas. Es una palabra que hoy usamos para indicar la municipalidad, y no es casualidad: cuando en italiano decimos «il Comune», con mayúscula, hablamos todavía del descendiente directo de aquellos juramentos medievales. Al comienzo el poder se confía a unos cónsules, elegidos entre las familias más influyentes; más tarde, para evitar favoritismos, se prefiere llamar a un podestà: un señor forastero, pagado para gobernar con neutralidad durante un año y luego irse." },
      { it: "Il simbolo del comune è il campanile o la torre civica: più alta della torre dei signori, perché la città conta più di ogni famiglia privata. E le città italiane si coprono davvero di torri: a Bologna, nel Duecento, ce ne sono più di cento; a San Gimignano, in Toscana, se ne vedono ancora oggi una quindicina, e i turisti la chiamano «la Manhattan medievale». Ogni torre è una sfida: più alta della tua, più forte della tua.", es: "El símbolo de la comuna es el campanile o la torre cívica: más alta que la torre de los señores, porque la ciudad cuenta más que cualquier familia privada. Y las ciudades italianas se cubren de verdad de torres: en Bolonia, en el Duecento, hay más de cien; en San Gimignano, en Toscana, todavía hoy se ven una quincena, y los turistas la llaman «el Manhattan medieval». Cada torre es un desafío: más alta que la tuya, más fuerte que la tuya." },
      { it: "Ma dentro le mura non tutto è pace. Le città si dividono in fazioni, spesso legate a famiglie rivali, e i nomi di questi schieramenti entrano nella storia: guelfi e ghibellini. I guelfi sostengono il papa, i ghibellini l'imperatore; in pratica, però, la lotta è per il potere locale, per i contratti, per le dogane. Firenze, che pure è ricca e piena di banchieri, vive un secolo di guerre intestine; e un poeta fiorentino, coinvolto proprio in queste lotte, finisce in esilio e scrive, lontano da casa, il poema più importante della lingua italiana: Dante Alighieri.", es: "Pero dentro de las murallas no todo es paz. Las ciudades se dividen en facciones, a menudo ligadas a familias rivales, y los nombres de estos bandos entran en la historia: güelfos y gibelinos. Los güelfos apoyan al papa, los gibelinos al emperador; en la práctica, sin embargo, la lucha es por el poder local, por los contratos, por las aduanas. Florencia, que sin embargo es rica y está llena de banqueros, vive un siglo de guerras intestinas; y un poeta florentino, involucrado justamente en estas luchas, termina en el exilio y escribe, lejos de casa, el poema más importante de la lengua italiana: Dante Alighieri." },
      { it: "Non sono però solo guerre. I comuni finanziano ponti, mura, ospedali e, soprattutto, studi. A Bologna, attorno al 1088, nasce quella che consideriamo la prima università del mondo occidentale: studenti arrivati da tutta Europa pagano professori di diritto, e la città promette loro protezione perfino contro l'imperatore. È l'inizio di una istituzione che esiste ancora oggi, nove secoli dopo, con gli stessi nomi — ateneo, facoltà, rettore — e con una città studentesca che d'estate si svuota e a ottobre esplode di biciclette.", es: "No son sin embargo solo guerras. Los comunas financian puentes, murallas, hospitales y, sobre todo, estudios. En Bolonia, hacia 1088, nace la que consideramos la primera universidad del mundo occidental: estudiantes llegados de toda Europa pagan a profesores de derecho, y la ciudad les promete protección incluso contra el emperador. Es el inicio de una institución que existe todavía hoy, nueve siglos después, con los mismos nombres —ateneo, facultad, rector— y con una ciudad estudiantil que en verano se vacía y en octubre explota de bicicletas." },
      { it: "Alla fine, i comuni si trasformano: le famiglie più forti prendono il potere e nascono le signorie — i Medici a Firenze, gli Visconti e gli Sforza a Milano — e l'esperienza dell'autogoverno sembra chiudersi. Ma qualcosa resta: l'idea che la città sia dei cittadini, che le leggi valgano per tutti, che un forestiero possa governare solo se neutrale, che lo studio valga più delle armi. Nove secoli dopo, il sindaco di un paese italiano che taglia il nastro di una nuova scuola sta ancora recitando, senza saperlo, un copione scritto dai mercanti medievali.", es: "Al final, los comunas se transforman: las familias más fuertes toman el poder y nacen las señorías —los Médici en Florencia, los Visconti y los Sforza en Milán— y la experiencia del autogobierno parece cerrarse. Pero algo queda: la idea de que la ciudad sea de los ciudadanos, de que las leyes valgan para todos, de que un forastero pueda gobernar solo si es neutral, de que el estudio valga más que las armas. Nueve siglos después, el alcalde de un pueblo italiano que corta la cinta de una escuela nueva está todavía representando, sin saberlo, un guion escrito por los mercaderes medievales." },
    ],
    glossary: [
      { it: "il notaio", es: "el notario" },
      { it: "il podestà", es: "el podestà (gobernador forastero temporal)" },
      { it: "la fazione", es: "la facción / el bando" },
      { it: "guelfi e ghibellini", es: "güelfos y gibelinos (papa vs emperador)" },
      { it: "le guerre intestine", es: "las guerras intestinas / internas" },
      { it: "la signoria", es: "la señoría (gobierno de una familia)" },
      { it: "l'autogoverno", es: "el autogobierno" },
    ],
    questions: [
      { q: "¿Qué es, en origen, el «comune» medieval?", options: ["Un castello del re", "Un giuramento collettivo: i cittadini si promettono reciproca protezione e si danno regole", "Un mercato settimanale", "Un esercito di mercenari"], answer: 1, why: "Es un juramento colectivo de protección recíproca entre mercaderes, notarios, artesanos y propietarios." },
      { q: "¿Por qué se prefiere luego un podestà forastero?", options: ["Perché costa meno", "Per evitare favoritismi: un forestiero pago governa un anno con neutralità e poi va via", "Perché lo sceglie il papa", "Perché è un guerriero più forte"], answer: 1, why: "El podestà es un señor forastero, pagado para goberrar con neutralidad un año: evita que domine una familia local." },
      { q: "¿Qué simboliza la torre cívica más alta que las torres señoriales?", options: ["La potenza militare del vescovo", "Che la città conta più di ogni famiglia privata", "L'altezza del grano", "Un gioco tra architetti"], answer: 1, why: "La torre de la ciudad debía superar a las torres privadas: la comunidad por encima de cualquier familia." },
      { q: "¿Qué nace en Bolonia hacia 1088, según el texto?", options: ["Il primo banco", "La prima università del mondo occidentale", "Il primo ospedale", "La prima fabbrica"], answer: 1, why: "La primera universidad del Occidente: estudiantes de toda Europa, profesores de derecho, protección de la ciudad." },
      { q: "¿En qué se transforman al final los comunas?", options: ["In colonie", "In signorie: le famiglie più forti prendono il potere (Medici, Visconti, Sforza)", "In repubbliche moderne", "In diocesi"], answer: 1, why: "Las señorías: los Médici, los Visconti y los Sforza toman el poder; pero la idea de autogobierno sobrevive." },
    ],
    discuss: [
      { it: "Nel tuo paese esistono città medievali con torri o mura? Raccontane una.", es: "¿En tu país existen ciudades medievales con torres o murallas? Cuenta una." },
      { it: "Guelfi e ghibellini: conosci conflitti storici del tuo paese tra fazioni che si nascondevano dietro grandi cause?", es: "Güelfos y gibelinos: ¿conoces conflictos históricos de tu país entre facciones que se escondían detrás de grandes causas?" },
      { it: "«La città è dei cittadini»: quanto è vera questa idea oggi? Chi decide davvero nella tua città?", es: "«La ciudad es de los ciudadanos»: ¿qué tan cierta es esta idea hoy? ¿Quién decide de verdad en tu ciudad?" },
    ],
  },
  {
    id: "it-piombo-16",
    cat: "storia-italia",
    level: "B2",
    title: "Gli anni di piombo: l'Italia della paura",
    titleEs: "Los años de plomo: la Italia del miedo",
    minutes: 6,
    lines: [
      { it: "Li chiamano «anni di piombo», e il nome dice tutto: il piombo è quello dei proiettili. È un periodo che va, indicativamente, dal 1969 alla prima metà degli anni Ottanta, in cui l'Italia democratica attraversa la prova più dura della sua storia repubblicana: stragi nelle piazze, attentati sui treni, rapimenti, assassinii, e una lotta politica che a volte smette di essere politica e diventa guerra.", es: "Los llaman «años de plomo», y el nombre lo dice todo: el plomo es el de las balas. Es un período que va, indicativamente, de 1969 a la primera mitad de los años Ochenta, en el que la Italia democrática atraviesa la prueba más dura de su historia republicana: masacres en las plazas, atentados en los trenes, secuestros, asesinatos, y una lucha política que a veces deja de ser política y se vuelve guerra." },
      { it: "Il contesto aiuta a capire, senza giustificare. Il boom economico è finito; le fabbriche sono in fermento, gli studenti hanno occupato le università; la società italiana cambia a una velocità che le istituzioni faticano a seguire. Sullo sfondo, la guerra fredda: a ovest gli Stati Uniti e la Nato, a est l'Unione Sovietica, e l'Italia — paese di confine, con il più grande partito comunista d'Occidente — è uno dei terreni preferiti della tensione internazionale. In questo clima nasce, all'inizio del 1969, una serie impressionante di attentati dimostrativi: bombe che esplodono di notte, senza vittime, su treni e in luoghi pubblici. Qualcuno, in ambienti dell'estrema destra, pensa che la paura porterà l'ordine.", es: "El contexto ayuda a entender, sin justificar. El boom económico terminó; las fábricas están en efervescencia, los estudiantes han ocupado las universidades; la sociedad italiana cambia a una velocidad que las instituciones difícilmente logran seguir. Al fondo, la guerra fría: al oeste Estados Unidos y la OTAN, al este la Unión Soviética, e Italia —país de frontera, con el mayor partido comunista de Occidente— es uno de los terrenos preferidos de la tensión internacional. En este clima nace, a comienzos de 1969, una serie impresionante de atentados demostrativos: bombas que explotan de noche, sin víctimas, en trenes y en lugares públicos. Alguien, en ambientes de la extrema derecha, piensa que el miedo traerá el orden." },
      { it: "Il 12 dicembre 1969 la follia diventa strage: alle 16:37 una bomba esplode nella Banca Nazionale dell'Agricoltura di piazza Fontana, a Milano. Sedici persone muoiono sul colpo, e nei giorni successivi la conta arriva a diciassette; ottantotto restano ferite. L'Italia scopre una parola nuova, «strage», e una stagione di menzogne: le prime indagini puntano sugli anarchici, e un ferroviere anarchico, Giuseppe Pinelli, muore cadendo da una finestra della questura durante un interrogatorio. Solo molti anni dopo, attraverso processi interminabili, si arriverà a una verità giudiziaria almeno parziale: la strage è di matrice fascista. Ma la parola «depistaggio» — la deviazione deliberata delle indagini — entra per sempre nel vocabolario italiano.", es: "El 12 de diciembre de 1969 la locura se vuelve masacre: a las 16:37 una bomba estalla en el Banco Nacional de la Agricultura de piazza Fontana, en Milán. Dieciséis personas mueren en el acto, y en los días siguientes la cuenta llega a diecisiete; ochenta y ocho quedan heridas. Italia descubre una palabra nueva, «strage» (masacre), y una temporada de mentiras: las primeras investigaciones apuntan a los anarquistas, y un ferroviario anarquista, Giuseppe Pinelli, muere cayendo por una ventana de la comisaría durante un interrogatorio. Solo muchos años después, a través de procesos interminables, se llegará a una verdad judicial al menos parcial: la masacre es de matriz fascista. Pero la palabra «depistaggio» —la desviación deliberada de las investigaciones— entra para siempre en el vocabulario italiano." },
      { it: "La strategia è quella che gli storici chiamano «strategia della tensione»: seminare terrore per creare un clima di emergenza, in cui la democrazia appare debole e un regime autoritario appare, a qualcuno, l'unica soluzione. Non funziona: le istituzioni reggono, le elezioni continuano a svolgersi. Ma il paese non esce dalla tempesta: negli anni Settanta l'estremismo di sinistra dà vita alle Brigate Rosse, che passano dalla lotta armata all'assassinio. Il momento più drammatico è il 16 marzo 1978, quando le BR rapiscono Aldo Moro, presidente della Democrazia Cristiana, l'uomo che stava costruendo, con il Partito Comunista, quel «compromesso storico» che le BR vogliono proprio impedire. Cinquantacinque giorni di prigionia, lettere dal «carcere del popolo», un governo che rifiuta ogni negoziazione: il 9 maggio il corpo di Moro viene trovato in via Caetani, a metà strada tra le sedi della DC e del PCI, come un messaggio macabro.", es: "La estrategia es la que los historiadores llaman «estrategia de la tensión»: sembrar terror para crear un clima de emergencia, en el que la democracia parece débil y un régimen autoritario parece, para alguien, la única solución. No funciona: las instituciones aguantan, las elecciones siguen celebrándose. Pero el país no sale de la tormenta: en los años Setenta el extremismo de izquierda da vida a las Brigadas Rojas, que pasan de la lucha armada al asesinato. El momento más dramático es el 16 de marzo de 1978, cuando las BR secuestran a Aldo Moro, presidente de la Democracia Cristiana, el hombre que estaba construyendo, con el Partido Comunista, aquel «compromiso histórico» que las BR quieren precisamente impedir. Cincuenta y cinco días de cautiverio, cartas desde la «cárcel del pueblo», un gobierno que rechaza toda negociación: el 9 de mayo el cuerpo de Moro es encontrado en vía Caetani, a medio camino entre las sedes de la DC y del PCI, como un mensaje macabro." },
      { it: "Il 2 agosto 1980, alle 10:25 di un sabato mattina di vacanze, la bomba più sanguinosa esplode nella sala d'attesa di seconda classe della stazione di Bologna: ottantacinque morti, duecento feriti. La città risponde con una dignità che diventa un modello: il funerale allo stadio, il silenzio, e poi, per decenni, la battaglia giudiziaria e civile delle famiglie delle vittime — l'Associazione tra i familiari delle vittime della strage di Bologna — che otterrà condanne definitive per esponenti del terrorismo nero e, per la logica dei depistaggi, anche per uomini dei servizi segreti deviati. Il 2 agosto è oggi la giornata nazionale della memoria delle vittime del terrorismo.", es: "El 2 de agosto de 1980, a las 10:25 de un sábado de vacaciones por la mañana, la bomba más sangrienta estalla en la sala de espera de segunda clase de la estación de Bolonia: ochenta y cinco muertos, doscientos heridos. La ciudad responde con una dignidad que se vuelve modelo: el funeral en el estadio, el silencio, y luego, durante décadas, la batalla judicial y civil de las familias de las víctimas —la Asociación entre los familiares de las víctimas de la masacre de Bolonia— que obtendrá condenas definitivas para exponentes del terrorismo negro y, por la lógica de los desvíos, también para hombres de los servicios secretos desviados. El 2 de agosto es hoy la jornada nacional de la memoria de las víctimas del terrorismo." },
      { it: "Cosa resta, oggi, degli anni di piombo? Molte verità giudiziarie sono arrivate tardi o non sono mai arrivate; alcuni mandanti restano senza nome. Ma resta anche un'altra eredità, meno visibile: l'Italia che ha attraversato quelle prove senza interrompere le elezioni, senza chiudere il parlamento, senza rinunciare alle libertà — e che ha imparato, a caro prezzo, quanto costa la violenza politica e quanto è fragile, e preziosa, la convivenza democratica. Per questo ogni 2 agosto, a Bologna, la sirena della stazione suona alle 10:25, e la città si ferma. La memoria, dicono i familiari delle vittime, non è nostalgia: è un'opera di manutenzione della democrazia.", es: "¿Qué queda, hoy, de los años de plomo? Muchas verdades judiciales llegaron tarde o nunca llegaron; algunos mandantes siguen sin nombre. Pero queda también otra herencia, menos visible: la Italia que atravesó aquellas pruebas sin interrumpir las elecciones, sin cerrar el parlamento, sin renunciar a las libertades —y que aprendió, a un precio caro, cuánto cuesta la violencia política y cuán frágil, y preciosa, es la convivencia democrática. Por eso cada 2 de agosto, en Bolonia, la sirena de la estación suena a las 10:25, y la ciudad se detiene. La memoria, dicen los familiares de las víctimas, no es nostalgia: es una obra de mantenimiento de la democracia." },
    ],
    glossary: [
      { it: "lo piombo / gli anni di piombo", es: "el plomo / los años de plomo" },
      { it: "la strage", es: "la masacre / el atentado masivo" },
      { it: "il depistaggio", es: "el desvío deliberado de una investigación" },
      { it: "la strategia della tensione", es: "la estrategia de la tensión" },
      { it: "il mandante", es: "el mandante (quien ordena el crimen)" },
      { it: "a caro prezzo", es: "a un precio caro" },
      { it: "la convivenza democratica", es: "la convivencia democrática" },
    ],
    questions: [
      { q: "¿Por qué se llaman «anni di piombo»?", options: ["Per le mini di piombo", "Per il piombo dei proiettili, in un'epoca di stragi e attentati", "Per il colore del cielo", "Per un film famoso"], answer: 1, why: "«Il piombo è quello dei proiettili»: hace referencia a la violencia armada de 1969 a los años Ochenta." },
      { q: "¿Qué ocurrió el 12 de diciembre de 1969 en piazza Fontana?", options: ["Un rapimento", "Una bomba alla Banca Nazionale dell'Agricoltura: 17 morti e 88 feriti", "Uno sciopero", "Un attentato senza vittime"], answer: 1, why: "La bomba en el Banco Nacional de la Agricultura de Milán: la primera gran masacre, de matriz fascista según la verdad judicial." },
      { q: "¿Qué es la «strategia della tensione»?", options: ["Una politica economica", "Seminare terrore per creare emergenza, far apparire debole la democrazia e aprire la strada a un regime autoritario", "Una strategia militare della Nato", "Un metodo di studio"], answer: 1, why: "Sembrar terror para crear emergencia: la democracia aparece débil y el régimen autoritario aparece como solución a alguien." },
      { q: "¿Por qué las Brigate Rosse secuestran a Aldo Moro en 1978?", options: ["Per soldi", "Per impedire il «compromesso storico» tra DC e Partito Comunista che Moro stava costruendo", "Per liberare un loro capo", "Per caso"], answer: 1, why: "Moro construía el compromiso histórico con el PCI; el secuestro termina 55 días después con su asesinato." },
      { q: "¿Qué se conmemora cada 2 de agosto?", options: ["La festa della Repubblica", "La giornata nazionale della memoria delle vittime del terrorismo, per la strage di Bologna del 1980 (85 morti)", "La liberazione", "L'unità d'Italia"], answer: 1, why: "La masacre de la estación de Bolonia (85 muertos); la sirena suena a las 10:25 y la ciudad se detiene." },
    ],
    discuss: [
      { it: "Il tuo paese ha vissuto periodi di violenza politica? Come ne ha parlato, dopo? Come se ne ricorda?", es: "¿Tu país vivió períodos de violencia política? ¿Cómo se habló de ello después? ¿Cómo se lo recuerda?" },
      { it: "«La memoria è manutenzione della democrazia»: cosa pensi di questa frase? Si può ricordare troppo, o troppo poco?", es: "«La memoria es mantenimiento de la democracia»: ¿qué piensas de esta frase? ¿Se puede recordar demasiado, o demasiado poco?" },
      { it: "Il governo rifiutò ogni negoziazione con le BR per Moro: fu una scelta giusta? Argomenta pro e contro.", es: "El gobierno rechazó toda negociación con las BR por Moro: ¿fue una elección justa? Argumenta a favor y en contra." },
    ],
  },
];

/* ═══ STORIA MONDO EXTRA v9.11 ════════════════════════════════════════ */

export const STORIA_MONDO_EXTRA6: Lettura[] = [
  {
    id: "mon-vichinghi-20",
    cat: "storia-mondo",
    level: "A2",
    title: "I vichinghi: navigatori del Nord",
    titleEs: "Los vikingos: navegantes del Norte",
    minutes: 3,
    lines: [
      { it: "I vichinghi vivevano nel Nord dell'Europa, nell'area delle attuali Danimarca, Norvegia e Svezia. Il loro tempo va, più o meno, dal 793 al 1066: quasi tre secoli. Oggi li immaginiamo sempre con l'elmetto e la scure, ma erano soprattutto marinai e commercianti straordinari. Il mare, per loro, non era un muro: era una strada.", es: "Los vikingos vivían en el norte de Europa, en la zona de las actuales Dinamarca, Noruega y Suecia. Su época va, más o menos, del 793 al 1066: casi tres siglos. Hoy los imaginamos siempre con el casco y el hacha, pero eran sobre todo marineros y comerciantes extraordinarios. El mar, para ellos, no era un muro: era un camino." },
      { it: "Il segreto del loro successo era la nave. Le navi vichinghe erano di legno, lunghe e basse, con la vela e i remi. Potevano navigare veloci in mare aperto, ma erano anche abbastanza leggere per salire nei fiumi. Con una nave di questo tipo si poteva arrivare in un villaggio vicino al fiume, attaccare di sorpresa e scappare prima dell'arrivo dei soldati.", es: "El secreto de su éxito era el barco. Los barcos vikingos eran de madera, largos y bajos, con vela y remos. Podían navegar rápido en mar abierto, pero también eran bastante ligeros para subir por los ríos. Con un barco de ese tipo se podía llegar a una aldea cerca del río, atacar por sorpresa y escapar antes de la llegada de los soldados." },
      { it: "Come navigavano senza bussola? Usavano la natura. Guardavano il sole e le stelle, studiavano il volo degli uccelli (gli uccelli volano verso la terra più vicina) e osservavano le nuvole sopra le isole. Con questi sistemi semplici arrivavano lontanissimo: dall'Islanda alla Groenlandia, attraversando l'Atlantico freddo e pericoloso.", es: "¿Cómo navegaban sin brújula? Usaban la naturaleza. Miraban el sol y las estrellas, estudiaban el vuelo de las aves (las aves vuelan hacia la tierra más cercana) y observaban las nubes sobre las islas. Con estos sistemas simples llegaban lejísimos: de Islandia a Groenlandia, cruzando el Atlántico frío y peligroso." },
      { it: "E hanno fatto una cosa incredibile: sono arrivati in America! Attorno all'anno 1000, il navigatore Leif Erikson è sbarcato in un territorio che i vichinghi chiamavano «Vinland», la «terra delle vigne», nell'attuale Canada. È successo quasi cinquecento anni prima di Cristoforo Colombo. Non hanno creato una colonia stabile, ma la loro impresa è raccontata nelle saghe, le antiche storie del Nord.", es: "E hicieron algo increíble: ¡llegaron a América! Alrededor del año 1000, el navegante Leif Erikson desembarcó en un territorio que los vikingos llamaban «Vinland», la «tierra de las viñas», en el actual Canadá. Sucedió casi quinientos años antes de Cristóbal Colón. No crearon una colonia estable, pero su hazaña está contada en las sagas, las antiguas historias del Norte." },
      { it: "Non erano solo guerrieri: erano anche contadini, artigiani e mercanti. Vendevano e compravano ambra, pellicce, avorio e sale. Andavano a est, in Russia, fino a Costantinopoli, dove alcuni vichinghi sono diventati guardie dell'imperatore. E nelle terre dove si fermavano costruivano case, fattorie e piccoli regni: in Inghilterra, in Irlanda, in Normandia e in Sicilia.", es: "No eran solo guerreros: también eran campesinos, artesanos y mercaderes. Vendían y compraban ámbar, pieles, marfil y sal. Iban al este, a Rusia, hasta Constantinopla, donde algunos vikingos llegaron a ser guardias del emperador. Y en las tierras donde se quedaban construían casas, granjas y pequeños reinos: en Inglaterra, en Irlanda, en Normandía y en Sicilia." },
      { it: "Oggi i vichinghi sono ovunque: nei musei della Scandinavia, nei film e nelle serie TV, nei nomi delle navi e persino nello spazio (una sonda si chiama «Viking»). Ma la cosa più interessante è un'altra: con le loro saghe — storie di dei, eroi e viaggi, scritte secoli dopo i fatti — hanno creato una letteratura che si legge ancora. Poche parole di un popolo di marinai, eppure: il mare era una strada, e le storie erano la mappa.", es: "Hoy los vikingos están en todas partes: en los museos de Escandinavia, en el cine y las series, en los nombres de barcos e incluso en el espacio (una sonda se llama «Viking»). Pero lo más interesante es otra cosa: con sus sagas —historias de dioses, héroes y viajes, escritas siglos después de los hechos— crearon una literatura que todavía se lee. Pocas palabras de un pueblo de marineros, y sin embargo: el mar era un camino, y las historias eran el mapa." },
    ],
    glossary: [
      { it: "la scure", es: "el hacha" },
      { it: "i remi", es: "los remos" },
      { it: "la bussola", es: "la brújula" },
      { it: "sbarcare", es: "desembarcar" },
      { it: "l'impresa", es: "la hazaña" },
      { it: "l'ambra", es: "el ámbar" },
      { it: "la fattoria", es: "la granja" },
    ],
    questions: [
      { q: "¿Dónde vivían los vikingos?", options: ["In Italia e Spagna", "Nel Nord dell'Europa: Danimarca, Norvegia e Svezia", "In Russia", "In America"], answer: 1, why: "Vivían en el norte de Europa, en las actuales Dinamarca, Noruega y Suecia." },
      { q: "¿Por qué sus barcos podían subir por los ríos?", options: ["Erano di ferro", "Erano di legno, lunghi e bassi, abbastanza leggeri per i fiumi", "Avevano le ruote", "Usavano solo la vela"], answer: 1, why: "Eran de madera, largos y bajos: rápidos en mar abierto y ligeros para navegar ríos." },
      { q: "¿Cómo se orientaban sin brújula?", options: ["Con il GPS", "Con il sole, le stelle, il volo degli uccelli e le nuvole", "Chiedevano ad altri marinai", "Non navigavano lontano"], answer: 1, why: "Usaban la naturaleza: sol, estrellas, vuelo de las aves y nubes sobre las islas." },
      { q: "¿Qué territorio llamado «Vinland» alcanzó Leif Erikson hacia el año 1000?", options: ["L'Australia", "L'attuale Canada, quasi 500 anni prima di Colombo", "Il Giappone", "L'Africa"], answer: 1, why: "Llegó al actual Canadá casi cinco siglos antes de Colón; la hazaña está en las sagas." },
      { q: "¿Qué hacían los vikingos además de guerrear?", options: ["Solo guerreggiavano", "Erano contadini, artigiani e mercanti: ambra, pellicce, avorio e sale", "Erano pescatori soltanto", "Erano imperatori"], answer: 1, why: "Comerciaban ámbar, pieles, marfil y sal; algunos llegaron a ser guardias del emperador en Constantinopla." },
    ],
    discuss: [
      { it: "Conosci film o serie TV sui vichinghi? Ti sembrano realistici dopo questa lettura?", es: "¿Conoces películas o series sobre vikingos? ¿Te parecen realistas después de esta lectura?" },
      { it: "Il mare «strada» o «muro»: nel tuo paese il mare è stato una strada o un muro? Racconta.", es: "El mar «camino» o «muro»: ¿en tu país el mar ha sido camino o muro? Cuenta." },
      { it: "Le saghe raccontano viaggi fatti secoli prima: quanto possiamo fidarci di storie orali? Confronta con le tue tradizioni.", es: "Las sagas cuentan viajes hechos siglos antes: ¿cuánto podemos fiarnos de historias orales? Compara con tus tradiciones." },
    ],
  },
  {
    id: "mon-spazio-21",
    cat: "storia-mondo",
    level: "B1",
    title: "La corsa allo spazio: dallo Sputnik alla Stazione",
    titleEs: "La carrera espacial: del Sputnik a la Estación",
    minutes: 4,
    lines: [
      { it: "Nell'ottobre del 1957 il mondo si sveglia con un nuovo suono: un piccolo «bip bip» che arriva dal cielo. È lo Sputnik 1, il primo satellite artificiale della storia, lanciato dall'Unione Sovietica. È una sfera di metallo grande come un pallone da spiaggia, e non fa niente di speciale: manda solo un segnale radio. Ma il messaggio politico è fortissimo — chi controlla lo spazio, controlla il mondo — e gli Stati Uniti reagiscono con una determinazione (e una paura) che segneranno i decenni successivi.", es: "En octubre de 1957 el mundo despierta con un sonido nuevo: un pequeño «bip bip» que viene del cielo. Es el Sputnik 1, el primer satélite artificial de la historia, lanzado por la Unión Soviética. Es una esfera de metallo grande como un balón de playa y no hace nada especial: envía solo una señal de radio. Pero el mensaje político es fortísimo —quien controla el espacio, controla el mundo— y Estados Unidos reacciona con una determinación (y un miedo) que marcarán las décadas siguientes." },
      { it: "La «corsa allo spazio» è, in realtà, un capitolo della guerra fredda: due sistemi — la democrazia americana e il comunismo sovietico — che si sfidano a colpi di primati per dimostrare la propria superiorità. Nel 1961 i sovietici vincono la tappa più emozionante: Jurij Gagarin diventa il primo uomo nello spazio, compie un giro intorno alla Terra in 108 minuti e torna giù dicendo una frase rimasta famosa: «La Terra è blu».", es: "La «carrera espacial» es, en realidad, un capítulo de la guerra fría: dos sistemas —la democracia americana y el comunismo soviético— que se desafían a golpes de récords para demostrar su superioridad. En 1961 los soviéticos ganan la etapa más emocionante: Yuri Gagarin se convierte en el primer hombre en el espacio, da una vuelta a la Tierra en 108 minutos y vuelve abajo diciendo una frase que quedó famosa: «La Tierra es azul»." },
      { it: "Il presidente americano Kennedy promette allora il colpo più difficile: mandare un uomo sulla Luna entro la fine del decennio. Il programma Apollo costa una fortuna — e un prezzo umano: tre astronauti muoiono in un incendio durante un test nel 1967 — ma il 20 luglio 1969, davanti a seicento milioni di persone davanti alla televisione, Neil Armstrong scende la scaletta del modulo lunare e pronuncia le parole entrate nella storia: «Un piccolo passo per un uomo, un grande balzo per l'umanità».", es: "El presidente americano Kennedy promete entonces el golpe más difícil: enviar un hombre a la Luna antes de terminar la década. El programa Apolo cuesta una fortuna —y un precio humano: tres astronautas mueren en un incendio durante una prueba en 1967— pero el 20 de julio de 1969, ante seiscientas millones de personas frente al televisor, Neil Armstrong baja la escalerilla del módulo lunar y pronuncia las palabras que entraron en la historia: «Un pequeño paso para un hombre, un gran salto para la humanidad»." },
      { it: "Dopo la Luna, la corsa cambia passo. I sovietici puntano sulle stazioni spaziali, gli americani sullo space shuttle, e per anni lo spazio sembra soprattutto un campo militare e di prestigio. Poi, lentamente, nasce un'idea nuova: cooperare. Nel 1998 inizia la costruzione della Stazione Spaziale Internazionale (ISS), il progetto pacifico più costoso e complesso della storia: quindici paesi, tra cui Stati Uniti, Russia, Giappone, Canada e i paesi europei, che costruiscono insieme un laboratorio che vola a 400 chilometri sopra le nostre teste, dove oggi gli astronauti — russi e americani insieme — vivono e lavorano per mesi.", es: "Después de la Luna, la carrera cambia de ritmo. Los soviéticos apuestan por las estaciones espaciales, los americanos por el transbordador, y durante años el espacio parece sobre todo un campo militar y de prestigio. Luego, lentamente, nace una idea nueva: cooperar. En 1998 comienza la construcción de la Estación Espacial Internacional (ISS), el proyecto pacífico más caro y complejo de la historia: quince países, entre ellos Estados Unidos, Rusia, Japón, Canadá y los países europeos, que construyen juntos un laboratorio que vuela a 400 kilómetros sobre nuestras cabezas, donde hoy los astronautas —rusos y americanos juntos— viven y trabajan durante meses." },
      { it: "E l'Italia? Presente, e prima di quanto si pensi: nel 1964 l'Italia lancia il San Marco, il primo satellite di un paese non superpotenza, da una base... galleggiante, una piattaforma al largo della Kenya. Da allora, l'agenzia spaziale italiana (ASI, nata nel 1988) ha contribuito a decine di missioni, e gli astronauti italiani sono diventati protagonisti: Samantha Cristoforetti ha passato più di un anno nello spazio in due missioni, comandando pure la ISS — la prima donna europea a farlo — e raccontando la sua esperienza in diretta sui social, in italiano.", es: "¿Y Italia? Presente, y antes de lo que se piensa: en 1964 Italia lanza el San Marco, el primer satélite de un país no superpotencia, desde una base... flotante, una plataforma frente a Kenia. Desde entonces, la agencia espacial italiana (ASI, nacida en 1988) ha contribuido a decenas de misiones, y los astronautas italianos se han vuelto protagonistas: Samantha Cristoforetti ha pasado más de un año en el espacio en dos misiones, llegando a comandar la ISS —la primera mujer europea en hacerlo— y contando su experiencia en directo en las redes, en italiano." },
      { it: "Oggi la corsa è ripresa, ma con attori nuovi: le aziende private, con i razzi riutilizzabili, hanno abbassato i costi e moltiplicato i lanci; la Cina è entrata da protagonista; e i programmi Artemis promettono il ritorno sulla Luna — con la prima donna — come trampolino verso Marte. Siamo all'inizio di una nuova stagione, e nessuno sa come finirà. Ma guardando le foto della Terra vista dallo spazio — quel palloncino blu e fragile appeso nel buio — è difficile non pensare che, in fondo, la cosa più importante che i viaggi spaziali ci hanno regalato non è la Luna: è la consapevolezza della nostra casa comune.", es: "Hoy la carrera se ha reanudado, pero con actores nuevos: las empresas privadas, con los cohetes reutilizables, han bajado los costos y multiplicado los lanzamientos; China ha entrado como protagonista; y los programas Artemis prometen el regreso a la Luna —con la primera mujer— como trampolín hacia Marte. Estamos al inicio de una nueva temporada, y nadie sabe cómo terminará. Pero mirando las fotos de la Tierra vista desde el espacio —aquel globo azul y frágil colgado en la oscuridad— es difícil no pensar que, en el fondo, lo más importante que los viajes espaciales nos han regalado no es la Luna: es la conciencia de nuestra casa común." },
    ],
    glossary: [
      { it: "il satellite artificiale", es: "el satélite artificial" },
      { it: "la corsa", es: "la carrera" },
      { it: "il primato", es: "el récord / la primacía" },
      { it: "la scaletta", es: "la escalerilla" },
      { it: "il modulo lunare", es: "el módulo lunar" },
      { it: "la piattaforma galleggiante", es: "la plataforma flotante" },
      { it: "il trampolino", es: "el trampolín" },
    ],
    questions: [
      { q: "¿Qué fue el Sputnik 1 (1957)?", options: ["Il primo uomo nello spazio", "Il primo satellite artificiale della storia, lanciato dall'Unione Sovietica", "Una stazione spaziale", "Un razzo americano"], answer: 1, why: "Una esfera metálica que enviaba solo «bip bip»: el primer satélite artificial, con un mensaje político fortísimo." },
      { q: "¿Qué dijo Yuri Gagarin al volver?", options: ["«La Terra è blu»", "«Vado più veloce del suono»", "«Ho visto gli alieni»", "«Mai più»"], answer: 0, why: "Gagarin, primer hombre en el espacio (1961), volvió con la frase famosa «La Terra è blu»." },
      { q: "¿Qué prometió Kennedy y cuándo se cumplió?", options: ["Marte entro il 2000", "Mandare un uomo sulla Luna entro la fine degli anni Sessanta: Apollo 11, 20 luglio 1969", "Una stazione spaziale", "Un satellite italiano"], answer: 1, why: "El programa Apolo logró el alunizaje el 20 de julio de 1969: «un piccolo passo per un uomo»." },
      { q: "¿Qué tiene de especial la ISS?", options: ["È russa soltanto", "È il progetto pacifico più costoso e complesso: 15 paesi che costruiscono insieme un laboratorio a 400 km", "È sulla Luna", "È un hotel spaziale"], answer: 1, why: "Quince países la construyeron juntos: la cooperación reemplazó a la competencia de la guerra fría." },
      { q: "¿Qué logro destaca el texto sobre Italia en el espacio?", options: ["Il primo uomo sulla Luna", "Il satellite San Marco (1964) e Samantha Cristoforetti, prima donna europea a comandare la ISS", "Il primo razzo privato", "Nessuno"], answer: 1, why: "Italia lanzó el San Marco en 1964 (primer satélite de una no superpotencia) y Cristoforetti comandó la ISS." },
    ],
    discuss: [
      { it: "«Chi controlla lo spazio, controlla il mondo»: oggi, con i satelliti privati, è ancora vero? Chi dovrebbe governare lo spazio?", es: "«Quien controla el espacio, controla el mundo»: hoy, con satélites privados, ¿sigue siendo cierto? ¿Quién debería gobernar el espacio?" },
      { it: "La cooperazione della ISS contro la guerra in Ucraina: può sopravvivere la scienza quando litigano i governi?", es: "La cooperación de la ISS frente a la guerra en Ucrania: ¿puede sobrevivir la ciencia cuando los gobiernos riñen?" },
      { it: "Concorrere o cooperare? Qual è stata, secondo te, la lezione più importante della corsa allo spazio?", es: "¿Competir o cooperar? ¿Cuál ha sido, según tú, la lección más importante de la carrera espacial?" },
    ],
  },
];
