/* ── Letture EXTRA · Paquete v9.10 · Parte 3: 5 storia ────────────────
   it-venezia-13 (B1), it-galileo-14 (B2), mon-mali-17 (B1),
   mon-industriale-18 (B2), mon-muro-19 (C1). 100% original.           */

import type { CefrLevel } from "./types";
import type { Lettura } from "./letture";

/* ═══ STORIA D'ITALIA NUOVE ══════════════════════════════════════════ */

export const STORIA_ITALIA_EXTRA: Lettura[] = [
  {
    id: "it-venezia-13",
    cat: "storia-italia",
    level: "B1",
    title: "La Serenissima: la repubblica del mare",
    titleEs: "La Serenísima: la república del mar",
    minutes: 5,
    lines: [
      { it: "Nel 421, secondo la leggenda, i primi abitanti fondarono Venezia su isolette paludose, fuggendo dalle invasioni barbariche che devastavano l'Italia. Nessuno poteva immaginare che quel villaggio di pescatori, nato dall'acqua, sarebbe diventato una delle potenze più ricche e durature della storia: la Repubblica di Venezia, chiamata «la Serenissima», sopravvissuta ben mille anni.", es: "En el 421, según la leyenda, los primeros habitantes fundaron Venecia sobre islotes pantanosos, huyendo de las invasiones bárbaras que devastaban Italia. Nadie podía imaginar que aquella aldea de pescadores, nacida del agua, se convertiría en una de las potencias más ricas y duraderas de la historia: la República de Venecia, llamada «la Serenísima», sobreviviente de nada menos que mil años." },
      { it: "Il segreto di Venezia stava nel suo rapporto con il mare. Mentre le altre città italiane combattevano tra loro per la terraferma, i veneziani guardarono verso est: il Mediterraneo orientale, Bisanzio, le spezie dell'Asia. Le loro navi, costruite in un cantiere gigantesco chiamato Arsenale, portavano in Europa pepe, seta, incenso e porcellane.", es: "El secreto de Venecia estaba en su relación con el mar. Mientras las demás ciudades italianas combatían entre sí por la tierra firme, los venecianos miraron hacia el este: el Mediterráneo oriental, Bizancio, las especias de Asia. Sus naves, construidas en un astillero gigantesco llamado Arsenal, llevaban a Europa pimienta, seda, incienso y porcelanas." },
      { it: "L'Arsenale era l'orgoglio della città: migliaia di operai, i «arsenalotti», lavoravano con un'organizzazione così moderna che alcuni storici lo considerano la prima fabbrica del mondo. Quando serviva una flotta, Venezia poteva armare cento galee in pochi mesi: una velocità che nessun nemico riusciva a eguagliare.", es: "El Arsenal era el orgullo de la ciudad: miles de obreros, los «arsenalotti», trabajaban con una organización tan moderna que algunos historiadores lo consideran la primera fábrica del mundo. Cuando hacía falta una flota, Venecia podía armar cien galeras en pocos meses: una velocidad que ningún enemigo lograba igualar." },
      { it: "Il governo della repubblica era strano e geniale: il Doge, il capo dello stato, non era un re ma un funzionario controllato da un complesso sistema di consigli e magistrature. I patrizi veneziani si riunivano nel Palazzo Ducale, e le leggi servivano a impedire che una sola famiglia diventasse troppo potente. Era una oligarchia, non una democrazia moderna, ma per i suoi tempi era un modello di stabilità.", es: "El gobierno de la república era extraño y genial: el Dux, el jefe del Estado, no era un rey sino un funcionario controlado por un complejo sistema de consejos y magistraturas. Los patricios venecianos se reunían en el Palacio Ducal, y las leyes servían para impedir que una sola familia se volviera demasiado poderosa. Era una oligarquía, no una democracia moderna, pero para su época era un modelo de estabilidad." },
      { it: "Il declino arrivò lentamente. Nel 1498 il portoghese Vasco de Gama aprì la rotta delle spezie attorno all'Africa: le carovane che passavano da Venezia persero valore. Poi le nuove potenze oceaniche — Spagna, Portogallo, Olanda, Inghilterra — spostarono il centro del commercio dal Mediterraneo all'Atlantico. La Serenissima, elegante e antica, si ritirò gradualmente dal commercio e si trasformò in una città del piacere, del carnevale e dell'arte.", es: "La decadencia llegó lentamente. En 1498 el portugués Vasco de Gama abrió la ruta de las especias alrededor de África: las caravanas que pasaban por Venecia perdieron valor. Luego las nuevas potencias oceánicas —España, Portugal, Holanda, Inglaterra— desplazaron el centro del comercio del Mediterráneo al Atlántico. La Serenísima, elegante y antigua, se retiró gradualmente del comercio y se transformó en una ciudad del placer, del carnaval y del arte." },
      { it: "Nel 1797 Napoleone Bonaparte invase l'Italia del nord e la millenaria repubblica cadde senza quasi combattere. Ma Venezia non scomparve: oggi è un museo a cielo aperto che affascina il mondo, e il suo antico spirito mercantile e cosmopolita vive ancora nei campielli, nei palazzi e nelle lingue dei suoi abitanti.", es: "En 1797 Napoleón Bonaparte invadió el norte de Italia y la milenaria república cayó casi sin combatir. Pero Venecia no desapareció: hoy es un museo a cielo abierto que fascina al mundo, y su antiguo espíritu mercantil y cosmopolita vive aún en los campi, en los palacios y en la lengua de sus habitantes." },
    ],
    glossary: [
      { it: "la Serenissima", es: "la Serenísima (apelativo de la República de Venecia)" },
      { it: "la galea", es: "la galera (nave de remo y vela)" },
      { it: "l'Arsenale", es: "el Arsenal (astillero veneciano)" },
      { it: "il Doge", es: "el Dux (jefe del Estado veneciano)" },
      { it: "la terraferma", es: "la tierra firme (el continente)" },
    ],
    questions: [
      { q: "¿Por qué llegaron los primeros habitantes a las islas de la laguna?", options: ["Per cercare l'oro", "Fuggendo dalle invasioni barbariche", "Per ordine di Roma", "Per la pesca"], answer: 1, why: "Según la leyenda, huían de las invasiones bárbaras que devastaban Italia." },
      { q: "¿Qué era el Arsenal?", options: ["Un palazzo ducale", "Un gigantesco cantiere navale", "Una chiesa famosa", "Un mercato di spezie"], answer: 1, why: "Era el astillero gigantesco donde miles de «arsenalotti» construían las naves; algunos lo consideran la primera fábrica del mundo." },
      { q: "¿Cómo se controlaba el poder del Dux?", options: ["Era un re assoluto", "Con un sistema di consigli e magistrature", "Con elezioni popolari", "Dal papa"], answer: 1, why: "No era re: un sistema complejo de consejos y magistraturas impedía que una sola familia acumulara demasiado poder." },
      { q: "¿Qué evento inició el declive comercial de Venecia?", options: ["La caduta di Roma", "La rotta delle spezie attorno all'Africa (1498)", "L'invenzione della stampa", "La peste del 1348"], answer: 1, why: "La ruta de Vasco de Gama alrededor de África devaluó las caravanas que pasaban por Venecia." },
      { q: "¿Cómo terminó la república en 1797?", options: ["Con una rivolta popolare", "Con un incendio", "Napoleone la invase e cadde quasi senza combattere", "Si unì all'Italia"], answer: 2, why: "Napoleón invadió el norte de Italia y la república milenaria cayó casi sin luchar." },
    ],
    discuss: [
      { it: "Venezia è nata dal nulla, in acqua, senza terra né risorse. Cosa può imparare il mondo di oggi da questa storia?", es: "Venecia nació de la nada, en el agua, sin tierra ni recursos. ¿Qué puede aprender el mundo actual de esta historia?" },
      { it: "Preferisci la Venezia mercantile e guerriera o quella del carnevale e dell'arte? Perché?", es: "¿Prefieres la Venecia mercantil y guerrera o la del carnaval y el arte? ¿Por qué?" },
      { it: "Conosci altre repubbliche antiche durate a lungo? Confrontale con la Serenissima.", es: "¿Conoces otras repúblicas antiguas que duraron mucho tiempo? Compáralas con la Serenísima." },
    ],
  },
  {
    id: "it-galileo-14",
    cat: "storia-italia",
    level: "B2",
    title: "Galileo Galilei: lo scienziato che guardò il cielo",
    titleEs: "Galileo Galilei: el científico que miró el cielo",
    minutes: 5,
    lines: [
      { it: "Nel 1609, a Padova, un professore di matematica di quarantacinque anni sentì parlare di una strana invenzione olandese: un tubo di vetro che faceva vedere gli oggetti lontani come se fossero vicini. Galileo Galilei, questo era il suo nome, capì subito il potenziale di quell'aggeggio, lo ricostruì con le sue mani e lo puntò — per primo nella storia — verso il cielo notturno.", es: "En 1609, en Padua, un profesor de matemáticas de cuarenta y cinco años oyó hablar de un extraño invento holandés: un tubo de vidrio que hacía ver los objetos lejanos como si estuvieran cerca. Galileo Galilei, así se llamaba, entendió de inmediato el potencial de aquel artilugio, lo reconstruyó con sus propias manos y lo apuntó —primero en la historia— hacia el cielo nocturno." },
      { it: "Ciò che vide cambiò per sempre la nostra immagine dell'universo. La Luna non era una sfera perfetta e liscia, come voleva la tradizione aristotelica: aveva montagne, crateri e valli. La Via Lattea non era una nuvola bianca: era un oceano di innumerevoli stelle. E attorno a Giove giravano quattro piccoli astri, i «satelliti medicei», che non giravano attorno alla Terra. Il cielo, fino ad allora considerato perfetto e immutabile, si rivelava pieno di sorprese.", es: "Lo que vio cambió para siempre nuestra imagen del universo. La Luna no era una esfera perfecta y lisa, como quería la tradición aristotélica: tenía montañas, cráteres y valles. La Vía Láctea no era una nube blanca: era un océano de innumerables estrellas. Y alrededor de Júpiter giraban cuatro pequeños astros, los «satélites mediceos», que no giraban alrededor de la Tierra. El cielo, hasta entonces considerado perfecto e inmutable, se revelaba lleno de sorpresas." },
      { it: "Galileo non si limitò a guardare: volle anche misurare. Studiò il moto dei corpi con esperimenti precisi — la leggenda lo vuole mentre lascia cadere sfere di peso diverso dalla Torre di Pisa — e scoprì che un pendolo oscilla sempre nello stesso tempo. Osservazione, esperimento, misura: questo metodo, oggi ovvio, era allora rivoluzionario. Prima di Galileo si cercava la verità nei libri antichi; dopo Galileo si cerca nei fatti.", es: "Galileo no se limitó a mirar: quiso también medir. Estudió el movimiento de los cuerpos con experimentos precisos —la leyenda lo quiere dejando caer esferas de distinto peso desde la Torre de Pisa— y descubrió que un péndulo oscila siempre en el mismo tiempo. Observación, experimento, medida: este método, hoy evidente, era entonces revolucionario. Antes de Galileo se buscaba la verdad en los libros antiguos; después de Galileo se busca en los hechos." },
      { it: "Ma le sue scoperte lo portarono presto in conflitto con la Chiesa. Galileo difendeva la teoria di Copernico, secondo cui la Terra gira attorno al Sole e non il contrario, e la difendeva in italiano volgare, non in latino: voleva che tutti potessero leggerla, non solo i dotti. Nel 1633, dopo un lungo processo, il Tribunale dell'Inquisizione lo dichiarò «veementemente sospetto di eresia» e lo obbligò ad abiurare, cioè a rinnegare pubblicamente le sue idee.", es: "Pero sus descubrimientos lo llevaron pronto a un conflicto con la Iglesia. Galileo defendía la teoría de Copérnico, según la cual la Tierra gira alrededor del Sol y no al revés, y la defendía en italiano vulgar, no en latín: quería que todos pudieran leerla, no solo los eruditos. En 1633, tras un largo proceso, el Tribunal de la Inquisición lo declaró «vehementemente sospechoso de herejía» y lo obligó a abjurar, es decir, a renegar públicamente de sus ideas." },
      { it: "La leggenda racconta che, dopo l'abiura, Galileo sussurrò: «Eppur si muove» — y sin embargo se mueve. La frase è probabilmente inventata, ma descrive bene la situazione: costretto al silenzio, lo scienziato passò gli ultimi anni della sua vita in segregazione nella sua villa di Arcetri, vicino a Firenze, ormai cieco. Lì scrisse in segreto i «Discorsi intorno a due nuove scienze», l'opera che fondava la fisica moderna, fatta uscire di nascosto e pubblicata in Olanda.", es: "La leyenda cuenta que, después de la abjuración, Galileo susurró: «Eppur si muove» —y sin embargo se mueve. La frase es probablemente inventada, pero describe bien la situación: obligado al silencio, el científico pasó los últimos años de su vida recluido en su villa de Arcetri, cerca de Florencia, ya ciego. Allí escribió en secreto los «Discursos sobre dos ciencias nuevas», la obra que fundaba la física moderna, sacada de contrabando y publicada en Holanda." },
      { it: "La storia di Galileo insegna che la scienza avanza a volte contro l'autorità, y che la verità ha bisogno di tempo. Nel 1992, trecentocinquantanove anni dopo il processo, papa Giovanni Paolo II ha riconosciuto formalmente gli errori del Tribunale ecclesiastico. Oggi Galileo è considerato il padre del metodo scientifico moderno, e la sua vita è un monito che nessuna epoca dovrebbe dimenticare: guardare il cielo non è mai stato un atto innocente.", es: "La historia de Galileo enseña que la ciencia avanza a veces contra la autoridad, y que la verdad necesita tiempo. En 1992, trescientos cincuenta y nueve años después del proceso, el papa Juan Pablo II reconoció formalmente los errores del Tribunal eclesiástico. Hoy Galileo es considerado el padre del método científico moderno, y su vida es una advertencia que ninguna época debería olvidar: mirar el cielo nunca ha sido un acto inocente." },
    ],
    glossary: [
      { it: "l'aggeggio", es: "el artilugio, el cacharro" },
      { it: "il pendolo", es: "el péndulo" },
      { it: "abiurare", es: "abjurar (renegar públicamente)" },
      { it: "il volgare", es: "la lengua vulgar (el italiano frente al latín)" },
      { it: "il monito", es: "la advertencia, la amonestación" },
    ],
    questions: [
      { q: "¿Qué hizo Galileo en 1609?", options: ["Inventò il microscopio", "Ricostruì il telescopio e lo puntó per primo verso il cielo", "Scrisse i Discorsi", "Andò a Roma"], answer: 1, why: "Al enterarse del invento holandés, lo reconstruyó y fue el primero en apuntarlo al cielo nocturno." },
      { q: "¿Qué revelaron sus observaciones de Júpiter?", options: ["Che aveva gli anelli", "Quattro satelliti che non giravano attorno alla Terra", "Che era abitato", "Che era la stella più vicina"], answer: 1, why: "Los «satélites mediceos» giraban alrededor de Júpiter, no de la Tierra: un golpe a la cosmología geocéntrica." },
      { q: "¿En qué consistía el método revolucionario de Galileo?", options: ["Cercare la verità nei libri antichi", "Osservazione, esperimento e misura", "Chiedere ai filosofi", "Seguire solo la Chiesa"], answer: 1, why: "Antes de Galileo la verdad se buscaba en los libros antiguos; después, en los hechos: observación, experimento y medida." },
      { q: "¿Por qué usaba Galileo el italiano vulgar y no el latín?", options: ["Non conosceva il latino", "Voleva che tutti potessero leggere le sue idee", "Era vietato usare il latino", "Per scherzo"], answer: 1, why: "Quería que todos pudieran leer sus ideas, no solo los eruditos." },
      { q: "¿Cuándo reconoció la Iglesia los errores del proceso?", options: ["Nel 1633", "Nel 1797", "Nel 1992, con Giovanni Paolo II", "Mai"], answer: 2, why: "En 1992, 359 años después del proceso, Juan Pablo II reconoció formalmente los errores del Tribunal." },
    ],
    discuss: [
      { it: "Perché, secondo te, le idee nuove fanno così paura? Conosci altri scienziati perseguitati?", es: "¿Por qué, según tú, las ideas nuevas dan tanto miedo? ¿Conoces otros científicos perseguidos?" },
      { it: "Galileo scriveva in volgare per farsi capire da tutti. Gli scienziati di oggi comunicano bene con il pubblico? Perché no?", es: "Galileo escribía en vulgar para hacerse entender por todos. ¿Comunican bien los científicos actuales con el público? ¿Por qué no?" },
      { it: "«Eppur si muove»: la frase è inventata, ma perché è diventata così famosa?", es: "«Eppur si muove»: la frase es inventada, ¿por qué se volvió tan famosa?" },
    ],
  },
];

/* ═══ STORIA DEL MONDO NUOVE ═════════════════════════════════════════ */

export const STORIA_MONDO_EXTRA: Lettura[] = [
  {
    id: "mon-mali-17",
    cat: "storia-mondo",
    level: "B1",
    title: "Mansa Musa e l'impero del Mali",
    titleEs: "Mansa Musa y el imperio de Malí",
    minutes: 5,
    lines: [
      { it: "Nel XIV secolo, mentre l'Europa viveva carestie e guerre, in Africa occidentale fioriva uno degli stati più ricchi e organizzati del mondo: l'impero del Mali. Si estendeva tra il deserto del Sahara e le foreste tropicali, attraversato dal fiume Niger, e controllava le miniere d'oro più produttive del pianeta. Si stima che fino a metà dell'oro circolante nel mondo medievale venisse da lì.", es: "En el siglo XIV, mientras Europa vivía hambrunas y guerras, en África occidental florecía uno de los estados más ricos y organizados del mundo: el imperio de Malí. Se extendía entre el desierto del Sahara y los bosques tropicales, cruzado por el río Níger, y controlaba las minas de oro más productivas del planeta. Se estima que hasta la mitad del oro circulante en el mundo medieval venía de allí." },
      { it: "Alla guida dell'impero stava il «Mansa», che significa «re dei re» o «imperatore». Il più famoso fu Mansa Musa, salito al trono nel 1312. Sotto il suo governo il Mali raggiunse la massima estensione: città come Timbuctù e Gao divennero centri di commercio e di sapere che attiravano mercanti e studiosi da tutto il mondo islamico, dal Marocco all'Egitto alla penisola arabica.", es: "A la cabeza del imperio estaba el «Mansa», que significa «rey de reyes» o «emperador». El más famoso fue Mansa Musa, subido al trono en 1312. Bajo su gobierno Malí alcanzó la máxima extensión: ciudades como Tombuctú y Gao se volvieron centros de comercio y de saber que atraían mercaderes y estudiosos de todo el mundo islámico, de Marruecos a Egipto y la península arábiga." },
      { it: "Timbuctù, in particolare, era leggendaria. Nella sua università, la Sankoré, si studiava teologia, diritto, astronomia e matematica, e si copiavano manoscritti preziosi che si vendevano più cari dell'oro. Ancora oggi, in biblioteche e archivi familiari del Sahel, si conservano centinaia di migliaia di questi manoscritti: una prova tangibile che l'Africa non era solo terra di tradizione orale, ma anche di alta cultura scritta.", es: "Tombuctú, en particular, era legendaria. En su universidad, la Sankoré, se estudiaba teología, derecho, astronomía y matemáticas, y se copiaban manuscritos preciosos que se vendían más caros que el oro. Aún hoy, en bibliotecas y archivos familiares del Sahel, se conservan cientos de miles de esos manuscritos: prueba tangible de que África no era solo tierra de tradición oral, sino también de alta cultura escrita." },
      { it: "Mansa Musa divenne famoso in tutto il mondo per un viaggio. Nel 1324 partì per il pellegrinaggio alla Mecca, l'Hajj, con una carovana straordinaria: si parla di decine di migliaia di persone, centinaia di cammelli carichi d'oro e una corte intera in cammino. Passando dal Cairo, l'imperatore distribuì così tanto oro che il valore del metallo prezioso crollò sul mercato egiziano per anni. Per gli europei, che ne sentirono parlare, divenne semplicemente «l'uomo più ricco del mondo».", es: "Mansa Musa se hizo famoso en todo el mundo por un viaje. En 1324 partió hacia la peregrinación a La Meca, el Hajj, con una caravana extraordinaria: se habla de decenas de miles de personas, cientos de camellos cargados de oro y una corte entera en marcha. Al pasar por El Cairo, el emperador repartió tanto oro que el valor del metal precioso se desplomó en el mercado egipcio durante años. Para los europeos, que oyeron hablar de él, se volvió simplemente «el hombre más rico del mundo»." },
      { it: "Ma Mansa Musa non fu solo un uomo ricco. Fu anche un costruttore: fece erigere moschee monumentali — come quella di Djenné, capolavoro di architettura in terra cruda che esiste ancora oggi — e portò in Mali architetti e studiosi dal Medio Oriente. Il suo regno è considerato l'età dell'oro della storia dell'Africa occidentale, ricordato con orgoglio dalle generazioni successive.", es: "Pero Mansa Musa no fue solo un hombre rico. Fue también un constructor: hizo erigir mezquitas monumentales —como la de Djenné, obra maestra de arquitectura en tierra cruda que existe todavía hoy— y llevó a Malí arquitectos y estudiosos de Medio Oriente. Su reinado es considerado la edad de oro de la historia de África occidental, recordado con orgullo por las generaciones siguientes." },
      { it: "L'impero del Mali declinò lentamente nei secoli successivi, tra successioni incerte e la concorrenza di nuovi stati. Ma la sua memoria resta un simbolo potente: ricorda che la ricchezza e il sapere non sono mai appartenuti a un solo continente, e che la storia dell'Africa — spesso raccontata solo attraverso la colonizzazione — ha radici molto più antiche e gloriose.", es: "El imperio de Malí declinó lentamente en los siglos siguientes, entre sucesiones inciertas y la competencia de nuevos estados. Pero su memoria queda como un símbolo poderoso: recuerda que la riqueza y el saber nunca pertenecieron a un solo continente, y que la historia de África —a menudo contada solo a través de la colonización— tiene raíces mucho más antiguas y gloriosas." },
    ],
    glossary: [
      { it: "il Mansa", es: "el Mansa (título del emperador de Malí)" },
      { it: "il pellegrinaggio (l'Hajj)", es: "la peregrinación (a La Meca)" },
      { it: "la carovana", es: "la caravana" },
      { it: "la terra cruda", es: "la tierra cruda (adobe, material de construcción)" },
      { it: "l'età dell'oro", es: "la edad de oro" },
    ],
    questions: [
      { q: "¿Por qué era tan rico el imperio de Malí?", options: ["Per il petrolio", "Controllava le miniere d'oro più produttive del pianeta", "Per le tasse sui romani", "Per il commercio della seta"], answer: 1, why: "Hasta la mitad del oro circulante del mundo medieval venía de sus minas." },
      { q: "¿Qué se estudiaba en la universidad Sankoré de Tombuctú?", options: ["Solo religione", "Teologia, diritto, astronomia e matematica", "Solo commercio", "Niente, non esisteva"], answer: 1, why: "Era un centro de saber completo; sus manuscritos se vendían más caros que el oro." },
      { q: "¿Qué ocurrió en El Cairo durante el paso de Mansa Musa?", options: ["Fu arrestato", "Distribuì così tanto oro che il suo valore crollò per anni", "Comprò la città", "Si ammalò"], answer: 1, why: "Repartió tanto oro que el precio del metal se desplomó en el mercado egipcio durante años." },
      { q: "¿Qué queda hoy de la época de Mansa Musa?", options: ["Niente", "La moschea di Djenné e centinaia di migliaia di manoscritti", "Solo leggende", "Un museo al Cairo"], answer: 1, why: "La mezquita de Djenné sigue en pie y se conservan cientos de miles de manuscritos en el Sahel." },
      { q: "¿Qué simboliza hoy la memoria del imperio de Malí?", options: ["Che l'Africa non ha storia", "Che ricchezza e sapere non appartengono a un solo continente", "Che l'oro non ha valore", "Che l'Europa era superiore"], answer: 1, why: "Recuerda que la riqueza y el saber nunca fueron monopolio de un solo continente." },
    ],
    discuss: [
      { it: "Perché, secondo te, la storia dell'Africa è così poco conosciuta nelle scuole? Cosa si dovrebbe insegnare di più?", es: "¿Por qué, según tú, la historia de África es tan poco conocida en las escuelas? ¿Qué se debería enseñar más?" },
      { it: "Confronta Mansa Musa con un sovrano ricco e famoso della storia del tuo paese: chi era più potente?", es: "Compara a Mansa Musa con un soberano rico y famoso de la historia de tu país: ¿quién era más poderoso?" },
      { it: "I manoscritti di Timbuctù rischiano di scomparire per il caldo, la sabbia e i conflitti. Chi ha la responsabilità di salvarli?", es: "Los manuscritos de Tombuctú riesgan desaparecer por el calor, la arena y los conflictos. ¿Quién tiene la responsabilidad de salvarlos?" },
    ],
  },
  {
    id: "mon-industriale-18",
    cat: "storia-mondo",
    level: "B2",
    title: "La rivoluzione industriale: il mondo cambia marcia",
    titleEs: "La revolución industrial: el mundo cambia de marcha",
    minutes: 6,
    lines: [
      { it: "Alla fine del Settecento, in Inghilterra, accadde qualcosa che non era mai successo nella storia dell'umanità: per la prima volta il reddito medio delle persone iniziò a crescere in modo costante, generazione dopo generazione. Prima di quel momento, per migliaia di anni, la vita economica era rimasta sostanzialmente immobile. Gli storici chiamano questa svolta «rivoluzione industriale», e molti la considerano l'evento più importante dopo l'invenzione dell'agricoltura.", es: "A finales del siglo XVIII, en Inglaterra, ocurrió algo que jamás había sucedido en la historia de la humanidad: por primera vez el ingreso promedio de las personas empezó a crecer de manera constante, generación tras generación. Antes de ese momento, durante miles de años, la vida económica había permanecido esencialmente inmóvil. Los historiadores llaman a ese giro «revolución industrial», y muchos la consideran el evento más importante desde la invención de la agricultura." },
      { it: "Il motore — in tutti i sensi — della trasformazione fu la macchina a vapore. James Watt ne perfezionò il brevetto negli anni Sessanta del Settecento, e improvvisamente l'energia non dipendeva più dai muscoli degli uomini e degli animali, né dal vento o dall'acqua dei fiumi. Una macchina poteva pompare acqua dalle miniere di carbone, muovere i telai nei cotonifici e, poco dopo, trainare treni a una velocità che nessun essere umano aveva mai raggiunto su terra.", es: "El motor —en todos los sentidos— de la transformación fue la máquina de vapor. James Watt perfeccionó su patente en los años sesenta del Setecientos, y de repente la energía ya no dependía de los músculos de hombres y animales, ni del viento o el agua de los ríos. Una máquina podía bombear agua de las minas de carbón, mover los telares en las fábricas de algodón y, poco después, arrastrar trenes a una velocidad que ningún ser humano había alcanzado jamás en tierra." },
      { it: "Le conseguenze sociali furono enormi e traumatiche. Le campagne si svuotarono e le città si riempirono: Manchester, piccola cittadina di mercato, divenne in pochi decenni una metropoli fumosa di fabbriche e operai. Le condizioni di lavoro erano durissime: giornate di dodici-quattordici ore, salari bassi, fabbriche piene di polvere e di rumore, donne e bambini impiegati nei lavori più pericolosi. La speranza di vita degli operai urbani era, paradossalmente, più bassa di quella dei contadini.", es: "Las consecuencias sociales fueron enormes y traumáticas. Los campos se vaciaron y las ciudades se llenaron: Mánchester, pequeña ciudad de mercado, se convirtió en pocas décadas en una metrópoli humeante de fábricas y obreros. Las condiciones de trabajo eran durísimas: jornadas de doce a catorce horas, salarios bajos, fábricas llenas de polvo y ruido, mujeres y niños empleados en los trabajos más peligrosos. La esperanza de vida de los obreros urbanos era, paradójicamente, más baja que la de los campesinos." },
      { it: "Proprio da quelle sofferenze nacquero le idee che avrebbero dominato i due secoli successivi. Gli operai cominciarono a organizzarsi in associazioni e sindacati; il filosofo tedesco Karl Marx, osservando le fabbriche inglesi, elaborò una teoria che vedeva nello sfruttamento operaio il motore segreto del capitalismo; e gli stati stessi, sotto pressione, iniziarono a legiferare: prime leggi sul lavoro minorile, limiti alle ore, ispezioni nelle fabbriche. Il welfare state moderno è figlio diretto della rivoluzione industriale.", es: "Justo de esos sufrimientos nacieron las ideas que dominarían los dos siglos siguientes. Los obreros empezaron a organizarse en asociaciones y sindicatos; el filósofo alemán Karl Marx, observando las fábricas inglesas, elaboró una teoría que veía en la explotación obrera el motor secreto del capitalismo; y los propios Estados, bajo presión, empezaron a legislar: primeras leyes sobre el trabajo infantil, límites de horario, inspecciones fabriles. El Estado de bienestar moderno es hijo directo de la revolución industrial." },
      { it: "La rivoluzione si diffuse a ondate. Dopo l'Inghilterra toccò al Belgio e alla Francia, poi alla Germania unificata e agli Stati Uniti, e infine — tra fine Ottocento e Novecento — al Giappone e all'Italia del nord, dove Milano, Torino e Genova formarono il «triangolo industriale». Ogni ondata portava tecnologie nuove: l'acciaio, la chimica, l'elettricità, il motore a combustione. Il mondo, che per secoli era cambiato alla velocità del cavallo, cominciò a cambiare alla velocità della luce.", es: "La revolución se difundió por oleadas. Después de Inglaterra tocó a Bélgica y Francia, luego a la Alemania unificada y a Estados Unidos, y finalmente —entre fines del Ochocientos y el Novecientos— a Japón y a la Italia del norte, donde Milán, Turín y Génova formaron el «triángulo industrial». Cada oleada traía tecnologías nuevas: el acero, la química, la electricidad, el motor de combustión. El mundo, que durante siglos había cambiado a la velocidad del caballo, empezó a cambiar a la velocidad de la luz." },
      { it: "Oggi viviamo forse una trasformazione analoga: la rivoluzione digitale. Come allora, le tecnologie cambiano più velocemente delle leggi e della cultura; come allora, ci sono vincitori e vinti, città che nascono e città che muoiono; e come allora, la domanda finale è la stessa: il progresso tecnologico renderà la vita migliore per tutti, o solo per pochi? La risposta, scrivono gli storici, non è scritta nelle macchine: è scritta nelle scelte delle società che le usano.", es: "Hoy vivimos quizás una transformación análoga: la revolución digital. Como entonces, las tecnologías cambian más rápido que las leyes y la cultura; como entonces, hay ganadores y perdedores, ciudades que nacen y ciudades que mueren; y como entonces, la pregunta final es la misma: ¿el progreso tecnológico hará mejor la vida para todos, o solo para pocos? La respuesta, escriben los historiadores, no está escrita en las máquinas: está escrita en las elecciones de las sociedades que las usan." },
    ],
    glossary: [
      { it: "la macchina a vapore", es: "la máquina de vapor" },
      { it: "il telaio", es: "el telar" },
      { it: "il cotonificio", es: "la fábrica de algodón" },
      { it: "il sindacato", es: "el sindicato" },
      { it: "legiferare", es: "legislar" },
      { it: "il welfare state", es: "el Estado de bienestar" },
    ],
    questions: [
      { q: "¿Qué ocurrió por primera vez en la historia a fines del Setecientos?", options: ["La scoperta dell'America", "Il reddito medio iniziò a crescere in modo costante", "La caduta di Roma", "L'invenzione della scrittura"], answer: 1, why: "Por primera vez el ingreso promedio creció de forma sostenida, generación tras generación." },
      { q: "¿Qué permitió la máquina de vapor de Watt?", options: ["Niente di nuovo", "L'energia non dipendeva più da muscoli, vento o acqua", "Solo viaggiare per mare", "L'agricoltura"], answer: 1, why: "La energía dejó de depender de músculos, viento o ríos: podía bombear, tejer y arrastrar trenes." },
      { q: "¿Cómo eran las condiciones de trabajo descritas?", options: ["Otto ore e buoni salari", "Giornate di 12-14 ore, salari bassi, donne e bambini nei lavori pericolosi", "Lavoro da casa", "Ferie pagate"], answer: 1, why: "Jornadas de doce a catorce horas, salarios bajos y trabajo infantil en las tareas más peligrosas." },
      { q: "¿Qué nació directamente de la revolución industrial, según el texto?", options: ["L'impero romano", "Il welfare state moderno", "Le lingue nazionali", "La religione"], answer: 1, why: "Leyes laborales, sindicatos y, con el tiempo, el Estado de bienestar moderno." },
      { q: "¿Cuál fue el «triángulo industrial» italiano?", options: ["Roma, Napoli, Palermo", "Milano, Torino, Genova", "Venezia, Bologna, Firenze", "Bari, Cagliari, Trieste"], answer: 1, why: "Milán, Turín y Génova lideraron la industrialización del norte italiano." },
    ],
    discuss: [
      { it: "La tua città o regione è stata trasformata dall'industria? Racconta come e con quali conseguenze.", es: "¿Tu ciudad o región fue transformada por la industria? Cuenta cómo y con qué consecuencias." },
      { it: "Il testo paragona la rivoluzione industriale a quella digitale: quali somiglianze e differenze vedi tu?", es: "El texto compara la revolución industrial con la digital: ¿qué semejanzas y diferencias ves tú?" },
      { it: "«La risposta è scritta nelle scelte delle società, non nelle macchine»: sei d'accordo? Fai un esempio attuale.", es: "«La respuesta está escrita en las elecciones de las sociedades, no en las máquinas»: ¿estás de acuerdo? Da un ejemplo actual." },
    ],
  },
  {
    id: "mon-muro-19",
    cat: "storia-mondo",
    level: "C1",
    title: "1989: la caduta del Muro di Berlino",
    titleEs: "1989: la caída del Muro de Berlín",
    minutes: 6,
    lines: [
      { it: "Nella notte tra il 12 e il 13 agosto 1961, gli abitanti di Berlino si addormentarono in una città e si svegliarono in due. All'alba, i soldati della Germania Est avevano chiuso con reticolati e blocchi di cemento tutte le strade che collegavano il settore sovietico ai settori occidentali. Nei giorni successivi il filo spinato diventò muro: centocinquantacinque chilometri di calcestruzzo alto quasi quattro metri, sormontato da filo spinato e sorvegliato da torri di guardia. Lo scopo dichiarato era fermare l'emigrazione: la Germania Est stava perdendo i suoi cittadini migliori — medici, ingegneri, professori — che fuggivano a ovest attraverso Berlino, l'unica porta rimasta aperta nella cortina di ferro.", es: "En la noche del 12 al 13 de agosto de 1961, los habitantes de Berlín se durmieron en una ciudad y despertaron en dos. Al amanecer, los soldados de Alemania Oriental habían cerrado con alambradas y bloques de cemento todas las calles que conectaban el sector soviético con los sectores occidentales. En los días siguientes el alambre de púas se volvió muro: ciento cincuenta y cinco kilómetros de hormigón de casi cuatro metros de alto, coronado con alambre de púas y vigilado por torres de guardia. El objetivo declarado era frenar la emigración: Alemania Oriental estaba perdiendo a sus mejores ciudadanos —médicos, ingenieros, profesores— que huían al oeste a través de Berlín, la única puerta que quedaba abierta en la cortina de hierro." },
      { it: "Il muro divise famiglie, amici e vite. Chi tentava di passarlo rischiava tutto: almeno centoquaranta persone morirono nel tentativo, anche se il numero esatto è ancora oggi discusso. Altri riuscirono con mezzi incredibili — tunnel scavati sotto terra, mongolfiere, auto modificate, corde tese sopra il filo spinato. La parola «Berlino Est» diventò sinonimo di sorveglianza: la Stasi, la polizia segreta, aveva schedato milioni di cittadini e reclutato un esercito di informatori, persino tra mariti e mogli.", es: "El muro dividió familias, amigos y vidas. Quien intentaba cruzarlo lo arriesgaba todo: al menos ciento cuarenta personas murieron en el intento, aunque el número exacto sigue en discusión. Otros lo lograron con medios increíbles —túneles cavados bajo tierra, globos aerostáticos, autos modificados, cuerdas tendidas sobre el alambre—. La expresión «Berlín Este» se volvió sinónimo de vigilancia: la Stasi, la policía secreta, había fichado a millones de ciudadanos y reclutado un ejército de informantes, incluso entre maridos y esposas." },
      { it: "Per quasi trent'anni il muro sembrò eterno. Poi, all'improvviso, tutto crollò in pochi mesi — letteralmente e politicamente. Nell'estate del 1989 l'Ungheria aprì il confine con l'Austria, e migliaia di tedeschi orientali fuggirono attraverso quel varco. A Lipsia e a Dresda le manifestazioni di lunedì crescevano di settimana in settimana, con lo slogan «Wir sind das Volk» — nosotros siamo il popolo. A Mosca, il leader sovietico Michail Gorbaciov aveva già fatto capire che l'Armata Rossa non sarebbe intervenuta a salvare i regimi alleati: l'era delle ingerenze era finita.", es: "Durante casi treinta años el muro pareció eterno. Luego, de repente, todo se derrumbó en pocos meses —literal y políticamente—. En el verano de 1989 Hungría abrió la frontera con Austria, y miles de alemanes orientales huyeron por esa brecha. En Leipzig y Dresde las manifestaciones de los lunes crecían semana a semana, con la consigna «Wir sind das Volk» —nosotros somos el pueblo—. En Moscú, el líder soviético Mijaíl Gorbachov ya había dejado claro que el Ejército Rojo no intervendría para salvar a los regímenes aliados: la era de las injerencias había terminado." },
      { it: "La sera del 9 novembre 1989 accadde l'impensabile. Durante una conferenza stampa confusa, un portavoce del governo tedesco-orientale annunciò, mal leggendo un documento, che i permessi di viaggio verso l'Occidente sarebbero stati concessi «immediatamente, senza ritardi». Migliaia di berlinesi orientali si riversarono ai checkpoints: le guardie, senza ordini chiari e di fronte alla folla, alla fine alzarono le barriere. Quella notte, davanti agli occhi del mondo intero, i berlinesi si abbracciarono sulla Linea della morte, ballarono sul muro e attaccarono il cemento con martelli e scalpelli — i «Mauerspechte», i «picchi del muro», che volevano portarsi a casa un frammento della storia.", es: "La noche del 9 de noviembre de 1989 ocurrió lo impensable. Durante una conferencia de prensa confusa, un portavoz del gobierno germano-oriental anunció, leyendo mal un documento, que los permisos de viaje hacia Occidente se concederían «inmediatamente, sin demora». Miles de berlinenses orientales se volcaron hacia los puestos de control: los guardias, sin órdenes claras y frente a la multitud, terminaron levantando las barreras. Esa noche, ante los ojos del mundo entero, los berlinenses se abrazaron sobre la Línea de la muerte, bailaron sobre el muro y atacaron el hormigón con martillos y cinceles —los «Mauerspechte», los «carpinteros del muro», que querían llevarse a casa un fragmento de la historia." },
      { it: "La riunificazione tedesca arrivò meno di un anno dopo, il 3 ottobre 1990. Ma le ferite del muro non guarirono con la firma dei trattati: per decenni l'est e l'ovest della Germania hanno parlato due lingue economiche diverse, con salari, opportunità e perfino vocabolari differenti. Ancora oggi, più di trent'anni dopo, le differenze si sentono nei dati sull'occupazione, sui salari e nei voti politici.", es: "La reunificación alemana llegó menos de un año después, el 3 de octubre de 1990. Pero las heridas del muro no sanaron con la firma de los tratados: durante décadas el este y el oeste de Alemania hablaron dos lenguas económicas distintas, con salarios, oportunidades y hasta vocabularios diferentes. Todavía hoy, más de treinta años después, las diferencias se sienten en los datos de empleo, en los salarios y en los votos políticos." },
      { it: "Il muro di Berlino resta l'icona del Novecento perché racconta in un solo oggetto tutte le sue contraddizioni: la divisione del mondo in blocchi, la paura reciproca, il coraggio delle persone comuni, la velocità con cui ciò che sembra eterno può cadere. Ne restano solo pochi tratti, conservati come monumento e coperti di arte e di memoria. E i turisti che oggi passeggiano lungo la Spree, tra grattacieli e caffè all'aperto, camminano sopra tunnel e memorie di cui il cemento non ha mai raccontato tutta la storia.", es: "El muro de Berlín queda como el ícono del siglo XX porque cuenta en un solo objeto todas sus contradicciones: la división del mundo en bloques, el miedo recíproco, el coraje de la gente común, la velocidad con que lo que parece eterno puede caer. Solo quedan algunos tramos, conservados como monumento y cubiertos de arte y de memoria. Y los turistas que hoy pasean junto al Spree, entre rascacielos y cafés al aire libre, caminan sobre túneles y recuerdos de los que el hormigón nunca contó toda la historia." },
    ],
    glossary: [
      { it: "il reticolato", es: "la alambrada" },
      { it: "la cortina di ferro", es: "la cortina de hierro" },
      { it: "schedare", es: "fichar (registrar en archivos policiales)" },
      { it: "il varco", es: "la brecha, el paso" },
      { it: "l'ingerenza", es: "la injerencia" },
      { it: "il checkpoint", es: "el puesto de control" },
    ],
    questions: [
      { q: "¿Cuál era el objetivo declarado del muro?", options: ["Difendersi da un attacco militare", "Fermare l'emigrazione verso l'ovest", "Proteggere i monumenti", "Separare le lingue"], answer: 1, why: "Alemania Oriental perdía a sus profesionales, que huían al oeste a través de Berlín." },
      { q: "¿Qué significaba el eslogan «Wir sind das Volk»?", options: ["Viva la libertad", "Nosotros somos el pueblo", "Abajo el muro", "Queremos viajar"], answer: 1, why: "Fue la consigna de las manifestaciones de los lunes en Leipzig y Dresde." },
      { q: "¿Qué papel jugó Gorbachov, según el texto?", options: ["Ordinò di costruire il muro", "Fece capire che l'Armata Rossa non avrebbe salvato i regimi alleati", "Attaccò Berlino", "Finanziò la riunificazione"], answer: 1, why: "Sin el paraguas soviético, los regímenes del este perdieron su sostento militar: la era de las injerencias había terminado." },
      { q: "¿Cómo se abrió el muro la noche del 9 de noviembre?", options: ["Con un attacco militare", "Un annuncio confuso in conferenza stampa e folle ai checkpoint senza ordini chiari", "Con un trattato firmato al mattino", "Con un referendum"], answer: 1, why: "Un portavoz leyó mal un documento; ante la multitud, las guardias terminaron levantando las barreras." },
      { q: "¿Qué fueron los «Mauerspechte»?", options: ["Soldati della Stasi", "Berlinesi che attaccavano il muro con martelli per portarsi a casa frammenti", "I costruttori del muro", "Turisti giapponesi"], answer: 1, why: "Los «picchi del muro» martillaban el hormigón para llevarse un fragmento de historia." },
    ],
    discuss: [
      { it: "Hai vissuto, o conosci qualcuno che ha vissuto, una divisione simile — un muro fisico o simbolico? Racconta.", es: "¿Has vivido, o conoces a alguien que haya vivido, una división parecida —un muro físico o simbolico? Cuenta." },
      { it: "Perché ciò che sembra eterno può cadere così in fretta? Fai altri esempi della storia.", es: "¿Por qué lo que parece eterno puede caer tan rápido? Da otros ejemplos de la historia." },
      { it: "«I muri di oggi non sono di cemento»: quali barriere moderne — digitali, economiche, culturali — paragoneresti al Muro di Berlino?", es: "«Los muros de hoy no son de hormigón»: ¿qué barreras modernas —digitales, económicas, culturales— compararías con el Muro de Berlín?" },
    ],
  },
];
