import type { Exercise } from "../types";

/* ── Ejercicios EXTRA · paquete de expansión v1.1 ─────────────────────
   Cubre las 32 lecciones nuevas (u-zero-3 → u-c2-3), las 8 lecturas
   nuevas, las 6 escuchas nuevas y los laboratorios de números/verbos. */

export const EXERCISES_EXTRA: Exercise[] = [
  /* ═══ A1 · tiempo libre, verbos, mesa, cuantificadores, tiempo ═══ */
  { id: "ex-a1-031", type: "mc", level: "A1", topic: "pronomi", prompt: "Completa: “Mi ___ la pizza.” (me gusta)",
    options: ["piace", "piacciono", "piacevano", "piacono"], answer: 0, explain: "Singular → mi piace. Plural → mi piacciono (mi piacciono gli spaghetti)." },
  { id: "ex-a1-032", type: "mc", level: "A1", topic: "pronomi", prompt: "Completa: “Mi ___ gli spaghetti.”",
    options: ["piacciono", "piace", "piaceva", "piacere"], answer: 0, explain: "Sustantivo plural → piacciono." },
  { id: "ex-a1-033", type: "mc", level: "A1", topic: "presente", prompt: "Completa: “Io ___ italiano.” (parlare)",
    options: ["parlo", "parli", "parla", "parliamo"], answer: 0, explain: "Verbos en -are: io parlo, tu parli, lui parla." },
  { id: "ex-a1-034", type: "fill", level: "A1", topic: "presente", prompt: "Escribe el verbo entre paréntesis: “Tu ___ la pasta ogni giorno.” (mangiare)",
    sentence: "Tu ___ la pasta ogni giorno.", accepted: ["mangi"], explain: "-are, 2ª persona: tu mangi." },
  { id: "ex-a1-035", type: "mc", level: "A1", topic: "presente", prompt: "Completa: “Lei non ___ l'italiano.” (capire)",
    options: ["capisce", "capo", "capite", "capiscono"], answer: 0, explain: "Verbos -ire con -isc: capire → lei capisce." },
  { id: "ex-a1-036", type: "mc", level: "A1", topic: "vocabolario", prompt: "¿Qué es “la colazione”?",
    options: ["El desayuno", "La comida", "La cena", "La merienda"], answer: 0, explain: "colazione = desayuno; pranzo = comida; cena = cena; merenda = merienda." },
  { id: "ex-a1-037", type: "order", level: "A1", topic: "situazioni", prompt: "Ordena: “Un caffè e un cornetto, per favore.”",
    words: ["caffè", "Un", "cornetto", "un", "e", "per", "favore"], answer: ["Un", "caffè", "e", "un", "cornetto", ",", "per", "favore"], explain: "El pedido cortés clásico del bar italiano." },
  { id: "ex-a1-038", type: "mc", level: "A1", topic: "numeri", prompt: "En el bar te preguntan “Quanto costa il dolce?”. ¿Qué te están preguntando?",
    options: ["Cuánto cuesta el postre", "Qué postre prefieres", "Si quieres pagar con tarjeta", "Si el postre está incluido"], answer: 0, explain: "Quanto costa? = ¿cuánto cuesta?" },
  { id: "ex-a1-039", type: "mc", level: "A1", topic: "aggettivi", prompt: "Completa: “Ho ___ fame!” (mucha)",
    options: ["molta", "molto", "molti", "molte"], answer: 0, explain: "molto concuerda con el sustantivo: fame es femenina singular → molta fame." },
  { id: "ex-a1-040", type: "tf", level: "A1", topic: "pronomi", prompt: "¿Es correcto decir “Mi piacciono il gelato”?",
    statement: "Mi piacciono il gelato.", answer: false, explain: "“Il gelato” es singular → mi piace il gelato." },
  { id: "ex-a1-041", type: "mc", level: "A1", topic: "vocabolario", prompt: "¿Cuál es el tercer día de la semana laboral italiana?",
    options: ["mercoledì", "martedì", "giovedì", "lunedì"], answer: 0, explain: "lunedì, martedì, mercoledì, giovedì, venerdì…" },
  { id: "ex-a1-042", type: "mc", level: "A1", topic: "vocabolario", prompt: "“Che tempo fa?” — “Fa ___”: hace (mucho) calor.",
    options: ["caldo", "freddo", "fresco", "vento"], answer: 0, explain: "fa caldo / fa freddo / c'è vento / piove." },
  { id: "ex-a1-043", type: "translate", level: "A1", topic: "vocabolario", prompt: "Traduce al italiano", to: "it", source: "El lunes trabajo hasta tarde.",
    accepted: ["lunedì lavoro fino a tardi", "il lunedì lavoro fino a tardi"], explain: "Días en minúscula; “fino a tardi” = hasta tarde." },
  { id: "ex-a1-044", type: "match", level: "A1", topic: "vocabolario", prompt: "Empareja cada color con su traducción",
    pairs: [ { it: "rosso", es: "rojo" }, { it: "giallo", es: "amarillo" }, { it: "verde", es: "verde" }, { it: "grigio", es: "gris" }, { it: "bianco", es: "blanco" }, { it: "nero", es: "negro" } ] },
  { id: "ex-a1-045", type: "dictation", level: "A1", topic: "ascolto", prompt: "Escucha y escribe lo que oyes",
    text: "Oggi piove, ma domani fa bel tempo.", es: "Hoy llueve, pero mañana hace buen tiempo." },

  /* ═══ A2 · viajes, hotel, cuerpo, reflexivos, passato prossimo ═══ */
  { id: "ex-a2-026", type: "mc", level: "A2", topic: "situazioni", prompt: "En la estación: “Un biglietto di andata e ritorno” es…",
    options: ["Un billete de ida y vuelta", "Un billete de solo ida", "Un abono mensual", "Una reserva de asiento"], answer: 0, explain: "andata e ritorno = ida y vuelta; solo andata = solo ida." },
  { id: "ex-a2-027", type: "order", level: "A2", topic: "situazioni", prompt: "Ordena: “Vorrei un biglietto per Roma, per favore.”",
    words: ["Vorrei", "biglietto", "un", "per", "Roma", "favore", "per"], answer: ["Vorrei", "un", "biglietto", "per", "Roma", ",", "per", "favore"], explain: "Vorrei (condicional de cortesía) + destino con “per”." },
  { id: "ex-a2-028", type: "mc", level: "A2", topic: "vocabolario", prompt: "“Il treno parte dal binario 9.” ¿Qué es “il binario”?",
    options: ["El andén", "El billete", "El horario", "El retraso"], answer: 0, explain: "binario = andén/vía." },
  { id: "ex-a2-029", type: "mc", level: "A2", topic: "situazioni", prompt: "En recepción: “Ho una prenotazione a nome Rossi.” Significa…",
    options: ["Tengo una reserva a nombre de Rossi", "Quiero una habitación con vistas", "He perdido la llave", "Quiero cancelar la reserva"], answer: 0, explain: "a nome di = a nombre de. Fórmula clave del check-in." },
  { id: "ex-a2-030", type: "mc", level: "A2", topic: "domande", prompt: "¿Cómo preguntas si el desayuno está incluido?",
    options: ["La colazione è inclusa?", "Dov'è la colazione?", "A che ora è la cena?", "Quanto costa il pranzo?"], answer: 0, explain: "è inclusa? = ¿está incluido?" },
  { id: "ex-a2-031", type: "mc", level: "A2", topic: "vocabolario", prompt: "En el médico: “Mi fa male la ___.” (me duele la cabeza)",
    options: ["testa", "gamba", "schiena", "bocca"], answer: 0, explain: "mi fa male la testa / mi fanno male le gambe (plural)." },
  { id: "ex-a2-032", type: "fill", level: "A2", topic: "verbi", prompt: "Completa el reflexivo: “Stamattina ___ alle sette.” (alzarsi, io)",
    sentence: "Stamattina ___ alle sette.", accepted: ["mi sono alzato", "mi sono alzata", "mi alzo"], explain: "Passato prossimo reflexivo: essere + participio + clítico (mi sono alzato/a)." },
  { id: "ex-a2-033", type: "mc", level: "A2", topic: "verbi", prompt: "Completa: “Ogni sera ___ i denti.” (lavarsi, io)",
    options: ["mi lavo", "lavo mi", "mi lava", "io lavo"], answer: 0, explain: "Reflexivo en presente: mi lavo, ti lavi, si lava…" },
  { id: "ex-a2-034", type: "mc", level: "A2", topic: "passato", prompt: "Completa: “Ieri ___ una pizza buonissima.” (mangiare, io)",
    options: ["ho mangiato", "sono mangiato", "mangiavo", "mangerò"], answer: 0, explain: "Verbo transitivo con avere: ho mangiato." },
  { id: "ex-a2-035", type: "mc", level: "A2", topic: "passato", prompt: "Completa: “Loro ___ in Italia l'anno scorso.” (andare)",
    options: ["sono andati", "hanno andato", "andavano", "sono andare"], answer: 0, explain: "andare usa essere: sono andati/e." },
  { id: "ex-a2-036", type: "tf", level: "A2", topic: "passato", prompt: "¿Es correcto “Ho andato al cinema ieri”?",
    statement: "Ho andato al cinema ieri.", answer: false, explain: "andare lleva essere: Sono andato al cinema ieri." },
  { id: "ex-a2-037", type: "fill", level: "A2", topic: "passato", prompt: "Completa: “Maria ___ ieri sera.” (venire)",
    sentence: "Maria ___ ieri sera.", accepted: ["è venuta"], explain: "venire: essere + venuta (participio concuerda: Maria fem.)." },
  { id: "ex-a2-038", type: "mc", level: "A2", topic: "numeri", prompt: "¿Qué hora es “le otto e un quarto”?",
    options: ["8:15", "8:45", "7:15", "8:30"], answer: 0, explain: "e un quarto = y cuarto; e mezza = y media; tre quarti = menos cuarto (le otto e tre quarti = 8:45)." },
  { id: "ex-a2-039", type: "translate", level: "A2", topic: "verbi", prompt: "Traduce al italiano (usa el passato prossimo reflexivo)", to: "it", source: "Esta mañana me he despertado a las siete.",
    accepted: ["stamattina mi sono svegliato alle sette", "questa mattina mi sono svegliata alle sette", "stamattina mi sono svegliata alle sette", "questa mattina mi sono svegliato alle sette"], explain: "svegliarsi es reflexivo: essere + svegliato/a; la hora con “alle”." },
  { id: "ex-a2-040", type: "dictation", level: "A2", topic: "ascolto", prompt: "Escucha y escribe el anuncio",
    text: "Il treno per Firenze è in ritardo di dieci minuti.", es: "El tren a Florencia va con diez minutos de retraso." },

  /* ═══ B1 · trabajo, correo formal, entrevista, noticias, narración, opiniones ═══ */
  { id: "ex-b1-016", type: "mc", level: "B1", topic: "vocabolario", prompt: "“La riunione è stata rinviata.” ¿Qué significa “rinviata”?",
    options: ["Aplazada", "Cancelada", "Confirmada", "Acortada"], answer: 0, explain: "rinviare = aplazar; cancellare = cancelar." },
  { id: "ex-b1-017", type: "mc", level: "B1", topic: "grammatica", prompt: "¿Cuál es la apertura correcta de un correo formal?",
    options: ["Gentile Dott. Rossi,", "Ciao Rossi!", "Ehi, come va?", "Salve amico!"], answer: 0, explain: "Gentile / Spettabile + título. Cierre: Cordiali saluti." },
  { id: "ex-b1-018", type: "order", level: "B1", topic: "grammatica", prompt: "Ordena: “In allegato trova il mio curriculum.”",
    words: ["In", "trova", "allegato", "curriculum", "il", "mio"], answer: ["In", "allegato", "trova", "il", "mio", "curriculum", "."], explain: "“In allegato” = adjunto (en un correo formal)." },
  { id: "ex-b1-019", type: "mc", level: "B1", topic: "passato", prompt: "En una entrevista: “___ per tre anni in un'azienda internazionale.”",
    options: ["Ho lavorato", "Lavoravo sempre", "Sono lavorato", "Lavoro"], answer: 0, explain: "Duración cerrada y terminada → passato prossimo: ho lavorato per tre anni." },
  { id: "ex-b1-020", type: "mc", level: "B1", topic: "vocabolario", prompt: "“Vorrei candidarmi per il posto di…” significa…",
    options: ["Quisiera presentarme al puesto de…", "Quiero renunciar al puesto de…", "Voy a entrevistarme para…", "Acabo de conseguir el puesto de…"], answer: 0, explain: "candidarsi = presentarse como candidato." },
  { id: "ex-b1-021", type: "mc", level: "B1", topic: "passato", prompt: "Completa: “Ieri ___ quando sono uscito.” (piovere, acción en curso)",
    options: ["pioveva", "ha piovuto", "piove", "pioverà"], answer: 0, explain: "Acción en curso que enmarca otra → imperfetto: pioveva." },
  { id: "ex-b1-022", type: "mc", level: "B1", topic: "passato", prompt: "Completa: “Mentre studiavo, il telefono ___.” (suonare, evento puntual)",
    options: ["è suonato", "suonava", "suona", "ha suonato sempre"], answer: 0, explain: "Marco (imperfetto) + evento (passato prossimo): è suonato." },
  { id: "ex-b1-023", type: "fill", level: "B1", topic: "passato", prompt: "Completa: “Da bambino ___ sempre nel cortile.” (giocare, hábito)",
    sentence: "Da bambino ___ sempre nel cortile.", accepted: ["giocavo"], explain: "Hábito recurrente en el pasado → imperfetto: giocavo." },
  { id: "ex-b1-024", type: "mc", level: "B1", topic: "grammatica", prompt: "¿Cómo se dice “en mi opinión” para abrir una opinión?",
    options: ["Secondo me", "Per me che", "Da me", "A me"], answer: 0, explain: "secondo me / a mio parere / dal mio punto di vista." },
  { id: "ex-b1-025", type: "mc", level: "B1", topic: "vocabolario", prompt: "En las noticias: “l'aumento dei prezzi” es…",
    options: ["El aumento de los precios", "La baja de los precios", "El control de precios", "La lista de precios"], answer: 0, explain: "l'aumento = el aumento; la riduzione = la reducción." },
  { id: "ex-b1-026", type: "translate", level: "B1", topic: "congiuntivo", prompt: "Traduce al italiano (atención al subjuntivo)", to: "it", source: "Creo que es una buena idea.",
    accepted: ["penso che sia una buona idea", "creo che sia una buona idea", "penso che è una buona idea"], explain: "Tras penso che / credo che → congiuntivo: sia." },
  { id: "ex-b1-027", type: "mc", level: "B1", topic: "congiuntivo", prompt: "Completa: “Penso che Marco ___ ragione.” (avere)",
    options: ["abbia", "ha", "avrà", "aveva"], answer: 0, explain: "penso che + congiuntivo: abbia ragione." },
  { id: "ex-b1-028", type: "order", level: "B1", topic: "grammatica", prompt: "Ordena: “Credo che questo lavoro sia adatto a me.”",
    words: ["Crede", "che", "lavoro", "questo", "sia", "a", "adatto", "mi"], answer: ["Credo", "che", "questo", "lavoro", "sia", "adatto", "a", "me", "."], explain: "credo che + subjuntivo (sia) es la estructura B1 por excelencia." },
  { id: "ex-b1-029", type: "mc", level: "B1", topic: "vocabolario", prompt: "Titular: “Il governo annuncia nuove misure.” “Misure” significa…",
    options: ["Medidas", "Ministros", "Muros", "Sueldos"], answer: 0, explain: "le misure = las medidas (políticas/económicas)." },
  { id: "ex-b1-030", type: "dictation", level: "B1", topic: "ascolto", prompt: "Escucha la nota de voz del jefe y escríbela",
    text: "La riunione di domani è stata spostata alle undici.", es: "La reunión de mañana ha sido movida a las once." },

  /* ═══ B2 · congiuntivo passato, relativas, connettivi, ipotético, publicidad ═══ */
  { id: "ex-b2-013", type: "mc", level: "B2", topic: "congiuntivo", prompt: "Completa: “Penso che Maria ___ già partita.”",
    options: ["sia", "è", "fosse", "sarà"], answer: 0, explain: "Congiuntivo passato: che sia partita." },
  { id: "ex-b2-014", type: "mc", level: "B2", topic: "pronomi", prompt: "Completa: “Il libro ___ ho letto è di Ferrante.”",
    options: ["che", "cui", "quale", "dove"], answer: 0, explain: "Complemento directo → che." },
  { id: "ex-b2-015", type: "mc", level: "B2", topic: "pronomi", prompt: "Completa: “La città in ___ vivo è meravigliosa.”",
    options: ["cui", "che", "quale", "dove che"], answer: 0, explain: "Tras preposición (in, di, a, con) → cui." },
  { id: "ex-b2-016", type: "mc", level: "B2", topic: "preposizioni", prompt: "Completa: “___ la pioggia, siamo usciti.” (a pesar de)",
    options: ["Nonostante", "Perché", "Durante", "Oltre a"], answer: 0, explain: "nonostante + sustantivo (o congiuntivo: nonostante piovesse)." },
  { id: "ex-b2-017", type: "mc", level: "B2", topic: "grammatica", prompt: "Elige el conector de contraste formal: “I prezzi salgono; ___, i consumi non calano.”",
    options: ["tuttavia", "quindi", "infatti", "perciò"], answer: 0, explain: "tuttavia / comunque = sin embargo (contraste); quindi/perciò = por lo tanto (causa)." },
  { id: "ex-b2-018", type: "mc", level: "B2", topic: "condizionale", prompt: "Completa: “Se mi avessi chiamato, ___ venuto subito.” (io)",
    options: ["sarei", "sarò", "ero", "fui"], answer: 0, explain: "Ipotético de 3º tipo (irreal del pasado): se + congiuntivo trapassato → condizionale composto: sarei venuto." },
  { id: "ex-b2-019", type: "mc", level: "B2", topic: "condizionale", prompt: "Completa: “Se avessi più tempo, ___ di più.” (viaggiare)",
    options: ["viaggerei", "viaggerò", "viaggiavo", "ho viaggiato"], answer: 0, explain: "Ipotético de 2º tipo: se + congiuntivo imperfetto → condizionale presente." },
  { id: "ex-b2-020", type: "mc", level: "B2", topic: "congiuntivo", prompt: "Completa: “Se studiavi, ___ l'esame.” (superar, tú)",
    options: ["avresti superato", "supereresti", "avevi superato", "supera"], answer: 0, explain: "Ipotético 3º: se + imperfetto (con valor irreal) → condizionale composto." },
  { id: "ex-b2-021", type: "fill", level: "B2", topic: "congiuntivo", prompt: "Completa: “Se ___ ricco, comprerei una casa in Toscana.” (essere, io)",
    sentence: "Se ___ ricco, comprerei una casa in Toscana.", accepted: ["fossi"], explain: "se + congiuntivo imperfetto: se fossi." },
  { id: "ex-b2-022", type: "mc", level: "B2", topic: "cultura", prompt: "En publicidad: “Meno è più” traduce el eslogan…",
    options: ["Menos es más", "Lo barato sale caro", "Más rápido, más fuerte", "El mínimo esfuerzo"], answer: 0, explain: "Calco de “less is more”, muy usado en el diseño italiano." },
  { id: "ex-b2-023", type: "translate", level: "B2", topic: "condizionale", prompt: "Traduce al italiano (periodo ipotetico di 3° tipo)", to: "it", source: "Si lo hubiera sabido, habría venido antes.",
    accepted: ["se lo avessi saputo, sarei venuto prima", "se lo avessi saputo sarei venuto prima", "se lo sapessi sarei venuto prima"], explain: "3º tipo: se lo avessi saputo → sarei venuto." },
  { id: "ex-b2-024", type: "dictation", level: "B2", topic: "ascolto", prompt: "Escucha y escribe la frase del telediario",
    text: "Nonostante il traffico, la città resta la più vivibile d'Italia.", es: "A pesar del tráfico, la ciudad sigue siendo la más vivible de Italia." },

  /* ═══ C1 · nominalización, registro, idioms ═══ */
  { id: "ex-c1-007", type: "mc", level: "C1", topic: "grammatica", prompt: "Nominalización académica de “si è verificato un errore”:",
    options: ["il verificarsi di un errore", "l'errore che verifica", "verificando errore", "la verifica sbagliata"], answer: 0, explain: "El infinito sustantivado con artículo: il verificarsi di…" },
  { id: "ex-c1-008", type: "mc", level: "C1", topic: "vocabolario", prompt: "En registro coloquial, “che palle!” expresa…",
    options: ["Qué pesadez / aburrimiento", "Qué suerte", "Qué miedo", "Qué barato"], answer: 0, explain: "che palle = qué pesado (familiar). Equivalente educado: che noia." },
  { id: "ex-c1-009", type: "mc", level: "C1", topic: "vocabolario", prompt: "“In bocca al lupo!” significa…",
    options: ["¡Buena suerte!", "¡Cuidado!", "¡Buen provecho!", "¡Enhorabuena!"], answer: 0, explain: "Se responde: “Crepi!” (¡que reviente!)." },
  { id: "ex-c1-010", type: "mc", level: "C1", topic: "vocabolario", prompt: "“È capitato a fagiolo” quiere decir que sucedió…",
    options: ["En el momento perfecto", "Dos veces seguidas", "Por desgracia", "De madrugada"], answer: 0, explain: "capitare a fagiolo = llegar como anillo al dedo." },
  { id: "ex-c1-011", type: "mc", level: "C1", topic: "grammatica", prompt: "En un texto formal, sustituye “fare un controllo” por…",
    options: ["effettuare un controllo", "farefare un controllo", "controllo fare", "fare fare controllo"], answer: 0, explain: "effettuare / procedere a son alternativas formales del verbo “fare”." },
  { id: "ex-c1-012", type: "mc", level: "C1", topic: "vocabolario", prompt: "“Non vedo l'ora che arrivi venerdì” expresa…",
    options: ["Impaciencia", "Indiferencia", "Decepción", "Sorpresa"], answer: 0, explain: "non vedere l'ora = no poder esperar / estar que trino." },
  { id: "ex-c1-013", type: "fill", level: "C1", topic: "vocabolario", prompt: "Completa el modismo: “Andare a___” significa morir (familiar).",
    sentence: "Il vecchio quadro è andato a ___ (fam.)", accepted: ["fagioli", "fave", "vela"], explain: "andare a fagioli/fave (familiar) = morirse; en registro neutro: venire a mancare." },
  { id: "ex-c1-014", type: "translate", level: "C1", topic: "grammatica", prompt: "Traduce al italiano en registro formal", to: "it", source: "Le agradecería que me confirmara la recepción del documento.",
    accepted: ["le sarei grato se mi confermasse la ricezione del documento", "le sarei grato se potesse confermarmi la ricezione del documento", "le sarei grata se mi confermasse la ricezione del documento"], explain: "sarei grato + se + congiuntivo (confermasse): cortesía formal C1." },

  /* ═══ C2 · retórica, variantes, académico ═══ */
  { id: "ex-c2-005", type: "mc", level: "C2", topic: "grammatica", prompt: "“Roma, Roma, Roma: cuore di questa città.” ¿Qué figura retórica es?",
    options: ["Anáfora (repetición de inicio)", "Metáfora", "Ironía", "Hipérbaton"], answer: 0, explain: "La repetición en posición inicial de verso/frase es anáfora." },
  { id: "ex-c2-006", type: "mc", level: "C2", topic: "congiuntivo", prompt: "“Se egli avesse compreso, avrebbe taciuto.” El “avrebbe taciuto” es…",
    options: ["Condizionale composto", "Congiuntivo trapassato", "Futuro anteriore", "Passato remoto"], answer: 0, explain: "condizionale compuesto = habría callado; el trapassato sería “avesse compreso”." },
  { id: "ex-c2-007", type: "mc", level: "C2", topic: "cultura", prompt: "En el italiano del Norte es frecuente “andare in bici col friulano”: ¿cuál de estas es una lengua de minoridad reconocida por el Estado italiano?",
    options: ["Il friulano", "Il piemontese urbano", "Il romanesco", "Il milanese"], answer: 0, explain: "Friulano, sardo, ladino, occitano, catalano de Alghero y otras 8 están protegidas por ley (482/1999)." },
  { id: "ex-c2-008", type: "mc", level: "C2", topic: "grammatica", prompt: "En un ensayo académico, “eppure” introduce…",
    options: ["Contraste argumentativo", "Concesión total", "Causa", "Consecuencia lógica"], answer: 0, explain: "eppure = y sin embargo: contraste con matiz de resistencia argumentativa." },
  { id: "ex-c2-009", type: "tf", level: "C2", topic: "congiuntivo", prompt: "¿Es correcta la concordancia “Se avessi saputo che eri malato, sarei venuto”?",
    statement: "Se avessi saputo che eri malato, sarei venuto.", answer: true, explain: "Hipopótético 3º correcto: la subordinada con indicativo (eri) es válida por ser un hecho real." },
  { id: "ex-c2-010", type: "dictation", level: "C2", topic: "ascolto", prompt: "Escucha y transcribe la frase literaria",
    text: "La lingua non è una gabbia bensì una lente attraverso cui il mondo si colora.", es: "La lengua no es una jaula sino una lente a través de la cual el mundo se colorea." },

  /* ═══ Lecturas nuevas (comprensión) ═══ */
  { id: "ex-let-007", type: "mc", level: "A1", topic: "ascolto", prompt: "Lectura “Il menu del giorno”: ¿cuál es el dolce della casa?",
    options: ["Il tiramisù", "La caprese", "L'orata", "Le patate"], answer: 0, explain: "El texto dice: “il dolce della casa è il tiramisù”." },
  { id: "ex-let-008", type: "mc", level: "A2", topic: "ascolto", prompt: "Lectura “Una gita a Firenze”: ¿cómo van a Florencia?",
    options: ["En tren", "En coche", "En avión", "En autobús"], answer: 0, explain: "“Il treno delle otto e dieci diretto a Firenze”." },
  { id: "ex-let-009", type: "mc", level: "A2", topic: "passato", prompt: "Lectura “Il nuovo lavoro di Luca”: ¿cuánto tiempo llevaba buscando?",
    options: ["Sei mesi", "Due settimane", "Un anno", "Un mes"], answer: 0, explain: "“dopo sei mesi di ricerca”." },
  { id: "ex-let-010", type: "mc", level: "B1", topic: "ascolto", prompt: "Lectura “Cosa fare a Bologna di sera”: ¿qué se recomienda para el after-dinner?",
    options: ["Una passeggiata sotto le Due Torri", "Un museo notturno", "Una discoteca", "Tornare in hotel"], answer: 0, explain: "El rito boloñés: la passeggiata sotto le Due Torri." },
  { id: "ex-let-011", type: "mc", level: "B1", topic: "vocabolario", prompt: "Lectura “Intervista a una chef”: “il chilometro zero” indica…",
    options: ["Ingredientes de productores locales", "Comida para llevar", "Un menú sin gluten", "El plato estrella"], answer: 0, explain: "chilometro zero = producción local de proximidad." },
  { id: "ex-let-012", type: "mc", level: "B2", topic: "cultura", prompt: "Lectura sobre turismo en Venecia: ¿cuál es la tesis principal?",
    options: ["Hay que equilibrar turismo y vida de los residentes", "Hay que prohibir todo el turismo", "El turismo no afecta a la ciudad", "Los turistas deben pagar el doble"], answer: 0, explain: "El texto argumenta una gestión sostenible del flujo turístico." },
  { id: "ex-let-013", type: "mc", level: "C1", topic: "cultura", prompt: "Lectura “Perché gli italiani parlano con le mani”: el gesto es…",
    options: ["Parte del sistema comunicativo, no un simple adorno", "Un invento del cine", "Una costumbre solo del sur", "Un signo de impaciencia"], answer: 0, explain: "La gesticulación es parte estructural de la comunicación italiana." },
  { id: "ex-let-014", type: "mc", level: "C2", topic: "vocabolario", prompt: "Lectura “La lingua come paesaggio”: la metáfora central sostiene que…",
    options: ["La lengua es un paisaje que habitamos y que nos habita", "El italiano está muriendo", "Solo existe una lengua correcta", "Traducir es imposible"], answer: 0, explain: "La lengua-paisaje: nos forma tanto como la formamos." },

  /* ═══ Escuchas nuevas ═══ */
  { id: "ex-asc-007", type: "mc", level: "A1", topic: "ascolto", prompt: "Escucha “Al mercato”: ¿qué compra la clienta?",
    options: ["Due chili di pesche", "Del pane", "Del formaggio", "Dei pomodori"], answer: 0, explain: "“Vorrei due chili di pesche, per favore.”" },
  { id: "ex-asc-008", type: "mc", level: "A2", topic: "ascolto", prompt: "Escucha “Check-in in hotel”: ¿qué pide el cliente además de la habitación?",
    options: ["Una camera silenziosa ai piani alti", "Il servizio in camera", "Un taxi", "La colazione in camera"], answer: 0, explain: "“Preferisco una camera silenziosa ai piani alti.”" },
  { id: "ex-asc-009", type: "mc", level: "A2", topic: "numeri", prompt: "Escucha los números y elige el número de teléfono completo",
    options: ["Tre-tre-nove-otto-due-uno", "Tre-due-nove-otto-tre-uno", "Due-tre-nove-otto-due-uno", "Tre-tre-otto-nove-due-uno"], answer: 0, explain: "Los dígitos se dan de uno en uno en italiano." },
  { id: "ex-asc-010", type: "mc", level: "B1", topic: "ascolto", prompt: "Escucha la entrevista de trabajo: ¿cuál es la fortaleza del candidato?",
    options: ["La gestione di team internazionali", "La contabilità", "Il graphic design", "Le vendite porta a porta"], answer: 0, explain: "“Ho guidato team internazionali per due anni.”" },
  { id: "ex-asc-011", type: "mc", level: "B2", topic: "ascolto", prompt: "Escucha el debate: ¿cuál es la postura del segundo interviniente?",
    options: ["Matiza: turismo sí, pero regulado", "Turismo cero", "Turismo libre sin límites", "No opina"], answer: 0, explain: "“Il turismo non è il nemico: lo è la sua cattiva gestione.”" },
  { id: "ex-asc-012", type: "dictation", level: "B2", topic: "ascolto", prompt: "Dictado de frases del noticiario",
    text: "Secondo gli esperti, il mercato del lavoro crescerà lentamente.", es: "Según los expertos, el mercado laboral crecerá lentamente." },

  /* ═══ Laboratorio de números ═══ */
  { id: "ex-num-001", type: "mc", level: "A1", topic: "numeri", prompt: "¿Cómo se escribe 34 en italiano?",
    options: ["trentaquattro", "trentaquatro", "trenta quattro", "trentaquatttro"], answer: 0, explain: "trenta + quattro = trentaquattro (una sola palabra)." },
  { id: "ex-num-002", type: "mc", level: "A1", topic: "numeri", prompt: "¿Y 68?",
    options: ["sessantotto", "sessantaotto", "sessantotto", "sesantotto"], answer: 0, explain: "Ojo: la -o de sessanta + otto → sessantotto (una t más que en español)." },
  { id: "ex-num-003", type: "mc", level: "A1", topic: "numeri", prompt: "“ventitré” es…",
    options: ["23", "32", "13", "33"], answer: 0, explain: "venti + tre = ventitré, con acento en la é final." },
  { id: "ex-num-004", type: "mc", level: "A2", topic: "numeri", prompt: "¿Cómo se dice 1998?",
    options: ["millenovecentonovantotto", "mille novecento novanta otto", "millenovecento novantotto", "novecentonovantotto"], answer: 0, explain: "mille + novecento + novantotto, todo junto en un compuesto." },
  { id: "ex-num-005", type: "mc", level: "A2", topic: "numeri", prompt: "El ordinal de “primo, secondo, terzo” continúa con…",
    options: ["quarto", "quattro", "quartesimo", "quarta"], answer: 0, explain: "Ordinales irregulares: primo, secondo, terzo, quarto, quinto…" },
  { id: "ex-num-006", type: "mc", level: "A1", topic: "numeri", prompt: "Son las 13:00. ¿Cómo se dice?",
    options: ["È l'una", "Sono le tredici", "È mezzogiorno", "È l'una e mezza"], answer: 0, explain: "En la vida diaria, la 1 de la tarde è l'una (le tredici es registro formal/24h)." },

  /* ═══ Entrenamiento de verbos ═══ */
  { id: "ex-verb-001", type: "mc", level: "A1", topic: "presente", prompt: "“fare”, 3ª persona singular: lui/lei ___",
    options: ["fa", "fare", "fà", "fae"], answer: 0, explain: "io faccio, tu fai, lui fa (sin acento), noi facciamo, voi fate, loro fanno." },
  { id: "ex-verb-002", type: "mc", level: "A2", topic: "passato", prompt: "“prendere”, passato prossimo io: ___",
    options: ["ho preso", "sono preso", "ho prenduto", "avevo preso"], answer: 0, explain: "participio irregular: preso (no *prenduto)." },
  { id: "ex-verb-003", type: "mc", level: "A1", topic: "presente", prompt: "“venire”, noi: ___",
    options: ["veniamo", "venono", "venio", "vieniamo"], answer: 0, explain: "io vengo, tu vieni, lui viene, noi veniamo, voi venite, loro vengono." },
  { id: "ex-verb-004", type: "mc", level: "B1", topic: "futuro", prompt: "“avere”, futuro io: ___",
    options: ["avrò", "averò", "avrarei", "avevo"], answer: 0, explain: "Futuros contractos: avrò, sarò, andrò, farò, darò." },
  { id: "ex-verb-005", type: "mc", level: "B2", topic: "congiuntivo", prompt: "“essere”, congiuntivo io: che io ___",
    options: ["sia", "sò", "sono", "fui"], answer: 0, explain: "che io sia, che tu sia, che lui sia…" },
  { id: "ex-verb-006", type: "fill", level: "B1", topic: "passato", prompt: "“dire”, imperfetto loro: ___",
    sentence: "Ieri i bambini ___ sempre la stessa cosa. (dire, loro)", accepted: ["dicevano"], explain: "imperfetto: dicevano (io dicevo, tu dicevi…)." },
];
