import type { Exercise } from "../types";

/* ── Ejercicios · paquete de expansión v4.0 ──────────────────────────
   Cubre las 21 lecciones nuevas (u-zero-4 → u-c2-4), las 8 lecturas
   nuevas (rd-15…rd-22) y las 8 escuchas nuevas (ls-15…ls-22). */

export const EXERCISES_EXTRA_2: Exercise[] = [
  /* ═══ ZERO · u-zero-4 La giornata e i pasti ═══ */
  { id: "ex-z4-001", type: "mc", level: "A1", topic: "verbi", prompt: "Completa: “Io ___ alle sette.” (despertarse)",
    options: ["mi sveglio", "sveglio", "si sveglia", "mi sveglia"], answer: 0, explain: "Verbo reflexivo: el pronombre va delante → mi sveglio." },
  { id: "ex-z4-002", type: "fill", level: "A1", topic: "verbi", prompt: "Escribe el verbo correcto: “La sera i bambini ___ presto.” (coricarsi)",
    sentence: "La sera i bambini ___ presto.", accepted: ["si coricano"], explain: "Reflexivo 3.ª persona plural: si coricano." },
  { id: "ex-z4-003", type: "mc", level: "A1", topic: "vocabolario", prompt: "¿Cómo se dice “desayunar” en italiano?",
    options: ["fare colazione", "fare cena", "fare merenda", "fare pranzo"], answer: 0, explain: "fare colazione = desayunar; fare pranzo/cena no se usa: se dice pranzare y cenare." },
  { id: "ex-z4-004", type: "mc", level: "A1", topic: "vocabolario", prompt: "La “merenda” es…",
    options: ["la merienda", "la cena", "el desayuno", "la comida"], answer: 0, explain: "la merenda = merienda, la parada dulce de la tarde de los niños (y no solo)." },
  { id: "ex-z4-005", type: "mc", level: "A1", topic: "vocabolario", prompt: "Completa: “Che ___ fa? — Fa sole!”",
    options: ["tempo", "ora", "giorno", "stagione"], answer: 0, explain: "Che tempo fa? = ¿qué tiempo hace? Respuesta con fare: fa sole, fa freddo…" },
  { id: "ex-z4-006", type: "fill", level: "A1", topic: "preposizioni", prompt: "Completa con la preposición: “___ estate andiamo al mare.”",
    sentence: "___ estate andiamo al mare.", accepted: ["d'estate", "destate", "in estate"], explain: "Con estate (y inverno) se usa d' (di + elisión): d'estate, d'inverno." },

  /* ═══ A1 · u-a1-7 La casa ═══ */
  { id: "ex-a1-046", type: "mc", level: "A1", topic: "vocabolario", prompt: "Completa: “___ camere ci sono in casa tua?”",
    options: ["Quante", "Quanto", "Quanti", "Che"], answer: 0, explain: "Camere es plural femenino → Quante. Respuesta: Ci sono tre camere." },
  { id: "ex-a1-047", type: "mc", level: "A1", topic: "presente", prompt: "Completa: “In cucina ___ un tavolo grande.” (hay)",
    options: ["c'è", "ci sono", "sono", "è"], answer: 0, explain: "Un tavolo = singular → c'è. Plural → ci sono." },
  { id: "ex-a1-048", type: "mc", level: "A1", topic: "pronomi", prompt: "Completa: “___ letto è comodo.” (mi)",
    options: ["Il mio", "La mia", "I miei", "Le mie"], answer: 0, explain: "Letto es masculino singular → il mio. El posesivo concuerda con la cosa, no con el dueño." },
  { id: "ex-a1-049", type: "fill", level: "A1", topic: "genere", prompt: "Escribe el posesivo correcto: “___ chiavi sono nella borsa.” (mi)",
    sentence: "___ chiavi sono nella borsa.", accepted: ["le mie"], explain: "Chiavi es femenino plural → le mie." },
  { id: "ex-a1-050", type: "mc", level: "A1", topic: "preposizioni", prompt: "Completa: “Abito ___ stazione, non lontano.” (cerca de)",
    options: ["vicino alla", "vicino al", "lontano dalla", "dentro la"], answer: 0, explain: "vicino a + la → vicino alla stazione." },
  { id: "ex-a1-051", type: "mc", level: "A1", topic: "pronomi", prompt: "Completa: “___ i parchi della mia città.” (me gustan)",
    options: ["Mi piacciono", "Mi piace", "Me piacciono", "Mi piacevano"], answer: 0, explain: "Sustantivo plural → piacciono: mi piacciono i parchi." },

  /* ═══ A2 · u-a2-6 Fare acquisti ═══ */
  { id: "ex-a2-041", type: "mc", level: "A2", topic: "vocabolario", prompt: "En una tienda, “Posso provare questa maglietta?” significa…",
    options: ["¿Puedo probarme esta camiseta?", "¿Puedo comprar esta camiseta?", "¿Puedo lavar esta camiseta?", "¿Puedo ver esta camiseta?"], answer: 0, explain: "provare = probar(se). En la tienda: posso provarla?" },
  { id: "ex-a2-042", type: "fill", level: "A2", topic: "numeri", prompt: "Completa: “Quanto ___ queste scarpe?” (costare)",
    sentence: "Quanto ___ queste scarpe?", accepted: ["costano"], explain: "Scarpe es plural → costano (quanto costano?). Singular: quanto costa?" },
  { id: "ex-a2-043", type: "mc", level: "A2", topic: "vocabolario", prompt: "“Lo scontrino” es…",
    options: ["el recibo (fiscal)", "la bolsa", "la etiqueta", "el descuento"], answer: 0, explain: "lo scontrino = recibo de compra, sagrado en Italia; la busta = la bolsa." },
  { id: "ex-a2-044", type: "mc", level: "A2", topic: "situazioni", prompt: "El dependiente pregunta: “In contanti o con la carta?”. Quiere saber…",
    options: ["si pagas en efectivo o con tarjeta", "si quieres la bolsa o no", "tu talla", "si eres socio"], answer: 0, explain: "in contanti = en efectivo; con la carta = con tarjeta (di credito/debito)." },
  { id: "ex-a2-045", type: "mc", level: "A2", topic: "passato", prompt: "Completa: “Ieri ___ un regalo a mia sorella.” (comprare)",
    options: ["ho comprato", "comprai", "compravo", "avevo comprato"], answer: 0, explain: "Acción terminada de ayer → passato prossimo: ho comprato." },
  { id: "ex-a2-046", type: "tf", level: "A2", topic: "situazioni", prompt: "Para rechazar con cortesía lo que te muestra un dependiente puedes decir: “Sto solo guardando, grazie.”",
    statement: "Sto solo guardando, grazie significa “solo estoy mirando, gracias”.", answer: true, explain: "Correcto: è la fórmula de cortesía para decir que solo estás mirando." },

  /* ═══ B1 · u-b1-6 La vita digitale ═══ */
  { id: "ex-b1-031", type: "mc", level: "B1", topic: "imperativo", prompt: "Completa: “___ il link che ti ho mandato!” (aprire, a un amigo)",
    options: ["Apri", "Apra", "Aprite", "Apro"], answer: 0, explain: "Imperativo informal singular: apri! (tu). Formal: apra (Lei)." },
  { id: "ex-b1-032", type: "mc", level: "B1", topic: "pronomi", prompt: "Completa: “Non ti sento, ___ il microfono!” (attivare, a un amigo)",
    options: ["attiva", "attivami", "attivalo", "attivate"], answer: 0, explain: "Imperativo + pronombre directo pospuesto: attiva il microfono. Si el pronombre es directo se pospone sin cambios." },
  { id: "ex-b1-033", type: "mc", level: "B1", topic: "congiuntivo", prompt: "Completa: “Credo che lo smart working ___ utile.”",
    options: ["sia", "è", "sono", "fosse"], answer: 0, explain: "Tras credo che → congiuntivo presente: sia." },
  { id: "ex-b1-034", type: "mc", level: "B1", topic: "vocabolario", prompt: "“Condividere lo schermo” en una videollamada es…",
    options: ["compartir la pantalla", "apagar la cámara", "silenciarse", "colgar"], answer: 0, explain: "condividere lo schermo = compartir pantalla; mettere il muto = silenciarse; chiudere la chiamata = colgar." },
  { id: "ex-b1-035", type: "mc", level: "B1", topic: "passato", prompt: "Completa: “Scorrevo il feed quando ___ la notizia.” (vedere)",
    options: ["ho visto", "vedevo", "avevo visto", "vedo"], answer: 0, explain: "Imperfetto (fondo) + passato prossimo (evento): scorrevo… quando ho visto." },
  { id: "ex-b1-036", type: "fill", level: "B1", topic: "verbi", prompt: "Escribe el verbo: “Mi ___ la batteria, dammi il caricatore!” (scaricarsi)",
    sentence: "Mi ___ la batteria, dammi il caricatore!", accepted: ["si è scaricata", "si scarica"], explain: "El si impersonal con battery: mi si è scaricata la batteria (se me descargó)." },

  /* ═══ B2 · u-b2-5 Ambiente ed economia ═══ */
  { id: "ex-b2-025", type: "mc", level: "B2", topic: "grammatica", prompt: "Completa la pasiva: “I rifiuti ___ raccolti ogni martedì.”",
    options: ["vengono", "vengano", "sono venuti", "verranno"], answer: 0, explain: "Pasiva con venire en presente: vengono raccolti. Más dinámica que sono raccolti." },
  { id: "ex-b2-026", type: "mc", level: "B2", topic: "preposizioni", prompt: "Completa: “___ dell'inquinamento, il livello del mare sale.” (a causa de)",
    options: ["A causa", "Grazie", "Per via", "Secondo"], answer: 0, explain: "a causa di = a causa de (negativo); grazie a = gracias a (positivo)." },
  { id: "ex-b2-027", type: "mc", level: "B2", topic: "condizionale", prompt: "Completa el consejo: “___ risparmiare di più quest'anno.” (deberíamos)",
    options: ["Dovremmo", "Dobbiamo", "Dovremmo aver", "Dovessimo"], answer: 0, explain: "Consejo prudente → condizionale presente: dovremmo." },
  { id: "ex-b2-028", type: "mc", level: "B2", topic: "aggettivi", prompt: "Completa la comparación equilibrada: “Milano è tanto cara ___ stressante.”",
    options: ["quanto", "come", "più", "meno"], answer: 0, explain: "tanto… quanto = tan… como (comparación de igualdad)." },
  { id: "ex-b2-029", type: "mc", level: "B2", topic: "condizionale", prompt: "Completa la hipótesis irreal: “Se ___ meno la macchina, inquinerei meno.” (usar)",
    options: ["usassi", "usavo", "userei", "uso"], answer: 0, explain: "Periodo ipotetico de 2.º tipo: se + congiuntivo imperfetto (usassi) → condizionale (inquinerei)." },
  { id: "ex-b2-030", type: "tf", level: "B2", topic: "vocabolario", prompt: "En Italia, la “raccolta differenziata” es la recolección selectiva de basura.",
    statement: "La raccolta differenziata è la recolección selectiva (separar orgánicos, plástico, papel…).", answer: true, explain: "Correcto: cada comune tiene sus reglas, colores y días; los italianos la defienden con orgullo municipal." },

  /* ═══ C1 · u-c1-4 L'Italia e le sue regioni ═══ */
  { id: "ex-c1-015", type: "mc", level: "C1", topic: "congiuntivo", prompt: "Completa: “Se ___ a Palermo, parleresti dialetto.” (nacer)",
    options: ["fossi nato", "nascevi", "sei nato", "eri nato"], answer: 0, explain: "Hipótesis irreal: se + congiuntivo imperfetto (fossi nato) → condizionale (parleresti)." },
  { id: "ex-c1-016", type: "mc", level: "C1", topic: "congiuntivo", prompt: "Completa: “Pareva che il nord e il sud ___ due paesi diversi.”",
    options: ["fossero", "erano", "sono", "saranno"], answer: 0, explain: "Tras pareva che / sembrava che → congiuntivo imperfetto: fossero." },
  { id: "ex-c1-017", type: "mc", level: "C1", topic: "grammatica", prompt: "Completa: “___ vissuto a Napoli, capisco il dialetto.” (habiendo vivido)",
    options: ["Avendo", "Avere", "Avuto", "Essendo"], answer: 0, explain: "Gerundio compuesto con avere: avendo vissuto = habiendo vivido." },
  { id: "ex-c1-018", type: "mc", level: "C1", topic: "grammatica", prompt: "Completa: “___ cresciuto tra due lingue, si sente doppio.” (habiendo crecido)",
    options: ["Essendo", "Avendo", "Stando", "Facendo"], answer: 0, explain: "Con verbos de movimiento/estado se usa essere: essendo cresciuto." },
  { id: "ex-c1-019", type: "mc", level: "C1", topic: "vocabolario", prompt: "“In fin dei conti” significa…",
    options: ["al fin y al cabo", "al final de la cuenta corriente", "en el fondo del pozo", "a fin de mes"], answer: 0, explain: "in fin dei conti = al fin y al cabo, conector de conclusión culta." },
  { id: "ex-c1-020", type: "mc", level: "C1", topic: "vocabolario", prompt: "El conector “peraltro” equivale a…",
    options: ["además / por lo demás", "sin embargo", "por el contrario", "es decir"], answer: 0, explain: "peraltro = además, por lo demás; introduce un dato que refuerza sin contradecir." },

  /* ═══ C2 · u-c2-4 La lingua della letteratura ═══ */
  { id: "ex-c2-011", type: "mc", level: "C2", topic: "congiuntivo", prompt: "Completa: “Se Dante non ___ la Commedia, l'italiano sarebbe diverso.” (escribir)",
    options: ["avesse scritto", "avesse scrivuto", "scrivesse", "avesse scritta"], answer: 0, explain: "Contrafactual: se + congiuntivo trapassato (avesse scritto) → condizionale passato/composto." },
  { id: "ex-c2-012", type: "mc", level: "C2", topic: "cultura", prompt: "El “Verismo” en la literatura italiana corresponde a…",
    options: ["el Realismo/Naturalismo (Verga, Capuana)", "el Romanticismo", "el Futurismo", "el Simbolismo"], answer: 0, explain: "Il Verismo (1870-1900) es el realismo italiano: Verga, Capuana, De Roberto." },
  { id: "ex-c2-013", type: "mc", level: "C2", topic: "grammatica", prompt: "El “endecasillabo” es…",
    options: ["un verso de once sílabas", "una estrofa de once versos", "un poema de once cantos", "una rima triple"], answer: 0, explain: "El endecasílabo (11 sílabas, acento en la 10.ª) es el verso noble italiano, desde Dante." },
  { id: "ex-c2-014", type: "mc", level: "C2", topic: "grammatica", prompt: "“Chiome d'oro” (Petrarca) es un ejemplo de…",
    options: ["metáfora", "aliteración", "hipérbaton", "ironía"], answer: 0, explain: "Metáfora petrarquiana: los cabellos son (metafóricamente) oro." },
  { id: "ex-c2-015", type: "mc", level: "C2", topic: "vocabolario", prompt: "El latinismo “in itinere” significa…",
    options: ["en el transcurso / sobre la marcha", "en línea recta", "de verdad", "en silencio"], answer: 0, explain: "in itinere = durante el desarrollo de algo, sobre la marcha: studiare il caso in itinere." },
  { id: "ex-c2-016", type: "mc", level: "C2", topic: "vocabolario", prompt: "En Toscana, “babbo” es…",
    options: ["papá", "bebé", "bautizo", "tío"], answer: 0, explain: "babbo = papá (toscanismo vivo); el estándar es papà." },

  /* ═══ LECTURAS nuevas rd-15…rd-22 (2 preguntas cada una) ═══ */
  { id: "ex-let-015", type: "mc", level: "A1", topic: "ascolto", prompt: "¿Qué compra el protagonista del texto “Al mercato di Rialto”?",
    options: ["Fruta y verdura", "Zapatos", "Un periódico", "Pescado"], answer: 0, explain: "En el mercado de Rialto compra frutta e verdura per la settimana." },
  { id: "ex-let-016", type: "mc", level: "A1", topic: "vocabolario", prompt: "En “Al mercato di Rialto”, “la fruttivendola” es…",
    options: ["la vendedora de fruta y verdura", "la frutería", "una fruta concreta", "un zumo"], answer: 0, explain: "la fruttivendola = la vendedora de fruta y verdura (-vendolo/-vendola, oficios con venta)." },
  { id: "ex-let-017", type: "mc", level: "A2", topic: "ascolto", prompt: "En “Una settimana a Bologna”, ¿cómo va Giulia al trabajo?",
    options: ["En bici", "En coche", "A pie", "En autobús"], answer: 0, explain: "Giulia va al lavoro in bicicletta: Bologna è la città delle bici porticate." },
  { id: "ex-let-018", type: "mc", level: "A2", topic: "vocabolario", prompt: "En el diario de Bologna, “i portici” son…",
    options: ["los soportales / pórticos", "los paraguas", "los aparcabicis", "los mercados"], answer: 0, explain: "i portici = los pórticos de Bologna (40 km declarados Patrimonio UNESCO)." },
  { id: "ex-let-019", type: "mc", level: "B1", topic: "ascolto", prompt: "Según “Il lavoro che cambia”, ¿qué porcentaje hace smart working en la empresa de Luca?",
    options: ["Dos días a la semana", "Cinco días", "Nunca", "Solo veranos"], answer: 0, explain: "Luca lavora da casa due giorni a settimana: lo smart working misto." },
  { id: "ex-let-020", type: "mc", level: "B1", topic: "grammatica", prompt: "En “Il lavoro che cambia”: “Il capo vorrebbe che tutti tornassero in ufficio”. ¿Qué tiempo es “tornassero”?",
    options: ["Congiuntivo imperfetto", "Indicativo imperfetto", "Condizionale", "Passato remoto"], answer: 0, explain: "vorrebbe che + congiuntivo imperfetto (tornassero): deseo no realizado." },
  { id: "ex-let-021", type: "mc", level: "B2", topic: "ascolto", prompt: "En “Il treno che unisce l'Italia”, ¿qué une la Alta Velocidad según el texto?",
    options: ["El norte y el sur en pocas horas", "Solo ciudades del norte", "Italia y Francia", "Las islas"], answer: 0, explain: "La AV une Milano y Roma en poco más de tres horas: el país se hace más pequeño." },
  { id: "ex-let-022", type: "mc", level: "B2", topic: "vocabolario", prompt: "En el texto del tren, “il pendolare” es…",
    options: ["la persona que viaja a diario por trabajo", "el péndulo del reloj", "el revisor", "el andén"], answer: 0, explain: "il pendolare = el viajero diario (pendular) entre casa y trabajo." },
  { id: "ex-let-023", type: "mc", level: "B2", topic: "ascolto", prompt: "En “Maremma amara”, ¿de qué trata el texto?",
    options: ["La vida de los pastores y braceros en la Maremma", "Un hotel en la costa", "La pesca del atún", "Una regata"], answer: 0, explain: "El texto evoca la Maremma de los pastores (butteri) y la malaria: maremma amara, dice el canto." },
  { id: "ex-let-024", type: "mc", level: "B2", topic: "vocabolario", prompt: "En “Maremma amara”, “i butteri” son…",
    options: ["los cowboys a caballo de la Maremma", "los pescadores", "los mosquitos", "los pastores de ovejas"], answer: 0, explain: "i butteri = los jinetes-vaqueros de la Maremma, los cowboys italianos." },
  { id: "ex-let-025", type: "mc", level: "C1", topic: "cultura", prompt: "Según “Le città d'arte minori”, ¿qué ventaja tienen las pequeñas ciudades de arte?",
    options: ["Se ven en pocos días, sin colas", "Son más baratas solo en invierno", "Tienen mejores restaurantes", "Están cerca del mar"], answer: 0, explain: "Urbino, Mantova, Ravenna: la escala humana permite verlas en pocos días sin las colas de las grandes." },
  { id: "ex-let-026", type: "mc", level: "C1", topic: "ascolto", prompt: "En “Le città d'arte minori”, ¿quién diseñó el Tempio Malatestiano de Rímini?",
    options: ["Leon Battista Alberti", "Michelangelo", "Bernini", "Palladio"], answer: 0, explain: "Alberti reconstruyó el Tempio Malatestiano para Sigismondo Malatesta." },
  { id: "ex-let-027", type: "mc", level: "C2", topic: "cultura", prompt: "En “Perché leggere i classici”, ¿qué afirma Calvino sobre los clásicos?",
    options: ["Nunca terminan de decir lo que tienen que decir", "Solo interesan a los filólogos", "Son aburridos pero útiles", "Deben leerse en dialecto"], answer: 0, explain: "La tesis calviniana: i classici non finiscono mai di dire ciò che hanno da dire." },
  { id: "ex-let-028", type: "mc", level: "C2", topic: "vocabolario", prompt: "En el texto sobre Calvino, “la leggerezza” calviniana se opone a…",
    options: ["la pesadez / el peso de vivir", "la velocidad", "la mentira", "la tradición"], answer: 0, explain: "La levedad de Calvino (lezione americana) es la ligereza pensada, no la frivolidad: quitare peso al mundo." },
  { id: "ex-let-029", type: "mc", level: "C1", topic: "ascolto", prompt: "En “Il dialetto a casa”, ¿dónde habla dialecto la familia de Chiara?",
    options: ["En casa, con la abuela", "En la oficina", "En la universidad", "En el supermercado"], answer: 0, explain: "El dialecto sobrevive en la esfera afectiva: con la nonna, en cocina, en las recetas." },
  { id: "ex-let-030", type: "mc", level: "C1", topic: "grammatica", prompt: "En “Il dialetto a casa”: “Pare che i giovani lo parlino meno”. ¿Qué tiempo es “parlino”?",
    options: ["Congiuntivo presente", "Indicativo presente", "Imperativo", "Condizionale"], answer: 0, explain: "Tras pare che / sembra que → congiuntivo presente: parlino." },

  /* ═══ ESCUCHAS nuevas ls-15…ls-22 (2 preguntas cada una) ═══ */
  { id: "ex-asc-013", type: "mc", level: "A1", topic: "ascolto", prompt: "En el diálogo del bar: ¿qué pide el cliente?",
    options: ["Un espresso y un cornetto", "Un cappuccino y agua", "Un té y una brioche", "Dos cafés"], answer: 0, explain: "Buongiorno, un caffè e un cornetto, per favore: el desayuno nacional." },
  { id: "ex-asc-014", type: "mc", level: "A1", topic: "ascolto", prompt: "En el diálogo del bar, el camarero pregunta “Al banco o al tavolo?” porque…",
    options: ["el precio cambia", "el café es distinto", "el cornetto está caliente", "cierra pronto"], answer: 0, explain: "Al banco (en la barra) es más barato que al tavolo (en mesa, con servicio)." },
  { id: "ex-asc-015", type: "mc", level: "A1", topic: "ascolto", prompt: "En la escucha de la estación: ¿de qué binario sale el tren a Firenze?",
    options: ["Del binario 9", "Del binario 3", "Del binario 21", "Del binario 1"], answer: 0, explain: "Il treno per Firenze parte dal binario nove: atención al binario, no al andén." },
  { id: "ex-asc-016", type: "mc", level: "A1", topic: "ascolto", prompt: "En la estación anuncian un ritardo. “Ritardo” significa…",
    options: ["retraso", "andén", "billete", "maleta"], answer: 0, explain: "ritardo = retraso. Frase clave: il treno è in ritardo di dieci minuti." },
  { id: "ex-asc-017", type: "mc", level: "A2", topic: "ascolto", prompt: "En la escucha de la farmacia, ¿qué necesita la clienta?",
    options: ["Algo para el dolor de cabeza", "Una receta para la tos", "Vendas", "Vitaminas"], answer: 0, explain: "Mi scusi, ho un forte mal di testa: avete qualcosa?" },
  { id: "ex-asc-018", type: "mc", level: "A2", topic: "vocabolario", prompt: "En la farmacia, “la ricetta” es…",
    options: ["la receta médica", "la caja", "la etiqueta", "la cita"], answer: 0, explain: "la ricetta = la receta (médica); serve la ricetta per questo medicinale." },
  { id: "ex-asc-019", type: "mc", level: "A2", topic: "ascolto", prompt: "En el diálogo del alquiler: ¿qué pide el cliente además del coche?",
    options: ["Un asiento para niño", "Un conductor", "Un GPS gratis", "Seguro total"], answer: 0, explain: "Avrei bisogno anche di un seggiolino per bambini: richiesta clásica." },
  { id: "ex-asc-020", type: "mc", level: "A2", topic: "ascolto", prompt: "En el alquiler, ¿qué documento muestra el cliente?",
    options: ["La patente y el DNI", "Solo el DNI", "El pasaporte y un recibo", "El carné de socio"], answer: 0, explain: "Patente (carné de conducir) + documento d'identità: los dos papeles del contrato." },
  { id: "ex-asc-021", type: "mc", level: "B1", topic: "ascolto", prompt: "En la videollamada de trabajo: ¿qué problema técnico hay al principio?",
    options: ["No se oye a una persona", "No hay internet", "La pantalla está rota", "El link expiró"], answer: 0, explain: "Praga? Ci senti? Non ti sentiamo: prueba clásica de audio antes de empezar." },
  { id: "ex-asc-022", type: "mc", level: "B1", topic: "ascolto", prompt: "En la videollamada, ¿qué acuerdan al final?",
    options: ["Mandarse el acta por email", "Repetir la reunión mañana", "Llamarse por teléfono", "Cancelar el proyecto"], answer: 0, explain: "Ti mando il verbale per email: el resumen escrito cierra toda reunión italiana." },
  { id: "ex-asc-023", type: "mc", level: "B1", topic: "ascolto", prompt: "En la entrevista a la artesana: ¿qué hace Silvia?",
    options: ["Cerámica", "Zapatos", "Joyas", "Queso"], answer: 0, explain: "Silvia fa la ceramista: un'artigiana di Gubbio, terza generación." },
  { id: "ex-asc-024", type: "mc", level: "B1", topic: "ascolto", prompt: "Según Silvia, ¿qué se necesita para su oficio?",
    options: ["Paciencia y manos sucias", "Dinero y contactos", "Estudiar en el extranjero", "Trabajar de noche"], answer: 0, explain: "Ci vuole pazienza, e le mani sporche di argilla: la lección de la artesana." },
  { id: "ex-asc-025", type: "mc", level: "B2", topic: "ascolto", prompt: "En el podcast de economía: ¿qué ha subido según la experta?",
    options: ["Los precios de la energía", "Los sueldos", "El turismo", "El euro"], answer: 0, explain: "I prezzi dell'energia sono aumentati: el punto de partida del debate." },
  { id: "ex-asc-026", type: "mc", level: "B2", topic: "ascolto", prompt: "En el podcast, ¿qué consejo da la experta para ahorrar?",
    options: ["Comparar precios y evitar el desperdicio", "Cambiar de banco", "Dejar de salir", "Comprar solo online"], answer: 0, explain: "Confrontare i prezzi e sprecare meno: las dos palabras de orden." },
  { id: "ex-asc-027", type: "mc", level: "C1", topic: "ascolto", prompt: "En la conferencia sobre dialectos: ¿qué datos da el profesor sobre los jóvenes?",
    options: ["Lo usan con ironía en las redes", "Lo han olvidado del todo", "Lo hablan mejor que sus abuelos", "Lo prohíben en la escuela"], answer: 0, explain: "I giovani lo usano con ironia sui social: el dialecto 2.0 es meme y orgullo." },
  { id: "ex-asc-028", type: "mc", level: "C1", topic: "ascolto", prompt: "Según el profesor, ¿qué unificó el italiano en los años sesenta?",
    options: ["La televisión", "La escuela obligatoria", "Los periódicos", "La radio"], answer: 0, explain: "La televisione ha unificato la lingua negli anni Sessanta: la tesis del profesor." },
];
