import type { Situation } from "../types";

/* ── Situaciones EXTRA · paquete v4.0 ──────────────────────────────── */

export const SITUATIONS_EXTRA_2: Situation[] = [
  {
    id: "sit-treno", emoji: "🚄", title: "En la estación de tren", titleIt: "Alla stazione", level: "A2",
    intro: "Comprar billetes, encontrar el andén y entender los anuncios de la estación sin perder el tren.",
    vocab: [
      { it: "il binario", es: "el andén / la vía" },
      { it: "andata e ritorno", es: "ida y vuelta" },
      { it: "il ritardo", es: "el retraso" },
      { it: "la coincidenza", es: "la correspondencia (conexión)" },
      { it: "convalidare il biglietto", es: "validar el billete" },
      { it: "il treno regionale", es: "el tren regional" },
    ],
    dialogue: [
      { speaker: "Viaggiatrice", it: "Buongiorno, un biglietto per Verona, andata e ritorno.", es: "Buenos días, un billete para Verona, ida y vuelta." },
      { speaker: "Addetto", it: "Per che ora? C'è il Frecciarossa delle nove e il regionale delle nove e mezza.", es: "¿Para qué hora? Está la Frecciarossa de las nueve y el regional de las nueve y media." },
      { speaker: "Viaggiatrice", it: "Il regionale, grazie. Quanto costa?", es: "El regional, gracias. ¿Cuánto cuesta?" },
      { speaker: "Addetto", it: "Dodici euro. Ricordi di convalidare il biglietto prima di salire.", es: "Doce euros. Recuerde validar el billete antes de subir." },
      { speaker: "Viaggiatrice", it: "Da quale binario parte?", es: "¿Desde qué andén sale?" },
      { speaker: "Addetto", it: "Binario sette. Se perde la coincidenza, il biglietto resta valido tutto il giorno.", es: "Andén siete. Si pierde la conexión, el billete sigue válido todo el día." },
    ],
    exerciseIds: ["ex-a2-042", "ex-asc-015"],
    roleplay: { it: "Sei alla biglietteria: chiedi un biglietto per Venezia, orario, prezzo e binario.", es: "Estás en taquilla: pide un billete para Venecia, horario, precio y andén." },
  },
  {
    id: "sit-museo", emoji: "🖼️", title: "En el museo", titleIt: "Al museo", level: "A2",
    intro: "Entradas, audioguías, salas cerradas y el arte de preguntar sin molestar al personal de sala.",
    vocab: [
      { it: "il biglietto intero / ridotto", es: "la entrada general / reducida" },
      { it: "la mostra", es: "la exposición" },
      { it: "l'audioguida", es: "la audioguía" },
      { it: "la sala", es: "la sala" },
      { it: "il guardiano (il custode)", es: "el vigilante de sala" },
      { it: "senza flash", es: "sin flash" },
    ],
    dialogue: [
      { speaker: "Visitatore", it: "Scusi, quanto costa il biglietto intero?", es: "Disculpe, ¿cuánto cuesta la entrada general?" },
      { speaker: "Custode", it: "Quindici euro, il ridotto dieci. C'è anche la mostra su Caravaggio, compresa.", es: "Quince euros, la reducida diez. También está la exposición sobre Caravaggio, incluida." },
      { speaker: "Visitatore", it: "Perfetto. Avete le audioguide in spagnolo?", es: "Perfecto. ¿Tienen audioguías en español?" },
      { speaker: "Custode", it: "Sì, si ritirano all'ingresso con un documento.", es: "Sí, se recogen en la entrada con un documento." },
      { speaker: "Visitatore", it: "Grazie! Si può fotografare?", es: "¡Gracias! ¿Se puede fotografiar?" },
      { speaker: "Custode", it: "Sì, ma senza flash e senza cavalletto.", es: "Sí, pero sin flash y sin trípode." },
    ],
    exerciseIds: ["ex-a2-044", "ex-let-025"],
    roleplay: { it: "Sei all'ingresso di un museo: chiedi biglietti, audioguida e orario di chiusura.", es: "Estás en la entrada de un museo: pregunta entradas, audioguía y hora de cierre." },
  },
  {
    id: "sit-barbiere", emoji: "💈", title: "Del barbero a la peluquería", titleIt: "Dal barbiere", level: "B1",
    intro: "El barbiere es una institución social italiana: aquí se aprende más italiano que en la academia.",
    vocab: [
      { it: "il taglio", es: "el corte" },
      { it: "la barba", es: "la barba" },
      { it: "solo le punte", es: "solo las puntas" },
      { it: "la schiuma", es: "la espuma" },
      { it: "il rasoio", es: "la navaja" },
      { it: "pettinare", es: "peinar" },
    ],
    dialogue: [
      { speaker: "Cliente", it: "Buongiorno, c'è posto per un taglio?", es: "Buenos días, ¿hay hueco para un corte?" },
      { speaker: "Barbiere", it: "Si accomodi, dieci minuti. Come li vogliamo oggi?", es: "Siéntese, diez minutos. ¿Cómo los queremos hoy?" },
      { speaker: "Cliente", it: "Più corti ai lati, sopra uguale. E mi sistemi la barba.", es: "Más cortos a los lados, arriba igual. Y me arregla la barba." },
      { speaker: "Barbiere", it: "Con la schiuma calda o il rasoio elettrico? Sa, col rasoio a mano si sta meglio.", es: "¿Con espuma caliente o maquinilla eléctrica? Ya sabe, con navaja a mano se está mejor." },
      { speaker: "Cliente", it: "Va bene la mano, mi fido. E la partita di ieri, l'ha vista?", es: "Vale la navaja, confío. ¿Y el partido de ayer, lo vio?" },
      { speaker: "Barbiere", it: "Non ne parliamo, meglio i capelli che il calcio!", es: "No hablemos, ¡mejor los pelos que el fútbol!" },
    ],
    exerciseIds: ["ex-b1-031", "ex-b1-032"],
    roleplay: { it: "Dal barbiere: spiega come vuoi i capelli e commenta la partita.", es: "Del barbero: explica cómo quieres el pelo y comenta el partido." },
  },
  {
    id: "sit-vigili", emoji: "🚗", title: "Multa y ZTL: la multa italiana", titleIt: "La multa e la ZTL", level: "B2",
    intro: "Las ZTL (zonas de tráfico limitado) atrapan a más turistas que las gaviotas de Venecia: aquí está el protocolo.",
    vocab: [
      { it: "la multa", es: "la multa" },
      { it: "la ZTL (zona a traffico limitato)", es: "la zona de tráfico limitado" },
      { it: "il verbale", es: "el acta (de denuncia)" },
      { it: "il ricorso", es: "el recurso" },
      { it: "pagare in busta", es: "pagar a plazos (por carta)" },
      { it: "la targa", es: "la matrícula" },
    ],
    dialogue: [
      { speaker: "Turista", it: "Buongiorno, ho ricevuto una multa per ZTL, ma non sapevo…", es: "Buenos días, recibí una multa por ZTL, pero no sabía…" },
      { speaker: "Impiegato", it: "Capisco. La ZTL è attiva in centro dalle 7 alle 20. Il verbale indica data e ora.", es: "Lo entiendo. La ZTL está activa en el centro de 7 a 20. El acta indica fecha y hora." },
      { speaker: "Turista", it: "C'è la possibilità di fare ricorso?", es: "¿Hay posibilidad de poner un recurso?" },
      { speaker: "Impiegato", it: "Può scrivere entro trenta giorni. Ma se paga entro quindici, la multa si riduce del trenta per cento.", es: "Puede escribir dentro de treinta días. Pero si paga dentro de quince, la multa se reduce un treinta por ciento." },
      { speaker: "Turista", it: "Allora conviene pagare subito. Si può fare online?", es: "Entonces conviene pagar enseguida. ¿Se puede hacer online?" },
      { speaker: "Impiegato", it: "Certo, sul sito del comune con il numero del verbale.", es: "Claro, en la web del ayuntamiento con el número del acta." },
    ],
    exerciseIds: ["ex-b2-026", "ex-b2-027"],
    roleplay: { it: "All'ufficio verbali: chiedi spiegazioni sulla multa e come pagarla.", es: "En la oficina de multas: pide explicaciones sobre la multa y cómo pagarla." },
  },
  {
    id: "sit-agriturismo", emoji: "🌾", title: "Agriturismo: dormir en la granja", titleIt: "All'agriturismo", level: "A2",
    intro: "El agriturismo italiano combina granja, cocina y naturaleza: el secreto mejor guardado del turismo lento.",
    vocab: [
      { it: "l'agriturismo", es: "el agroturismo (granja con habitaciones)" },
      { it: "la colazione con i dolci fatti in casa", es: "el desayuno con dulces caseros" },
      { it: "il camino", es: "la chimenea" },
      { it: "il prodotto a chilometro zero", es: "el producto de kilómetro cero" },
      { it: "la camera con vista sui colli", es: "la habitación con vistas a las colinas" },
      { it: "prenotare", es: "reservar" },
    ],
    dialogue: [
      { speaker: "Ospite", it: "Buonasera, ho prenotato una camera doppia per due notti, nome Blanco.", es: "Buenas noches, reservé una habitación doble por dos noches, apellido Blanco." },
      { speaker: "Proprietaria", it: "Benvenuti! La camera con vista sui colli, al primo piano.", es: "¡Bienvenidos! La habitación con vistas a las colinas, en el primer piso." },
      { speaker: "Ospite", it: "La colazione è inclusa?", es: "¿El desayuno está incluido?" },
      { speaker: "Proprietaria", it: "Certo: dolci fatti in casa, marmellate nostre e latte appena munto.", es: "Claro: dulces caseros, mermeladas nuestras y leche recién ordeñada." },
      { speaker: "Ospite", it: "Si può cenare qui?", es: "¿Se puede cenar aquí?" },
      { speaker: "Proprietaria", it: "Sì, stasera c'è la cena della fattoria: tutto a chilometro zero!", es: "Sí, esta noche hay cena de granja: ¡todo de kilómetro cero!" },
    ],
    exerciseIds: ["ex-a2-043", "ex-let-015"],
    roleplay: { it: "Arrivi all'agriturismo: check-in, colazione e cena della fattoria.", es: "Llegas al agriturismo: check-in, desayuno y cena de granja." },
  },
  {
    id: "sit-biblioteca", emoji: "📚", title: "En la biblioteca", titleIt: "In biblioteca", level: "B1",
    intro: "La biblioteca pública italiana: carné, préstamos, salas de estudio y el silencio sagrado.",
    vocab: [
      { it: "la tessera della biblioteca", es: "el carné de la biblioteca" },
      { it: "il prestito", es: "el préstamo" },
      { it: "riconsegnare / restituire", es: "devolver" },
      { it: "la scadenza", es: "el vencimiento" },
      { it: "la sala di lettura", es: "la sala de lectura" },
      { it: "il silenzio, per favore!", es: "¡silencio, por favor!" },
    ],
    dialogue: [
      { speaker: "Studentessa", it: "Scusi, come faccio a iscrivermi alla biblioteca?", es: "Disculpe, ¿cómo me inscribo en la biblioteca?" },
      { speaker: "Bibliotecaria", it: "Basta un documento e il codice fiscale. La tessera è gratuita.", es: "Basta un documento y el código fiscal. El carné es gratuito." },
      { speaker: "Studentessa", it: "Quanti libri posso prendere in prestito?", es: "¿Cuántos libros puedo llevar en préstamo?" },
      { speaker: "Bibliotecaria", it: "Fino a cinque, per trenta giorni. Si può rinnovare online una volta.", es: "Hasta cinco, por treinta días. Se puede renovar online una vez." },
      { speaker: "Studentessa", it: "E se lo riconsegno in ritardo?", es: "¿Y si lo devuelvo con retraso?" },
      { speaker: "Bibliotecaria", it: "Niente multa, ma si blocca il prestito finché non restituisce. In sala di lettura, ricordi: silenzio!", es: "Sin multa, pero se bloquea el préstamo hasta que devuelva. En la sala de lectura, recuerde: ¡silencio!" },
    ],
    exerciseIds: ["ex-b1-032", "ex-let-030"],
    roleplay: { it: "Iscriviti alla biblioteca e chiedi le regole del prestito.", es: "Inscríbete en la biblioteca y pregunta las reglas del préstamo." },
  },
];
